azurerm_postgresql_server:
    status: HOLD
    subcategory: Database
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_postgresql_server'
    description: Manages a PostgreSQL Server.
    arguments:
        name:
            description: Specifies the name of the PostgreSQL Server. Changing this
                forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group in which to create the PostgreSQL
                Server. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        location:
            description: Specifies the supported Azure location where the resource
                exists. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        sku_name:
            description: Specifies the SKU Name for this PostgreSQL Server. The name
                of the SKU, follows the `tier` + `family` + `cores` pattern (e.g.
                `B_Gen4_1`, `GP_Gen5_8`). For more information see the [product documentation](https://docs.microsoft.com/en-us/rest/api/postgresql/servers/create#sku).
            required: true
            policy: ''
            notes: ''
        storage_profile:
            description: A `storage_profile` block as defined below.
            required: true
            policy: ''
            notes: ''
        administrator_login:
            description: The Administrator Login for the PostgreSQL Server. Changing
                this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        administrator_login_password:
            description: The Password associated with the `administrator_login` for
                the PostgreSQL Server.
            required: true
            policy: ''
            notes: ''
        version:
            description: Specifies the version of PostgreSQL to use. Valid values
                are `9.5`, `9.6`, `10`, `10.0`, and `11`. Changing this forces a new
                resource to be created.
            required: true
            policy: ''
            notes: ''
        ssl_enforcement:
            description: Specifies if SSL should be enforced on connections. Possible
                values are `Enabled` and `Disabled`.
            required: true
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
        storage_mb:
            description: Max storage allowed for a server. Possible values are between
                `5120` MB(5GB
            required: true
            policy: ''
            notes: ''
        backup_retention_days:
            description: Backup retention days for the server, supported values are
                between `7` and `35` days.
            required: false
            policy: ''
            notes: ''
        geo_redundant_backup:
            description: Enable/Disable Geo-redundant for server backup. Valid values
                for this property are `Enabled` or `Disabled`, not supported for the
                `basic` tier.  This allows you to choose between locally redundant
                or geo-redundant backup storage in the General Purpose and Memory
                Optimized tiers. When the backups are stored in geo-redundant backup
                storage, they are not only stored within the region in which your
                server is hosted, but are also replicated to a paired data center.
                This provides better protection and ability to restore your server
                in a different region in the event of a disaster. The Basic tier only
                offers locally redundant backup storage.
            required: false
            policy: ''
            notes: ''
        auto_grow:
            description: 'Enable/Disable auto-growing of the storage. Valid values
                for this property are `Enabled` or `Disabled`. Storage auto-grow prevents
                your server from running out of storage and becoming read-only. If
                storage auto grow is enabled, the storage automatically grows without
                impacting the workload. The default value if not explicitly specified
                is `Enabled`.  '
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the PostgreSQL Server.
        fqdn:
            description: The FQDN of the PostgreSQL Server.
    timeouts:
        create:
            description: Used when creating the PostgreSQL Server.
            required: false
            timeout: 60
        update:
            description: Used when updating the PostgreSQL Server.
            required: false
            timeout: 60
        read:
            description: Used when retrieving the PostgreSQL Server.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the PostgreSQL Server.
            required: false
            timeout: 60
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbUZ3YVMxeVp5MXdjbThpQ2lBZ2JHOWpZWFJwYjI0Z1BT
        QWlWMlZ6ZENCRmRYSnZjR1VpQ24wS0NuSmxjMjkxY21ObElDSmhlblZ5WlhKdFgzQnZjM1JuY21W
        emNXeGZjMlZ5ZG1WeUlpQWlaWGhoYlhCc1pTSWdld29nSUc1aGJXVWdJQ0FnSUNBZ0lDQWdJQ0Fn
        SUNBZ1BTQWljRzl6ZEdkeVpYTnhiQzF6WlhKMlpYSXRNU0lLSUNCc2IyTmhkR2x2YmlBZ0lDQWdJ
        Q0FnSUNBZ0lEMGdZWHAxY21WeWJWOXlaWE52ZFhKalpWOW5jbTkxY0M1bGVHRnRjR3hsTG14dlky
        RjBhVzl1Q2lBZ2NtVnpiM1Z5WTJWZlozSnZkWEJmYm1GdFpTQTlJR0Y2ZFhKbGNtMWZjbVZ6YjNW
        eVkyVmZaM0p2ZFhBdVpYaGhiWEJzWlM1dVlXMWxDZ29nSUhOcmRWOXVZVzFsSUQwZ0lrSmZSMlZ1
        TlY4eUlnb0tJQ0J6ZEc5eVlXZGxYM0J5YjJacGJHVWdld29nSUNBZ2MzUnZjbUZuWlY5dFlpQWdJ
        Q0FnSUNBZ0lDQWdJRDBnTlRFeU1Bb2dJQ0FnWW1GamEzVndYM0psZEdWdWRHbHZibDlrWVhseklE
        MGdOd29nSUNBZ1oyVnZYM0psWkhWdVpHRnVkRjlpWVdOcmRYQWdJRDBnSWtScGMyRmliR1ZrSWdv
        Z0lDQWdZWFYwYjE5bmNtOTNJQ0FnSUNBZ0lDQWdJQ0FnSUQwZ0lrVnVZV0pzWldRaUNpQWdmUW9L
        SUNCaFpHMXBibWx6ZEhKaGRHOXlYMnh2WjJsdUlDQWdJQ0FnSUNBZ0lEMGdJbkJ6Y1d4aFpHMXBi
        blZ1SWdvZ0lHRmtiV2x1YVhOMGNtRjBiM0pmYkc5bmFXNWZjR0Z6YzNkdmNtUWdQU0FpU0VCVGFE
        RkRiMUl6SVNJS0lDQjJaWEp6YVc5dUlDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJRDBnSWpr
        dU5TSUtJQ0J6YzJ4ZlpXNW1iM0pqWlcxbGJuUWdJQ0FnSUNBZ0lDQWdJQ0FnSUQwZ0lrVnVZV0pz
        WldRaUNuMEs=
    import: !!binary |
        Q2dwUWIzTjBaM0psVTFGTUlGTmxjblpsY2lkeklHTmhiaUJpWlNCcGJYQnZjblJsWkNCMWMybHVa
        eUIwYUdVZ1lISmxjMjkxY21ObElHbGtZQ3dnWlM1bkxnb0s=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmNHOXpkR2R5WlhOeGJGOXpaWEoyWlhJdWFIUnRiQzV0WVhKclpHOTNiZz09
