azurerm_private_dns_mx_record:
    status: ASSESS
    subcategory: Private DNS
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_private_dns_mx_record'
    description: Manages a Private DNS MX Record.
    arguments:
        name:
            description: The name of the DNS MX Record. Changing this forces a new
                resource to be created. Default to '@' for root zone entry.
            required: false
            policy: ''
            notes: ''
        resource_group_name:
            description: Specifies the resource group where the resource exists. Changing
                this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        zone_name:
            description: Specifies the Private DNS Zone where the resource exists.
                Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        record:
            description: One or more `record` blocks as defined below.
            required: true
            policy: ''
            notes: ''
        'ttl ':
            description: The Time To Live (TTL
            required: true
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
        preference:
            description: The preference of the MX record.
            required: true
            policy: ''
            notes: ''
        exchange:
            description: The FQDN of the exchange to MX record points to.
            required: true
            policy: ''
            notes: ''
    attributes:
        id:
            description: The Private DNS MX Record ID.
        fqdn:
            description: The FQDN of the DNS MX Record.
    timeouts:
        create:
            description: Used when creating the Private DNS MX Record.
            required: false
            timeout: 30
        update:
            description: Used when updating the Private DNS MX Record.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Private DNS MX Record.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Private DNS MX Record.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbUZqWTJWd2RHRnVZMlZVWlhOMFVtVnpiM1Z5WTJWSGNt
        OTFjREVpQ2lBZ2JHOWpZWFJwYjI0Z1BTQWlWMlZ6ZENCVlV5SUtmUW9LY21WemIzVnlZMlVnSW1G
        NmRYSmxjbTFmY0hKcGRtRjBaVjlrYm5OZmVtOXVaU0lnSW1WNFlXMXdiR1VpSUhzS0lDQnVZVzFs
        SUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJRDBnSW1OdmJuUnZjMjh1WTI5dElnb2dJSEpsYzI5MWNtTmxY
        MmR5YjNWd1gyNWhiV1VnUFNCaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndMbVY0WVcxd2JH
        VXVibUZ0WlFwOUNncHlaWE52ZFhKalpTQWlZWHAxY21WeWJWOXdjbWwyWVhSbFgyUnVjMTl0ZUY5
        eVpXTnZjbVFpSUNKbGVHRnRjR3hsSWlCN0NpQWdibUZ0WlNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0E5
        SUNKbGVHRnRjR3hsSWdvZ0lISmxjMjkxY21ObFgyZHliM1Z3WDI1aGJXVWdQU0JoZW5WeVpYSnRY
        M0psYzI5MWNtTmxYMmR5YjNWd0xtVjRZVzF3YkdVdWJtRnRaUW9nSUhwdmJtVmZibUZ0WlNBZ0lD
        QWdJQ0FnSUNBZ1BTQmhlblZ5WlhKdFgzQnlhWFpoZEdWZlpHNXpYM3B2Ym1VdVpYaGhiWEJzWlM1
        dVlXMWxDaUFnZEhSc0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBOUlETXdNQW9LSUNCeVpXTnZjbVFn
        ZXdvZ0lDQWdjSEpsWm1WeVpXNWpaU0E5SURFd0NpQWdJQ0JsZUdOb1lXNW5aU0FnSUQwZ0ltMTRN
        UzVqYjI1MGIzTnZMbU52YlNJS0lDQjlDZ29nSUhKbFkyOXlaQ0I3Q2lBZ0lDQndjbVZtWlhKbGJt
        TmxJRDBnTWpBS0lDQWdJR1Y0WTJoaGJtZGxJQ0FnUFNBaVltRmphM1Z3YlhndVkyOXVkRzl6Ynk1
        amIyMGlDaUFnZlFvS0lDQjBZV2R6SUQwZ2V3b2dJQ0FnUlc1MmFYSnZibTFsYm5RZ1BTQWlVSEp2
        WkhWamRHbHZiaUlLSUNCOUNuMEs=
    import: !!binary |
        Q2dwUWNtbDJZWFJsSUVST1V5Qk5XQ0JTWldOdmNtUnpJR05oYmlCaVpTQnBiWEJ2Y25SbFpDQjFj
        Mmx1WnlCMGFHVWdZSEpsYzI5MWNtTmxJR2xrWUN3Z1pTNW5MZ29L
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmNISnBkbUYwWlY5a2JuTmZiWGhmY21WamIzSmtMbWgwYld3dWJXRnlhMlJ2ZDI0
        PQ==
