azurerm_dns_srv_record:
    status: ASSESS
    subcategory: DNS
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_dns_srv_record'
    description: Manages a DNS SRV Record.
    arguments:
        name:
            description: The name of the DNS SRV Record.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: Specifies the resource group where the resource exists. Changing
                this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        zone_name:
            description: Specifies the DNS Zone where the DNS Zone (parent resource
            required: true
            policy: ''
            notes: ''
        ttl:
            description: The Time To Live (TTL
            required: true
            policy: ''
            notes: ''
        record:
            description: A list of values that make up the SRV record. Each `record`
                block supports fields documented below.
            required: true
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
        priority:
            description: Priority of the SRV record.
            required: true
            policy: ''
            notes: ''
        weight:
            description: Weight of the SRV record.
            required: true
            policy: ''
            notes: ''
        port:
            description: Port the service is listening on.
            required: true
            policy: ''
            notes: ''
        target:
            description: FQDN of the service.
            required: true
            policy: ''
            notes: ''
    attributes:
        id:
            description: The DNS SRV Record ID.
        fqdn:
            description: The FQDN of the DNS SRV Record.
    timeouts:
        create:
            description: Used when creating the DNS SRV Record.
            required: false
            timeout: 30
        update:
            description: Used when updating the DNS SRV Record.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the DNS SRV Record.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the DNS SRV Record.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbUZqWTJWd2RHRnVZMlZVWlhOMFVtVnpiM1Z5WTJWSGNt
        OTFjREVpQ2lBZ2JHOWpZWFJwYjI0Z1BTQWlWMlZ6ZENCVlV5SUtmUW9LY21WemIzVnlZMlVnSW1G
        NmRYSmxjbTFmWkc1elgzcHZibVVpSUNKbGVHRnRjR3hsSWlCN0NpQWdibUZ0WlNBZ0lDQWdJQ0Fn
        SUNBZ0lDQWdJQ0E5SUNKdGVXUnZiV0ZwYmk1amIyMGlDaUFnY21WemIzVnlZMlZmWjNKdmRYQmZi
        bUZ0WlNBOUlHRjZkWEpsY20xZmNtVnpiM1Z5WTJWZlozSnZkWEF1WlhoaGJYQnNaUzV1WVcxbENu
        MEtDbkpsYzI5MWNtTmxJQ0poZW5WeVpYSnRYMlJ1YzE5emNuWmZjbVZqYjNKa0lpQWlaWGhoYlhC
        c1pTSWdld29nSUc1aGJXVWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ1BTQWlkR1Z6ZENJS0lDQjZiMjVs
        WDI1aGJXVWdJQ0FnSUNBZ0lDQWdJRDBnWVhwMWNtVnliVjlrYm5OZmVtOXVaUzVsZUdGdGNHeGxM
        bTVoYldVS0lDQnlaWE52ZFhKalpWOW5jbTkxY0Y5dVlXMWxJRDBnWVhwMWNtVnliVjl5WlhOdmRY
        SmpaVjluY205MWNDNWxlR0Z0Y0d4bExtNWhiV1VLSUNCMGRHd2dJQ0FnSUNBZ0lDQWdJQ0FnSUNB
        Z0lEMGdNekF3Q2dvZ0lISmxZMjl5WkNCN0NpQWdJQ0J3Y21sdmNtbDBlU0E5SURFS0lDQWdJSGRs
        YVdkb2RDQWdJRDBnTlFvZ0lDQWdjRzl5ZENBZ0lDQWdQU0E0TURnd0NpQWdJQ0IwWVhKblpYUWdJ
        Q0E5SUNKMFlYSm5aWFF4TG1OdmJuUnZjMjh1WTI5dElnb2dJSDBLQ2lBZ2RHRm5jeUE5SUhzS0lD
        QWdJRVZ1ZG1seWIyNXRaVzUwSUQwZ0lsQnliMlIxWTNScGIyNGlDaUFnZlFwOUNnPT0=
    import: !!binary |
        Q2dwVFVsWWdjbVZqYjNKa2N5QmpZVzRnWW1VZ2FXMXdiM0owWldRZ2RYTnBibWNnZEdobElHQnla
        WE52ZFhKalpTQnBaR0FzSUdVdVp5NEtDZz09
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdlpHNXpYM055ZGw5eVpXTnZjbVF1YUhSdGJDNXRZWEpyWkc5M2JnPT0=
