azurerm_snapshot:
    status: ASSESS
    subcategory: Compute
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_snapshot'
    description: Manages a Disk Snapshot.
    arguments:
        name:
            description: Specifies the name of the Snapshot resource. Changing this
                forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group in which to create the Snapshot.
                Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        location:
            description: Specifies the supported Azure location where the resource
                exists. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        create_option:
            description: Indicates how the snapshot is to be created. Possible values
                are `Copy` or `Import`. Changing this forces a new resource to be
                created.
            required: true
            policy: ''
            notes: ''
        source_uri:
            description: Specifies the URI to a Managed or Unmanaged Disk. Changing
                this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        source_resource_id:
            description: Specifies a reference to an existing snapshot, when `create_option`
                is `Copy`. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        storage_account_id:
            description: Specifies the ID of an storage account. Used with `source_uri`
                to allow authorization during import of unmanaged blobs from a different
                subscription. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        disk_size_gb:
            description: The size of the Snapshotted Disk in GB.
            required: false
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The Snapshot ID.
        disk_size_gb:
            description: The Size of the Snapshotted Disk in GB.
    timeouts:
        create:
            description: Used when creating the Snapshot.
            required: false
            timeout: 30
        update:
            description: Used when updating the Snapshot.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Snapshot.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Snapshot.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbk51WVhCemFHOTBMWEpuSWdvZ0lHeHZZMkYwYVc5dUlE
        MGdJbGRsYzNRZ1JYVnliM0JsSWdwOUNncHlaWE52ZFhKalpTQWlZWHAxY21WeWJWOXRZVzVoWjJW
        a1gyUnBjMnNpSUNKbGVHRnRjR3hsSWlCN0NpQWdibUZ0WlNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0Fn
        UFNBaWJXRnVZV2RsWkMxa2FYTnJJZ29nSUd4dlkyRjBhVzl1SUNBZ0lDQWdJQ0FnSUNBZ0lEMGdZ
        WHAxY21WeWJWOXlaWE52ZFhKalpWOW5jbTkxY0M1bGVHRnRjR3hsTG14dlkyRjBhVzl1Q2lBZ2Nt
        VnpiM1Z5WTJWZlozSnZkWEJmYm1GdFpTQWdQU0JoZW5WeVpYSnRYM0psYzI5MWNtTmxYMmR5YjNW
        d0xtVjRZVzF3YkdVdWJtRnRaUW9nSUhOMGIzSmhaMlZmWVdOamIzVnVkRjkwZVhCbElEMGdJbE4w
        WVc1a1lYSmtYMHhTVXlJS0lDQmpjbVZoZEdWZmIzQjBhVzl1SUNBZ0lDQWdJQ0E5SUNKRmJYQjBl
        U0lLSUNCa2FYTnJYM05wZW1WZloySWdJQ0FnSUNBZ0lDQTlJQ0l4TUNJS2ZRb0tjbVZ6YjNWeVky
        VWdJbUY2ZFhKbGNtMWZjMjVoY0hOb2IzUWlJQ0psZUdGdGNHeGxJaUI3Q2lBZ2JtRnRaU0FnSUNB
        Z0lDQWdJQ0FnSUNBZ0lDQTlJQ0p6Ym1Gd2MyaHZkQ0lLSUNCc2IyTmhkR2x2YmlBZ0lDQWdJQ0Fn
        SUNBZ0lEMGdZWHAxY21WeWJWOXlaWE52ZFhKalpWOW5jbTkxY0M1bGVHRnRjR3hsTG14dlkyRjBh
        Vzl1Q2lBZ2NtVnpiM1Z5WTJWZlozSnZkWEJmYm1GdFpTQTlJR0Y2ZFhKbGNtMWZjbVZ6YjNWeVky
        VmZaM0p2ZFhBdVpYaGhiWEJzWlM1dVlXMWxDaUFnWTNKbFlYUmxYMjl3ZEdsdmJpQWdJQ0FnSUNB
        OUlDSkRiM0I1SWdvZ0lITnZkWEpqWlY5MWNta2dJQ0FnSUNBZ0lDQWdQU0JoZW5WeVpYSnRYMjFo
        Ym1GblpXUmZaR2x6YXk1bGVHRnRjR3hsTG1sa0NuMEs=
    import: !!binary |
        Q2dwVGJtRndjMmh2ZEhNZ1kyRnVJR0psSUdsdGNHOXlkR1ZrSUhWemFXNW5JSFJvWlNCZ2NtVnpi
        M1Z5WTJVZ2FXUmdMQ0JsTG1jdUNnbz0=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmMyNWhjSE5vYjNRdWFIUnRiQzV0WVhKclpHOTNiZz09
