azurerm_api_management_identity_provider_google:
    status: ASSESS
    subcategory: API Management
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_api_management_identity_provider_google'
    description: Manages an API Management Google Identity Provider.
    arguments:
        api_management_name:
            description: The Name of the API Management Service where this Google
                Identity Provider should be created. Changing this forces a new resource
                to be created.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: The Name of the Resource Group where the API Management Service
                exists. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        client_id:
            description: Client Id for Google Sign-in.
            required: true
            policy: ''
            notes: ''
        client_secret:
            description: Client secret for Google Sign-in.
            required: true
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the API Management Google Identity Provider.
    timeouts:
        create:
            description: Used when creating the API Management Google Identity Provider.
            required: false
            timeout: 30
        update:
            description: Used when updating the API Management Google Identity Provider.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the API Management Google Identity Provider.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the API Management Google Identity Provider.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbVY0WVcxd2JHVXRjbVZ6YjNWeVkyVnpJZ29nSUd4dlky
        RjBhVzl1SUQwZ0lsZGxjM1FnUlhWeWIzQmxJZ3A5Q2dweVpYTnZkWEpqWlNBaVlYcDFjbVZ5YlY5
        aGNHbGZiV0Z1WVdkbGJXVnVkQ0lnSW1WNFlXMXdiR1VpSUhzS0lDQnVZVzFsSUNBZ0lDQWdJQ0Fn
        SUNBZ0lDQWdJRDBnSW1WNFlXMXdiR1V0WVhCcGJTSUtJQ0JzYjJOaGRHbHZiaUFnSUNBZ0lDQWdJ
        Q0FnSUQwZ1lYcDFjbVZ5YlY5eVpYTnZkWEpqWlY5bmNtOTFjQzVsZUdGdGNHeGxMbXh2WTJGMGFX
        OXVDaUFnY21WemIzVnlZMlZmWjNKdmRYQmZibUZ0WlNBOUlHRjZkWEpsY20xZmNtVnpiM1Z5WTJW
        ZlozSnZkWEF1WlhoaGJYQnNaUzV1WVcxbENpQWdjSFZpYkdsemFHVnlYMjVoYldVZ0lDQWdJQ0E5
        SUNKTmVTQkRiMjF3WVc1NUlnb2dJSEIxWW14cGMyaGxjbDlsYldGcGJDQWdJQ0FnUFNBaVkyOXRj
        R0Z1ZVVCMFpYSnlZV1p2Y20wdWFXOGlDaUFnYzJ0MVgyNWhiV1VnSUNBZ0lDQWdJQ0FnSUNBOUlD
        SkVaWFpsYkc5d1pYSmZNU0lLZlFvS2NtVnpiM1Z5WTJVZ0ltRjZkWEpsY20xZllYQnBYMjFoYm1G
        blpXMWxiblJmYVdSbGJuUnBkSGxmY0hKdmRtbGtaWEpmWjI5dloyeGxJaUFpWlhoaGJYQnNaU0ln
        ZXdvZ0lISmxjMjkxY21ObFgyZHliM1Z3WDI1aGJXVWdQU0JoZW5WeVpYSnRYM0psYzI5MWNtTmxY
        MmR5YjNWd0xtVjRZVzF3YkdVdWJtRnRaUW9nSUdGd2FWOXRZVzVoWjJWdFpXNTBYMjVoYldVZ1BT
        QmhlblZ5WlhKdFgyRndhVjl0WVc1aFoyVnRaVzUwTG1WNFlXMXdiR1V1Ym1GdFpRb2dJR05zYVdW
        dWRGOXBaQ0FnSUNBZ0lDQWdJQ0FnUFNBaU1EQXdNREF3TURBdVlYQndjeTVuYjI5bmJHVjFjMlZ5
        WTI5dWRHVnVkQzVqYjIwaUNpQWdZMnhwWlc1MFgzTmxZM0psZENBZ0lDQWdJQ0E5SUNJd01EQXdN
        REF3TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNQ0lLZlFvPQ==
    import: !!binary |
        Q2dwQlVFa2dUV0Z1WVdkbGJXVnVkQ0JIYjI5bmJHVWdTV1JsYm5ScGRIa2dVSEp2ZG1sa1pYSWdZ
        MkZ1SUdKbElHbHRjRzl5ZEdWa0lIVnphVzVuSUhSb1pTQmdjbVZ6YjNWeVkyVWdhV1JnTENCbExt
        Y3VDZ289
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdllYQnBYMjFoYm1GblpXMWxiblJmYVdSbGJuUnBkSGxmY0hKdmRtbGtaWEpmWjI5
        dloyeGxMbWgwYld3dWJXRnlhMlJ2ZDI0PQ==
