azurerm_managed_disk:
    status: ASSESS
    subcategory: Compute
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_managed_disk'
    description: Manages a Managed Disk.
    arguments:
        name:
            description: Specifies the name of the Managed Disk. Changing this forces
                a new resource to be created.
            required: false
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the Resource Group where the Managed Disk should
                exist.
            required: false
            policy: ''
            notes: ''
        location:
            description: Specified the supported Azure location where the resource
                exists. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        storage_account_type:
            description: The type of storage to use for the managed disk. Possible
                values are `Standard_LRS`, `Premium_LRS`, `StandardSSD_LRS` or `UltraSSD_LRS`.
            required: false
            policy: ''
            notes:
            - '-> **Note**: A `storage_account_type` of type `UltraSSD_LRS` and the
                arguments `disk_iops_read_write` and `disk_mbps_read_write` are currently
                in private preview and are not available to subscriptions that have
                not requested onboarding to `Azure Ultra Disk Storage` private preview.
                `Azure Ultra Disk Storage` is only available in `East US 2`, `North
                Europe`, and `Southeast Asia` regions. For more information see the
                `Azure Ultra Disk Storage` [product documentation](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disks-enable-ultra-ssd),
                [product blog](https://azure.microsoft.com/en-us/blog/announcing-the-general-availability-of-azure-ultra-disk-storage/)
                and [FAQ](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/faq-for-disks#ultra-disks).'
        create_option:
            description: 'The method to use when creating the managed disk. Changing
                this forces a new resource to be created. Possible values include:'
            required: false
            policy: ''
            notes: ''
        disk_encryption_set_id:
            description: The ID of a Disk Encryption Set which should be used to encrypt
                this Managed Disk.
            required: false
            policy: ''
            notes:
            - '-> '
            - ' The Disk Encryption Set must have the `Reader` Role Assignment scoped
                on the Key Vault - in addition to an Access Policy to the Key Vault'
        disk_iops_read_write:
            description: The number of IOPS allowed for this disk; only settable for
                UltraSSD disks. One operation can transfer between 4k and 256k bytes.
            required: false
            policy: ''
            notes: ''
        disk_mbps_read_write:
            description: The bandwidth allowed for this disk; only settable for UltraSSD
                disks. MBps means millions of bytes per second.
            required: false
            policy: ''
            notes: ''
        disk_size_gb:
            description: Specifies the size of the managed disk to create in gigabytes.
                If `create_option` is `Copy` or `FromImage`, then the value must be
                equal to or greater than the source's size. The size can only be increased.
            required: false
            policy: ''
            notes: ''
        encryption_settings:
            description: A `encryption_settings` block as defined below.
            required: false
            policy: ''
            notes: ''
        image_reference_id:
            description: ID of an existing platform/marketplace disk image to copy
                when `create_option` is `FromImage`.
            required: false
            policy: ''
            notes: ''
        os_type:
            description: Specify a value when the source of an `Import` or `Copy`
                operation targets a source that contains an operating system. Valid
                values are `Linux` or `Windows`.
            required: false
            policy: ''
            notes: ''
        source_resource_id:
            description: The ID of an existing Managed Disk to copy `create_option`
                is `Copy` or the recovery point to restore when `create_option` is
                `Restore`
            required: false
            policy: ''
            notes: ''
        source_uri:
            description: URI to a valid VHD file to be used when `create_option` is
                `Import`.
            required: false
            policy: ''
            notes: ''
        storage_account_id:
            description: The ID of the Storage Account where the `source_uri` is located.
                Required when `create_option` is set to `Import`.  Changing this forces
                a new resource to be created.
            required: false
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
        zones:
            description: A collection containing the availability zone to allocate
                the Managed Disk in.
            required: false
            policy: ''
            notes:
            - '-> **Note**: Availability Zones are [only supported in select regions
                at this time](https://docs.microsoft.com/en-us/azure/availability-zones/az-overview).'
        secret_url:
            description: The URL to the Key Vault Secret used as the Disk Encryption
                Key. This can be found as `id` on the `azurerm_key_vault_secret` resource.
            required: false
            policy: ''
            notes: ''
        source_vault_id:
            description: The ID of the source Key Vault.
            required: false
            policy: ''
            notes: ''
        enabled:
            description: Is Encryption enabled on this Managed Disk? Changing this
                forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        disk_encryption_key:
            description: A `disk_encryption_key` block as defined above.
            required: false
            policy: ''
            notes: ''
        key_encryption_key:
            description: A `key_encryption_key` block as defined below.
            required: false
            policy: ''
            notes: ''
        key_url:
            description: The URL to the Key Vault Key used as the Key Encryption Key.
                This can be found as `id` on the `azurerm_key_vault_key` resource.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the Managed Disk.
    timeouts:
        create:
            description: Used when creating the Managed Disk.
            required: false
            timeout: 30
        update:
            description: Used when updating the Managed Disk.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Managed Disk.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Managed Disk.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbVY0WVcxd2JHVXRjbVZ6YjNWeVkyVnpJZ29nSUd4dlky
        RjBhVzl1SUQwZ0lsZGxjM1FnVlZNZ01pSUtmUW9LY21WemIzVnlZMlVnSW1GNmRYSmxjbTFmYldG
        dVlXZGxaRjlrYVhOcklpQWlaWGhoYlhCc1pTSWdld29nSUc1aGJXVWdJQ0FnSUNBZ0lDQWdJQ0Fn
        SUNBZ0lEMGdJbUZqWTNSbGMzUnRaQ0lLSUNCc2IyTmhkR2x2YmlBZ0lDQWdJQ0FnSUNBZ0lDQTlJ
        Q0pYWlhOMElGVlRJRElpQ2lBZ2NtVnpiM1Z5WTJWZlozSnZkWEJmYm1GdFpTQWdQU0JoZW5WeVpY
        SnRYM0psYzI5MWNtTmxYMmR5YjNWd0xtVjRZVzF3YkdVdWJtRnRaUW9nSUhOMGIzSmhaMlZmWVdO
        amIzVnVkRjkwZVhCbElEMGdJbE4wWVc1a1lYSmtYMHhTVXlJS0lDQmpjbVZoZEdWZmIzQjBhVzl1
        SUNBZ0lDQWdJQ0E5SUNKRmJYQjBlU0lLSUNCa2FYTnJYM05wZW1WZloySWdJQ0FnSUNBZ0lDQTlJ
        Q0l4SWdvS0lDQjBZV2R6SUQwZ2V3b2dJQ0FnWlc1MmFYSnZibTFsYm5RZ1BTQWljM1JoWjJsdVp5
        SUtJQ0I5Q24wSw==
    import: !!binary |
        Q2dwTllXNWhaMlZrSUVScGMydHpJR05oYmlCaVpTQnBiWEJ2Y25SbFpDQjFjMmx1WnlCMGFHVWdZ
        SEpsYzI5MWNtTmxJR2xrWUN3Z1pTNW5MZ29L
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmJXRnVZV2RsWkY5a2FYTnJMbWgwYld3dWJXRnlhMlJ2ZDI0PQ==
