azurerm_dns_txt_record:
    status: HOLD
    subcategory: DNS
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_dns_txt_record'
    description: Manages a DNS TXT Record.
    arguments:
        name:
            description: The name of the DNS TXT Record.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: Specifies the resource group where the resource exists. Changing
                this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        zone_name:
            description: Specifies the DNS Zone where the DNS Zone (parent resource
            required: true
            policy: ''
            notes: ''
        ttl:
            description: The Time To Live (TTL
            required: true
            policy: ''
            notes: ''
        record:
            description: A list of values that make up the txt record. Each `record`
                block supports fields documented below.
            required: true
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
        value:
            description: 'The value of the record. Max length: 1024 characters'
            required: true
            policy: ''
            notes: ''
    attributes:
        id:
            description: The DNS TXT Record ID.
        fqdn:
            description: The FQDN of the DNS TXT Record.
    timeouts:
        create:
            description: Used when creating the DNS TXT Record.
            required: false
            timeout: 30
        update:
            description: Used when updating the DNS TXT Record.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the DNS TXT Record.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the DNS TXT Record.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbUZqWTJWd2RHRnVZMlZVWlhOMFVtVnpiM1Z5WTJWSGNt
        OTFjREVpQ2lBZ2JHOWpZWFJwYjI0Z1BTQWlWMlZ6ZENCVlV5SUtmUW9LY21WemIzVnlZMlVnSW1G
        NmRYSmxjbTFmWkc1elgzcHZibVVpSUNKbGVHRnRjR3hsSWlCN0NpQWdibUZ0WlNBZ0lDQWdJQ0Fn
        SUNBZ0lDQWdJQ0E5SUNKdGVXUnZiV0ZwYmk1amIyMGlDaUFnY21WemIzVnlZMlZmWjNKdmRYQmZi
        bUZ0WlNBOUlHRjZkWEpsY20xZmNtVnpiM1Z5WTJWZlozSnZkWEF1WlhoaGJYQnNaUzV1WVcxbENu
        MEtDbkpsYzI5MWNtTmxJQ0poZW5WeVpYSnRYMlJ1YzE5MGVIUmZjbVZqYjNKa0lpQWlaWGhoYlhC
        c1pTSWdld29nSUc1aGJXVWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ1BTQWlkR1Z6ZENJS0lDQjZiMjVs
        WDI1aGJXVWdJQ0FnSUNBZ0lDQWdJRDBnWVhwMWNtVnliVjlrYm5OZmVtOXVaUzVsZUdGdGNHeGxM
        bTVoYldVS0lDQnlaWE52ZFhKalpWOW5jbTkxY0Y5dVlXMWxJRDBnWVhwMWNtVnliVjl5WlhOdmRY
        SmpaVjluY205MWNDNWxlR0Z0Y0d4bExtNWhiV1VLSUNCMGRHd2dJQ0FnSUNBZ0lDQWdJQ0FnSUNB
        Z0lEMGdNekF3Q2dvZ0lISmxZMjl5WkNCN0NpQWdJQ0IyWVd4MVpTQTlJQ0puYjI5bmJHVXRjMmww
        WlMxaGRYUm9aVzUwYVdOaGRHOXlJZ29nSUgwS0NpQWdjbVZqYjNKa0lIc0tJQ0FnSUhaaGJIVmxJ
        RDBnSW0xdmNtVWdjMmwwWlNCcGJtWnZjbTFoZEdsdmJpQm9aWEpsSWdvZ0lIMEtDaUFnZEdGbmN5
        QTlJSHNLSUNBZ0lFVnVkbWx5YjI1dFpXNTBJRDBnSWxCeWIyUjFZM1JwYjI0aUNpQWdmUXA5Q2c9
        PQ==
    import: !!binary |
        Q2dwVVdGUWdjbVZqYjNKa2N5QmpZVzRnWW1VZ2FXMXdiM0owWldRZ2RYTnBibWNnZEdobElHQnla
        WE52ZFhKalpTQnBaR0FzSUdVdVp5NEtDZz09
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdlpHNXpYM1I0ZEY5eVpXTnZjbVF1YUhSdGJDNXRZWEpyWkc5M2JnPT0=
