azurerm_storage_container:
    status: ASSESS
    subcategory: Storage
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_storage_container'
    description: Manages a Container within an Azure Storage Account.
    arguments:
        name:
            description: The name of the Container which should be created within
                the Storage Account.
            required: true
            policy: ''
            notes: ''
        storage_account_name:
            description: The name of the Storage Account where the Container should
                be created.
            required: true
            policy: ''
            notes: ''
        container_access_type:
            description: The Access Level configured for this Container. Possible
                values are `blob`, `container` or `private`. Defaults to `private`.
            required: false
            policy: ''
            notes: ''
        metadata:
            description: A mapping of MetaData for this Container.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the Storage Container.
        has_immutability_policy:
            description: Is there an Immutability Policy configured on this Storage
                Container?
        has_legal_hold:
            description: Is there a Legal Hold configured on this Storage Container?
        resource_manager_id:
            description: The Resource Manager ID of this Storage Container.
    timeouts:
        create:
            description: Used when creating the Storage Container.
            required: false
            timeout: 30
        update:
            description: Used when updating the Storage Container.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Storage Container.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Storage Container.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbVY0WVcxd2JHVXRjbVZ6YjNWeVkyVnpJZ29nSUd4dlky
        RjBhVzl1SUQwZ0lsZGxjM1FnUlhWeWIzQmxJZ3A5Q2dweVpYTnZkWEpqWlNBaVlYcDFjbVZ5YlY5
        emRHOXlZV2RsWDJGalkyOTFiblFpSUNKbGVHRnRjR3hsSWlCN0NpQWdibUZ0WlNBZ0lDQWdJQ0Fn
        SUNBZ0lDQWdJQ0FnSUNBZ0lEMGdJbVY0WVcxd2JHVnpkRzl5WVdOamIzVnVkQ0lLSUNCeVpYTnZk
        WEpqWlY5bmNtOTFjRjl1WVcxbElDQWdJQ0FnUFNCaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIz
        VndMbVY0WVcxd2JHVXVibUZ0WlFvZ0lHeHZZMkYwYVc5dUlDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNB
        OUlHRjZkWEpsY20xZmNtVnpiM1Z5WTJWZlozSnZkWEF1WlhoaGJYQnNaUzVzYjJOaGRHbHZiZ29n
        SUdGalkyOTFiblJmZEdsbGNpQWdJQ0FnSUNBZ0lDQWdJQ0E5SUNKVGRHRnVaR0Z5WkNJS0lDQmhZ
        Mk52ZFc1MFgzSmxjR3hwWTJGMGFXOXVYM1I1Y0dVZ1BTQWlURkpUSWdvS0lDQjBZV2R6SUQwZ2V3
        b2dJQ0FnWlc1MmFYSnZibTFsYm5RZ1BTQWljM1JoWjJsdVp5SUtJQ0I5Q24wS0NuSmxjMjkxY21O
        bElDSmhlblZ5WlhKdFgzTjBiM0poWjJWZlkyOXVkR0ZwYm1WeUlpQWlaWGhoYlhCc1pTSWdld29n
        SUc1aGJXVWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQTlJQ0oyYUdSeklnb2dJSE4wYjNKaFoyVmZZ
        V05qYjNWdWRGOXVZVzFsSUNBOUlHRjZkWEpsY20xZmMzUnZjbUZuWlY5aFkyTnZkVzUwTG1WNFlX
        MXdiR1V1Ym1GdFpRb2dJR052Ym5SaGFXNWxjbDloWTJObGMzTmZkSGx3WlNBOUlDSndjbWwyWVhS
        bElncDlDZz09
    import: !!binary |
        Q2dwVGRHOXlZV2RsSUVOdmJuUmhhVzVsY25NZ1kyRnVJR0psSUdsdGNHOXlkR1ZrSUhWemFXNW5J
        SFJvWlNCZ2NtVnpiM1Z5WTJVZ2FXUmdMQ0JsTG1jdUNnbz0=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmMzUnZjbUZuWlY5amIyNTBZV2x1WlhJdWFIUnRiQzV0WVhKclpHOTNiZz09
