azurerm_traffic_manager_profile:
    status: HOLD
    subcategory: Network
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_traffic_manager_profile'
    description: Manages a Traffic Manager Profile.
    arguments:
        name:
            description: The name of the custom header.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group in which to create the Traffic
                Manager profile.
            required: true
            policy: ''
            notes: ''
        profile_status:
            description: The status of the profile, can be set to either `Enabled`
                or `Disabled`. Defaults to `Enabled`.
            required: false
            policy: ''
            notes: ''
        traffic_routing_method:
            description: 'Specifies the algorithm used to route traffic, possible
                values are:'
            required: true
            policy: ''
            notes: ''
        dns_config:
            description: This block specifies the DNS configuration of the Profile,
                it supports the fields documented below.
            required: true
            policy: ''
            notes: ''
        monitor_config:
            description: This block specifies the Endpoint monitoring configuration
                for the Profile, it supports the fields documented below.
            required: true
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
        relative_name:
            description: The relative domain name, this is combined with the domain
                name used by Traffic Manager to form the FQDN which is exported as
                documented below. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        ttl:
            description: The TTL value of the Profile used by Local DNS resolvers
                and clients.
            required: true
            policy: ''
            notes: ''
        protocol:
            description: The protocol used by the monitoring checks, supported values
                are `HTTP`, `HTTPS` and `TCP`.
            required: true
            policy: ''
            notes: ''
        port:
            description: The port number used by the monitoring checks.
            required: true
            policy: ''
            notes: ''
        path:
            description: The path used by the monitoring checks. Required when `protocol`
                is set to `HTTP` or `HTTPS` - cannot be set when `protocol` is set
                to `TCP`.
            required: false
            policy: ''
            notes: ''
        expected_status_code_ranges:
            description: A list of status code ranges in the format of `100-101`.
            required: false
            policy: ''
            notes: ''
        custom_header:
            description: One or more `custom_header` blocks as defined below.
            required: false
            policy: ''
            notes: ''
        interval_in_seconds:
            description: 'The interval used to check the endpoint health from a Traffic
                Manager probing agent. You can specify two values here: `30` (normal
                probing'
            required: false
            policy: ''
            notes: ''
        timeout_in_seconds:
            description: The amount of time the Traffic Manager probing agent should
                wait before considering that check a failure when a health check probe
                is sent to the endpoint. If `interval_in_seconds` is set to `30`,
                then `timeout_in_seconds` can be between `5` and `10`. The default
                value is `10`. If `interval_in_seconds` is set to `10`, then valid
                values are between `5` and `9` and `timeout_in_seconds` is required.
            required: false
            policy: ''
            notes: ''
        tolerated_number_of_failures:
            description: The number of failures a Traffic Manager probing agent tolerates
                before marking that endpoint as unhealthy. Valid values are between
                `0` and `9`. The default value is `3`
            required: false
            policy: ''
            notes: ''
        value:
            description: The value of custom header. Applicable for Http and Https
                protocol.
            required: true
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the Traffic Manager Profile.
        fqdn:
            description: The FQDN of the created Profile.
    timeouts:
        create:
            description: Used when creating the Traffic Manager Profile.
            required: false
            timeout: 30
        update:
            description: Used when updating the Traffic Manager Profile.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Traffic Manager Profile.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Traffic Manager Profile.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKeVlXNWtiMjFmYVdRaUlDSnpaWEoyWlhJaUlIc0tJQ0JyWldWd1pYSnpJ
        RDBnZXdvZ0lDQWdZWHBwWDJsa0lEMGdNUW9nSUgwS0NpQWdZbmwwWlY5c1pXNW5kR2dnUFNBNENu
        MEtDbkpsYzI5MWNtTmxJQ0poZW5WeVpYSnRYM0psYzI5MWNtTmxYMmR5YjNWd0lpQWlaWGhoYlhC
        c1pTSWdld29nSUc1aGJXVWdJQ0FnSUQwZ0luUnlZV1ptYVdOdFlXNWhaMlZ5VUhKdlptbHNaU0lL
        SUNCc2IyTmhkR2x2YmlBOUlDSlhaWE4wSUZWVElncDlDZ3B5WlhOdmRYSmpaU0FpWVhwMWNtVnli
        VjkwY21GbVptbGpYMjFoYm1GblpYSmZjSEp2Wm1sc1pTSWdJbVY0WVcxd2JHVWlJSHNLSUNCdVlX
        MWxJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJRDBnY21GdVpHOXRYMmxrTG5ObGNuWmxjaTVvWlhn
        S0lDQnlaWE52ZFhKalpWOW5jbTkxY0Y5dVlXMWxJQ0FnSUQwZ1lYcDFjbVZ5YlY5eVpYTnZkWEpq
        WlY5bmNtOTFjQzVsZUdGdGNHeGxMbTVoYldVS0lDQjBjbUZtWm1salgzSnZkWFJwYm1kZmJXVjBh
        RzlrSUQwZ0lsZGxhV2RvZEdWa0lnb0tJQ0JrYm5OZlkyOXVabWxuSUhzS0lDQWdJSEpsYkdGMGFY
        WmxYMjVoYldVZ1BTQnlZVzVrYjIxZmFXUXVjMlZ5ZG1WeUxtaGxlQW9nSUNBZ2RIUnNJQ0FnSUNB
        Z0lDQWdJQ0E5SURFd01Bb2dJSDBLQ2lBZ2JXOXVhWFJ2Y2w5amIyNW1hV2NnZXdvZ0lDQWdjSEp2
        ZEc5amIyd2dJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0E5SUNKb2RIUndJZ29nSUNBZ2NHOXlk
        Q0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQTlJRGd3Q2lBZ0lDQndZWFJvSUNBZ0lD
        QWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJRDBnSWk4aUNpQWdJQ0JwYm5SbGNuWmhiRjlwYmw5
        elpXTnZibVJ6SUNBZ0lDQWdJQ0FnSUQwZ016QUtJQ0FnSUhScGJXVnZkWFJmYVc1ZmMyVmpiMjVr
        Y3lBZ0lDQWdJQ0FnSUNBZ1BTQTVDaUFnSUNCMGIyeGxjbUYwWldSZmJuVnRZbVZ5WDI5bVgyWmhh
        V3gxY21WeklEMGdNd29nSUgwS0NpQWdkR0ZuY3lBOUlIc0tJQ0FnSUdWdWRtbHliMjV0Wlc1MElE
        MGdJbEJ5YjJSMVkzUnBiMjRpQ2lBZ2ZRcDlDZz09
    import: !!binary |
        Q2dwVWNtRm1abWxqSUUxaGJtRm5aWElnVUhKdlptbHNaWE1nWTJGdUlHSmxJR2x0Y0c5eWRHVmtJ
        SFZ6YVc1bklIUm9aU0JnY21WemIzVnlZMlVnYVdSZ0xDQmxMbWN1Q2dvPQ==
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmRISmhabVpwWTE5dFlXNWhaMlZ5WDNCeWIyWnBiR1V1YUhSdGJDNXRZWEpyWkc5
        M2JnPT0=
