azurerm_route:
    status: HOLD
    subcategory: Network
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_route'
    description: Manages a Route within a Route Table.
    arguments:
        name:
            description: The name of the route. Changing this forces a new resource
                to be created.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group in which to create the route.
                Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        route_table_name:
            description: The name of the route table within which create the route.
                Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        address_prefix:
            description: The destination CIDR to which the route applies, such as
                `10.1.0.0/16`
            required: true
            policy: ''
            notes: ''
        next_hop_type:
            description: The type of Azure hop the packet should be sent to. Possible
                values are `VirtualNetworkGateway`, `VnetLocal`, `Internet`, `VirtualAppliance`
                and `None`
            required: true
            policy: ''
            notes: ''
        next_hop_in_ip_address:
            description: Contains the IP address packets should be forwarded to. Next
                hop values are only allowed in routes where the next hop type is `VirtualAppliance`.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The Route ID.
    timeouts:
        create:
            description: Used when creating the Route.
            required: false
            timeout: 30
        update:
            description: Used when updating the Route.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Route.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Route.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbUZqWTJWd2RHRnVZMlZVWlhOMFVtVnpiM1Z5WTJWSGNt
        OTFjREVpQ2lBZ2JHOWpZWFJwYjI0Z1BTQWlWMlZ6ZENCVlV5SUtmUW9LY21WemIzVnlZMlVnSW1G
        NmRYSmxjbTFmY205MWRHVmZkR0ZpYkdVaUlDSmxlR0Z0Y0d4bElpQjdDaUFnYm1GdFpTQWdJQ0Fn
        SUNBZ0lDQWdJQ0FnSUNBOUlDSmhZMk5sY0hSaGJtTmxWR1Z6ZEZKdmRYUmxWR0ZpYkdVeElnb2dJ
        R3h2WTJGMGFXOXVJQ0FnSUNBZ0lDQWdJQ0FnUFNCaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIz
        VndMbVY0WVcxd2JHVXViRzlqWVhScGIyNEtJQ0J5WlhOdmRYSmpaVjluY205MWNGOXVZVzFsSUQw
        Z1lYcDFjbVZ5YlY5eVpYTnZkWEpqWlY5bmNtOTFjQzVsZUdGdGNHeGxMbTVoYldVS2ZRb0tjbVZ6
        YjNWeVkyVWdJbUY2ZFhKbGNtMWZjbTkxZEdVaUlDSmxlR0Z0Y0d4bElpQjdDaUFnYm1GdFpTQWdJ
        Q0FnSUNBZ0lDQWdJQ0FnSUNBOUlDSmhZMk5sY0hSaGJtTmxWR1Z6ZEZKdmRYUmxNU0lLSUNCeVpY
        TnZkWEpqWlY5bmNtOTFjRjl1WVcxbElEMGdZWHAxY21WeWJWOXlaWE52ZFhKalpWOW5jbTkxY0M1
        bGVHRnRjR3hsTG01aGJXVUtJQ0J5YjNWMFpWOTBZV0pzWlY5dVlXMWxJQ0FnSUQwZ1lYcDFjbVZ5
        YlY5eWIzVjBaVjkwWVdKc1pTNWxlR0Z0Y0d4bExtNWhiV1VLSUNCaFpHUnlaWE56WDNCeVpXWnBl
        Q0FnSUNBZ0lEMGdJakV3TGpFdU1DNHdMekUySWdvZ0lHNWxlSFJmYUc5d1gzUjVjR1VnSUNBZ0lD
        QWdQU0FpZG01bGRHeHZZMkZzSWdwOUNnPT0=
    import: !!binary |
        Q2dwU2IzVjBaWE1nWTJGdUlHSmxJR2x0Y0c5eWRHVmtJSFZ6YVc1bklIUm9aU0JnY21WemIzVnlZ
        MlVnYVdSZ0xDQmxMbWN1Q2dvPQ==
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmNtOTFkR1V1YUhSdGJDNXRZWEpyWkc5M2JnPT0=
