azurerm_mariadb_configuration:
    status: ASSESS
    subcategory: Database
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_mariadb_configuration'
    description: Sets a MariaDB Configuration value on a MariaDB Server.
    arguments:
        name:
            description: Specifies the name of the MariaDB Configuration, which needs
                [to be a valid MariaDB configuration name](https://mariadb.com/kb/en/library/server-system-variables/).
                Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        server_name:
            description: Specifies the name of the MariaDB Server. Changing this forces
                a new resource to be created.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group in which the MariaDB Server
                exists. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        value:
            description: Specifies the value of the MariaDB Configuration. See the
                MariaDB documentation for valid values.
            required: true
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the MariaDB Configuration.
    timeouts:
        create:
            description: Used when creating the MariaDB Configuration.
            required: false
            timeout: 30
        update:
            description: Used when updating the MariaDB Configuration.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the MariaDB Configuration.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the MariaDB Configuration.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbUZ3YVMxeVp5MXdjbThpQ2lBZ2JHOWpZWFJwYjI0Z1BT
        QWlWMlZ6ZENCRmRYSnZjR1VpQ24wS0NuSmxjMjkxY21ObElDSmhlblZ5WlhKdFgyMWhjbWxoWkdK
        ZmMyVnlkbVZ5SWlBaVpYaGhiWEJzWlNJZ2V3b2dJRzVoYldVZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0Fn
        UFNBaWJXRnlhV0ZrWWkxelpYSjJaWEl0TVNJS0lDQnNiMk5oZEdsdmJpQWdJQ0FnSUNBZ0lDQWdJ
        RDBnWVhwMWNtVnliVjl5WlhOdmRYSmpaVjluY205MWNDNWxlR0Z0Y0d4bExteHZZMkYwYVc5dUNp
        QWdjbVZ6YjNWeVkyVmZaM0p2ZFhCZmJtRnRaU0E5SUdGNmRYSmxjbTFmY21WemIzVnlZMlZmWjNK
        dmRYQXVaWGhoYlhCc1pTNXVZVzFsQ2dvZ0lITnJkVjl1WVcxbElEMGdJa0pmUjJWdU5WOHlJZ29L
        SUNCemRHOXlZV2RsWDNCeWIyWnBiR1VnZXdvZ0lDQWdjM1J2Y21GblpWOXRZaUFnSUNBZ0lDQWdJ
        Q0FnSUQwZ05URXlNQW9nSUNBZ1ltRmphM1Z3WDNKbGRHVnVkR2x2Ymw5a1lYbHpJRDBnTndvZ0lD
        QWdaMlZ2WDNKbFpIVnVaR0Z1ZEY5aVlXTnJkWEFnSUQwZ0lrUnBjMkZpYkdWa0lnb2dJSDBLQ2lB
        Z1lXUnRhVzVwYzNSeVlYUnZjbDlzYjJkcGJpQWdJQ0FnSUNBZ0lDQTlJQ0p0WVhKcFlXUmlZV1J0
        YVc0aUNpQWdZV1J0YVc1cGMzUnlZWFJ2Y2w5c2IyZHBibDl3WVhOemQyOXlaQ0E5SUNKSVFGTm9N
        VU52VWpNaElnb2dJSFpsY25OcGIyNGdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnUFNBaU1U
        QXVNaUlLSUNCemMyeGZaVzVtYjNKalpXMWxiblFnSUNBZ0lDQWdJQ0FnSUNBZ0lEMGdJa1Z1WVdK
        c1pXUWlDbjBLQ25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDIxaGNtbGhaR0pmWTI5dVptbG5kWEpo
        ZEdsdmJpSWdJbVY0WVcxd2JHVWlJSHNLSUNCdVlXMWxJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lEMGdJ
        bWx1ZEdWeVlXTjBhWFpsWDNScGJXVnZkWFFpQ2lBZ2NtVnpiM1Z5WTJWZlozSnZkWEJmYm1GdFpT
        QTlJR0Y2ZFhKbGNtMWZjbVZ6YjNWeVkyVmZaM0p2ZFhBdVpYaGhiWEJzWlM1dVlXMWxDaUFnYzJW
        eWRtVnlYMjVoYldVZ0lDQWdJQ0FnSUNBOUlHRjZkWEpsY20xZmJXRnlhV0ZrWWw5elpYSjJaWEl1
        WlhoaGJYQnNaUzV1WVcxbENpQWdkbUZzZFdVZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0E5SUNJMk1EQWlD
        bjBL
    import: !!binary |
        Q2dwTllYSnBZVVJDSUVOdmJtWnBaM1Z5WVhScGIyNXpJR05oYmlCaVpTQnBiWEJ2Y25SbFpDQjFj
        Mmx1WnlCMGFHVWdZSEpsYzI5MWNtTmxJR2xrWUN3Z1pTNW5MZ29L
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmJXRnlhV0ZrWWw5amIyNW1hV2QxY21GMGFXOXVMbWgwYld3dWJXRnlhMlJ2ZDI0
        PQ==
