azurerm_private_dns_zone:
    status: HOLD
    subcategory: Private DNS
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_private_dns_zone'
    description: Manages a Private DNS Zone.
    arguments:
        name:
            description: The name of the Private DNS Zone. Must be a valid domain
                name.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: Specifies the resource group where the resource exists. Changing
                this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The Prviate DNS Zone ID.
        number_of_record_sets:
            description: The current number of record sets in this Private DNS zone.
        max_number_of_record_sets:
            description: The maximum number of record sets that can be created in
                this Private DNS zone.
        max_number_of_virtual_network_links:
            description: The maximum number of virtual networks that can be linked
                to this Private DNS zone.
        max_number_of_virtual_network_links_with_registration:
            description: The maximum number of virtual networks that can be linked
                to this Private DNS zone with registration enabled.
    timeouts:
        create:
            description: Used when creating the Private DNS Zone.
            required: false
            timeout: 30
        update:
            description: Used when updating the Private DNS Zone.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Private DNS Zone.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Private DNS Zone.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbUZqWTJWd2RHRnVZMlZVWlhOMFVtVnpiM1Z5WTJWSGNt
        OTFjREVpQ2lBZ2JHOWpZWFJwYjI0Z1BTQWlWMlZ6ZENCVlV5SUtmUW9LY21WemIzVnlZMlVnSW1G
        NmRYSmxjbTFmY0hKcGRtRjBaVjlrYm5OZmVtOXVaU0lnSW1WNFlXMXdiR1VpSUhzS0lDQnVZVzFs
        SUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJRDBnSW0xNVpHOXRZV2x1TG1OdmJTSUtJQ0J5WlhOdmRYSmpa
        VjluY205MWNGOXVZVzFsSUQwZ1lYcDFjbVZ5YlY5eVpYTnZkWEpqWlY5bmNtOTFjQzVsZUdGdGNH
        eGxMbTVoYldVS2ZRbz0=
    import: !!binary |
        Q2dwUWNtbDJZWFJsSUVST1V5QmFiMjVsY3lCallXNGdZbVVnYVcxd2IzSjBaV1FnZFhOcGJtY2dk
        R2hsSUdCeVpYTnZkWEpqWlNCcFpHQXNJR1V1Wnk0S0NnPT0=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmNISnBkbUYwWlY5a2JuTmZlbTl1WlM1b2RHMXNMbTFoY210a2IzZHU=
