azurerm_availability_set:
    status: ASSESS
    subcategory: Compute
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_availability_set'
    description: Manages an Availability Set for Virtual Machines.
    arguments:
        name:
            description: Specifies the name of the availability set. Changing this
                forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group in which to create the availability
                set. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        location:
            description: Specifies the supported Azure location where the resource
                exists. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        platform_update_domain_count:
            description: Specifies the number of update domains that are used. Defaults
                to `5`.
            required: false
            policy: ''
            notes: ''
        platform_fault_domain_count:
            description: Specifies the number of fault domains that are used. Defaults
                to `3`.
            required: false
            policy: ''
            notes: ''
        proximity_placement_group_id:
            description: The ID of the Proximity Placement Group to which this Virtual
                Machine should be assigned. Changing this forces a new resource to
                be created
            required: false
            policy: ''
            notes: ''
        managed:
            description: Specifies whether the availability set is managed or not.
                Possible values are `true` (to specify aligned
            required: false
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the Availability Set.
    timeouts:
        create:
            description: Used when creating the Availability Set.
            required: false
            timeout: 30
        update:
            description: Used when updating the Availability Set.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Availability Set.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Availability Set.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbVY0WVcxd2JHVXRjbVZ6YjNWeVkyVnpJZ29nSUd4dlky
        RjBhVzl1SUQwZ0lsZGxjM1FnUlhWeWIzQmxJZ3A5Q2dweVpYTnZkWEpqWlNBaVlYcDFjbVZ5YlY5
        aGRtRnBiR0ZpYVd4cGRIbGZjMlYwSWlBaVpYaGhiWEJzWlNJZ2V3b2dJRzVoYldVZ0lDQWdJQ0Fn
        SUNBZ0lDQWdJQ0FnUFNBaVpYaGhiWEJzWlMxaGMyVjBJZ29nSUd4dlkyRjBhVzl1SUNBZ0lDQWdJ
        Q0FnSUNBZ1BTQmhlblZ5WlhKdFgzSmxjMjkxY21ObFgyZHliM1Z3TG1WNFlXMXdiR1V1Ykc5allY
        UnBiMjRLSUNCeVpYTnZkWEpqWlY5bmNtOTFjRjl1WVcxbElEMGdZWHAxY21WeWJWOXlaWE52ZFhK
        alpWOW5jbTkxY0M1bGVHRnRjR3hsTG01aGJXVUtDaUFnZEdGbmN5QTlJSHNLSUNBZ0lHVnVkbWx5
        YjI1dFpXNTBJRDBnSWxCeWIyUjFZM1JwYjI0aUNpQWdmUXA5Q2c9PQ==
    import: !!binary |
        Q2dwQmRtRnBiR0ZpYVd4cGRIa2dVMlYwY3lCallXNGdZbVVnYVcxd2IzSjBaV1FnZFhOcGJtY2dk
        R2hsSUdCeVpYTnZkWEpqWlNCcFpHQXNJR1V1Wnk0S0NnPT0=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdllYWmhhV3hoWW1sc2FYUjVYM05sZEM1b2RHMXNMbTFoY210a2IzZHU=
