azurerm_network_security_rule:
    status: ASSESS
    subcategory: Network
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_network_security_rule'
    description: Manages a Network Security Rule.
    arguments:
        name:
            description: The name of the security rule. This needs to be unique across
                all Rules in the Network Security Group. Changing this forces a new
                resource to be created.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group in which to create the Network
                Security Rule. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        network_security_group_name:
            description: The name of the Network Security Group that we want to attach
                the rule to. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        description:
            description: A description for this rule. Restricted to 140 characters.
            required: false
            policy: ''
            notes: ''
        protocol:
            description: Network protocol this rule applies to. Possible values include
                `Tcp`, `Udp`, `Icmp`, or `*` (which matches all).
            required: true
            policy: ''
            notes: ''
        source_port_range:
            description: Source Port or Range. Integer or range between `0` and `65535`
                or `*` to match any. This is required if `source_port_ranges` is not
                specified.
            required: false
            policy: ''
            notes: ''
        source_port_ranges:
            description: List of source ports or port ranges. This is required if
                `source_port_range` is not specified.
            required: false
            policy: ''
            notes: ''
        destination_port_range:
            description: Destination Port or Range. Integer or range between `0` and
                `65535` or `*` to match any. This is required if `destination_port_ranges`
                is not specified.
            required: false
            policy: ''
            notes: ''
        destination_port_ranges:
            description: List of destination ports or port ranges. This is required
                if `destination_port_range` is not specified.
            required: false
            policy: ''
            notes: ''
        source_address_prefix:
            description: "CIDR or source IP range or * to match any IP. Tags such\
                \ as \u2018VirtualNetwork\u2019, \u2018AzureLoadBalancer\u2019 and\
                \ \u2018Internet\u2019 can also be used. This is required if `source_address_prefixes`\
                \ is not specified."
            required: false
            policy: ''
            notes: ''
        source_address_prefixes:
            description: List of source address prefixes. Tags may not be used. This
                is required if `source_address_prefix` is not specified.
            required: false
            policy: ''
            notes: ''
        source_application_security_group_ids:
            description: A List of source Application Security Group ID's
            required: false
            policy: ''
            notes: ''
        destination_address_prefix:
            description: "CIDR or destination IP range or * to match any IP. Tags\
                \ such as \u2018VirtualNetwork\u2019, \u2018AzureLoadBalancer\u2019\
                \ and \u2018Internet\u2019 can also be used. This is required if `destination_address_prefixes`\
                \ is not specified."
            required: false
            policy: ''
            notes: ''
        destination_address_prefixes:
            description: List of destination address prefixes. Tags may not be used.
                This is required if `destination_address_prefix` is not specified.
            required: false
            policy: ''
            notes: ''
        destination_application_security_group_ids:
            description: A List of destination Application Security Group ID's
            required: false
            policy: ''
            notes: ''
        access:
            description: Specifies whether network traffic is allowed or denied. Possible
                values are `Allow` and `Deny`.
            required: true
            policy: ''
            notes: ''
        priority:
            description: Specifies the priority of the rule. The value can be between
                100 and 4096. The priority number must be unique for each rule in
                the collection. The lower the priority number, the higher the priority
                of the rule.
            required: true
            policy: ''
            notes: ''
        direction:
            description: The direction specifies if rule will be evaluated on incoming
                or outgoing traffic. Possible values are `Inbound` and `Outbound`.
            required: true
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the Network Security Rule.
    timeouts:
        create:
            description: Used when creating the Network Security Rule.
            required: false
            timeout: 30
        update:
            description: Used when updating the Network Security Rule.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Network Security Rule.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Network Security Rule.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbUZqWTJWd2RHRnVZMlZVWlhOMFVtVnpiM1Z5WTJWSGNt
        OTFjREVpQ2lBZ2JHOWpZWFJwYjI0Z1BTQWlWMlZ6ZENCVlV5SUtmUW9LY21WemIzVnlZMlVnSW1G
        NmRYSmxjbTFmYm1WMGQyOXlhMTl6WldOMWNtbDBlVjluY205MWNDSWdJbVY0WVcxd2JHVWlJSHNL
        SUNCdVlXMWxJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lEMGdJbUZqWTJWd2RHRnVZMlZVWlhOMFUyVmpk
        WEpwZEhsSGNtOTFjREVpQ2lBZ2JHOWpZWFJwYjI0Z0lDQWdJQ0FnSUNBZ0lDQTlJR0Y2ZFhKbGNt
        MWZjbVZ6YjNWeVkyVmZaM0p2ZFhBdVpYaGhiWEJzWlM1c2IyTmhkR2x2YmdvZ0lISmxjMjkxY21O
        bFgyZHliM1Z3WDI1aGJXVWdQU0JoZW5WeVpYSnRYM0psYzI5MWNtTmxYMmR5YjNWd0xtVjRZVzF3
        YkdVdWJtRnRaUXA5Q2dweVpYTnZkWEpqWlNBaVlYcDFjbVZ5YlY5dVpYUjNiM0pyWDNObFkzVnlh
        WFI1WDNKMWJHVWlJQ0psZUdGdGNHeGxJaUI3Q2lBZ2JtRnRaU0FnSUNBZ0lDQWdJQ0FnSUNBZ0lD
        QWdJQ0FnSUNBZ0lEMGdJblJsYzNReE1qTWlDaUFnY0hKcGIzSnBkSGtnSUNBZ0lDQWdJQ0FnSUNB
        Z0lDQWdJQ0FnSUQwZ01UQXdDaUFnWkdseVpXTjBhVzl1SUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0Fn
        SUQwZ0lrOTFkR0p2ZFc1a0lnb2dJR0ZqWTJWemN5QWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJ
        Q0E5SUNKQmJHeHZkeUlLSUNCd2NtOTBiMk52YkNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ1BT
        QWlWR053SWdvZ0lITnZkWEpqWlY5d2IzSjBYM0poYm1kbElDQWdJQ0FnSUNBZ0lDQTlJQ0lxSWdv
        Z0lHUmxjM1JwYm1GMGFXOXVYM0J2Y25SZmNtRnVaMlVnSUNBZ0lDQTlJQ0lxSWdvZ0lITnZkWEpq
        WlY5aFpHUnlaWE56WDNCeVpXWnBlQ0FnSUNBZ0lDQTlJQ0lxSWdvZ0lHUmxjM1JwYm1GMGFXOXVY
        MkZrWkhKbGMzTmZjSEpsWm1sNElDQTlJQ0lxSWdvZ0lISmxjMjkxY21ObFgyZHliM1Z3WDI1aGJX
        VWdJQ0FnSUNBZ0lDQTlJR0Y2ZFhKbGNtMWZjbVZ6YjNWeVkyVmZaM0p2ZFhBdVpYaGhiWEJzWlM1
        dVlXMWxDaUFnYm1WMGQyOXlhMTl6WldOMWNtbDBlVjluY205MWNGOXVZVzFsSUQwZ1lYcDFjbVZ5
        YlY5dVpYUjNiM0pyWDNObFkzVnlhWFI1WDJkeWIzVndMbVY0WVcxd2JHVXVibUZ0WlFwOUNnPT0=
    import: !!binary |
        Q2dwT1pYUjNiM0pySUZObFkzVnlhWFI1SUZKMWJHVnpJR05oYmlCaVpTQnBiWEJ2Y25SbFpDQjFj
        Mmx1WnlCMGFHVWdZSEpsYzI5MWNtTmxJR2xrWUN3Z1pTNW5MZ29L
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmJtVjBkMjl5YTE5elpXTjFjbWwwZVY5eWRXeGxMbWgwYld3dWJXRnlhMlJ2ZDI0
        PQ==
