azurerm_shared_image_gallery:
    status: ASSESS
    subcategory: Compute
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_shared_image_gallery'
    description: Manages a Shared Image Gallery.
    arguments:
        name:
            description: Specifies the name of the Shared Image Gallery. Changing
                this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group in which to create the Shared
                Image Gallery. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        location:
            description: Specifies the supported Azure location where the resource
                exists. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        description:
            description: A description for this Shared Image Gallery.
            required: false
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the Shared Image Gallery.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the Shared Image Gallery.
        unique_name:
            description: The Unique Name for this Shared Image Gallery.
    timeouts:
        create:
            description: Used when creating the Shared Image Gallery.
            required: false
            timeout: 30
        update:
            description: Used when updating the Shared Image Gallery.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Shared Image Gallery.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Shared Image Gallery.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbVY0WVcxd2JHVXRjbVZ6YjNWeVkyVnpJZ29nSUd4dlky
        RjBhVzl1SUQwZ0lsZGxjM1FnUlhWeWIzQmxJZ3A5Q2dweVpYTnZkWEpqWlNBaVlYcDFjbVZ5YlY5
        emFHRnlaV1JmYVcxaFoyVmZaMkZzYkdWeWVTSWdJbVY0WVcxd2JHVWlJSHNLSUNCdVlXMWxJQ0Fn
        SUNBZ0lDQWdJQ0FnSUNBZ0lEMGdJbVY0WVcxd2JHVmZhVzFoWjJWZloyRnNiR1Z5ZVNJS0lDQnla
        WE52ZFhKalpWOW5jbTkxY0Y5dVlXMWxJRDBnWVhwMWNtVnliVjl5WlhOdmRYSmpaVjluY205MWND
        NWxlR0Z0Y0d4bExtNWhiV1VLSUNCc2IyTmhkR2x2YmlBZ0lDQWdJQ0FnSUNBZ0lEMGdZWHAxY21W
        eWJWOXlaWE52ZFhKalpWOW5jbTkxY0M1bGVHRnRjR3hsTG14dlkyRjBhVzl1Q2lBZ1pHVnpZM0pw
        Y0hScGIyNGdJQ0FnSUNBZ0lDQTlJQ0pUYUdGeVpXUWdhVzFoWjJWeklHRnVaQ0IwYUdsdVozTXVJ
        Z29LSUNCMFlXZHpJRDBnZXdvZ0lDQWdTR1ZzYkc4Z1BTQWlWR2hsY21VaUNpQWdJQ0JYYjNKc1pD
        QTlJQ0pGZUdGdGNHeGxJZ29nSUgwS2ZRbz0=
    import: !!binary |
        Q2dwVGFHRnlaV1FnU1cxaFoyVWdSMkZzYkdWeWFXVnpJR05oYmlCaVpTQnBiWEJ2Y25SbFpDQjFj
        Mmx1WnlCMGFHVWdZSEpsYzI5MWNtTmxJR2xrWUN3Z1pTNW5MZ29L
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmMyaGhjbVZrWDJsdFlXZGxYMmRoYkd4bGNua3VhSFJ0YkM1dFlYSnJaRzkzYmc9
        PQ==
