azurerm_dev_test_windows_virtual_machine:
    status: ASSESS
    subcategory: Dev Test
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_dev_test_windows_virtual_machine'
    description: Manages a Windows Virtual Machine within a Dev Test Lab.
    arguments:
        name:
            description: Specifies the name of the Dev Test Machine. Changing this
                forces a new resource to be created.
            required: false
            policy: ''
            notes:
            - '-> '
            - ' The validation requirements for the Name change based on the `os_type`
                used in this Virtual Machine. For a Linux VM the name must be between
                1-62 characters, and for a Windows VM the name must be between 1-15
                characters. It must begin and end with a letter or number, and cannot
                be all numbers.'
        lab_name:
            description: Specifies the name of the Dev Test Lab in which the Virtual
                Machine should be created. Changing this forces a new resource to
                be created.
            required: false
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group in which the Dev Test Lab
                resource exists. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        location:
            description: Specifies the supported Azure location where the Dev Test
                Lab exists. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        gallery_image_reference:
            description: A `gallery_image_reference` block as defined below.
            required: false
            policy: ''
            notes: ''
        lab_subnet_name:
            description: The name of a Subnet within the Dev Test Virtual Network
                where this machine should exist. Changing this forces a new resource
                to be created.
            required: false
            policy: ''
            notes: ''
        lab_virtual_network_id:
            description: The ID of the Dev Test Virtual Network where this Virtual
                Machine should be created. Changing this forces a new resource to
                be created.
            required: false
            policy: ''
            notes: ''
        password:
            description: The Password associated with the `username` used to login
                to this Virtual Machine. Changing this forces a new resource to be
                created.
            required: false
            policy: ''
            notes: ''
        size:
            description: The Machine Size to use for this Virtual Machine, such as
                `Standard_F2`. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        storage_type:
            description: The type of Storage to use on this Virtual Machine. Possible
                values are `Standard` and `Premium`.
            required: false
            policy: ''
            notes: ''
        username:
            description: The Username associated with the local administrator on this
                Virtual Machine. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        allow_claim:
            description: Can this Virtual Machine be claimed by users? Defaults to
                `true`.
            required: false
            policy: ''
            notes: ''
        disallow_public_ip_address:
            description: Should the Virtual Machine be created without a Public IP
                Address? Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        inbound_nat_rule:
            description: One or more `inbound_nat_rule` blocks as defined below. Changing
                this forces a new resource to be created.
            required: false
            policy: ''
            notes:
            - '-> '
            - ' If any `inbound_nat_rule` blocks are specified then `disallow_public_ip_address`
                must be set to `true`.'
        notes:
            description: Any notes about the Virtual Machine.
            required: false
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
        offer:
            description: The Offer of the Gallery Image. Changing this forces a new
                resource to be created.
            required: false
            policy: ''
            notes: ''
        publisher:
            description: The Publisher of the Gallery Image. Changing this forces
                a new resource to be created.
            required: false
            policy: ''
            notes: ''
        sku:
            description: The SKU of the Gallery Image. Changing this forces a new
                resource to be created.
            required: false
            policy: ''
            notes: ''
        version:
            description: The Version of the Gallery Image. Changing this forces a
                new resource to be created.
            required: false
            policy: ''
            notes: ''
        protocol:
            description: The Protocol used for this NAT Rule. Possible values are
                `Tcp` and `Udp`. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        backend_port:
            description: The Backend Port associated with this NAT Rule. Changing
                this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the Virtual Machine.
        fqdn:
            description: The FQDN of the Virtual Machine.
        inbound_nat_rule:
            description: One or more `inbound_nat_rule` blocks as defined below.
        unique_identifier:
            description: The unique immutable identifier of the Virtual Machine.
        frontend_port:
            description: The frontend port associated with this Inbound NAT Rule.
    timeouts:
        create:
            description: Used when creating the DevTest Windows Virtual Machine.
            required: false
            timeout: 30
        update:
            description: Used when updating the DevTest Windows Virtual Machine.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the DevTest Windows Virtual Machine.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the DevTest Windows Virtual Machine.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbVY0WVcxd2JHVXRjbVZ6YjNWeVkyVnpJZ29nSUd4dlky
        RjBhVzl1SUQwZ0lsZGxjM1FnVlZNaUNuMEtDbkpsYzI5MWNtTmxJQ0poZW5WeVpYSnRYMlJsZGw5
        MFpYTjBYMnhoWWlJZ0ltVjRZVzF3YkdVaUlIc0tJQ0J1WVcxbElDQWdJQ0FnSUNBZ0lDQWdJQ0Fn
        SUQwZ0ltVjRZVzF3YkdVdFpHVjJkR1Z6ZEd4aFlpSUtJQ0JzYjJOaGRHbHZiaUFnSUNBZ0lDQWdJ
        Q0FnSUQwZ1lYcDFjbVZ5YlY5eVpYTnZkWEpqWlY5bmNtOTFjQzVsZUdGdGNHeGxMbXh2WTJGMGFX
        OXVDaUFnY21WemIzVnlZMlZmWjNKdmRYQmZibUZ0WlNBOUlHRjZkWEpsY20xZmNtVnpiM1Z5WTJW
        ZlozSnZkWEF1WlhoaGJYQnNaUzV1WVcxbENnb2dJSFJoWjNNZ1BTQjdDaUFnSUNBaVUzbGtibVY1
        SWlBOUlDSkJkWE4wY21Gc2FXRWlDaUFnZlFwOUNncHlaWE52ZFhKalpTQWlZWHAxY21WeWJWOWta
        WFpmZEdWemRGOTJhWEowZFdGc1gyNWxkSGR2Y21zaUlDSmxlR0Z0Y0d4bElpQjdDaUFnYm1GdFpT
        QWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBOUlDSmxlR0Z0Y0d4bExXNWxkSGR2Y21zaUNpQWdiR0ZpWDI1
        aGJXVWdJQ0FnSUNBZ0lDQWdJQ0E5SUdGNmRYSmxjbTFmWkdWMlgzUmxjM1JmYkdGaUxtVjRZVzF3
        YkdVdWJtRnRaUW9nSUhKbGMyOTFjbU5sWDJkeWIzVndYMjVoYldVZ1BTQmhlblZ5WlhKdFgzSmxj
        MjkxY21ObFgyZHliM1Z3TG1WNFlXMXdiR1V1Ym1GdFpRb0tJQ0J6ZFdKdVpYUWdld29nSUNBZ2RY
        TmxYM0IxWW14cFkxOXBjRjloWkdSeVpYTnpJQ0FnSUNBZ0lDQWdJQ0E5SUNKQmJHeHZkeUlLSUNB
        Z0lIVnpaVjlwYmw5MmFYSjBkV0ZzWDIxaFkyaHBibVZmWTNKbFlYUnBiMjRnUFNBaVFXeHNiM2Np
        Q2lBZ2ZRcDlDZ3B5WlhOdmRYSmpaU0FpWVhwMWNtVnliVjlrWlhaZmRHVnpkRjkzYVc1a2IzZHpY
        M1pwY25SMVlXeGZiV0ZqYUdsdVpTSWdJbVY0WVcxd2JHVWlJSHNLSUNCdVlXMWxJQ0FnSUNBZ0lD
        QWdJQ0FnSUNBZ0lDQWdJRDBnSW1WNFlXMXdiR1V0ZG0wd015SUtJQ0JzWVdKZmJtRnRaU0FnSUNB
        Z0lDQWdJQ0FnSUNBZ0lEMGdZWHAxY21WeWJWOWtaWFpmZEdWemRGOXNZV0l1WlhoaGJYQnNaUzV1
        WVcxbENpQWdjbVZ6YjNWeVkyVmZaM0p2ZFhCZmJtRnRaU0FnSUNBOUlHRjZkWEpsY20xZmNtVnpi
        M1Z5WTJWZlozSnZkWEF1WlhoaGJYQnNaUzV1WVcxbENpQWdiRzlqWVhScGIyNGdJQ0FnSUNBZ0lD
        QWdJQ0FnSUNBOUlHRjZkWEpsY20xZmNtVnpiM1Z5WTJWZlozSnZkWEF1WlhoaGJYQnNaUzVzYjJO
        aGRHbHZiZ29nSUhOcGVtVWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdQU0FpVTNSaGJtUmhjbVJm
        UkZNeUlnb2dJSFZ6WlhKdVlXMWxJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ1BTQWlaWGhoYlhCc1pYVnpa
        WEk1T1NJS0lDQndZWE56ZDI5eVpDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUQwZ0lsQmhKSGN3Y21ReE1q
        TTBJU0lLSUNCc1lXSmZkbWx5ZEhWaGJGOXVaWFIzYjNKclgybGtJRDBnWVhwMWNtVnliVjlrWlha
        ZmRHVnpkRjkyYVhKMGRXRnNYMjVsZEhkdmNtc3VaWGhoYlhCc1pTNXBaQW9nSUd4aFlsOXpkV0p1
        WlhSZmJtRnRaU0FnSUNBZ0lDQWdQU0JoZW5WeVpYSnRYMlJsZGw5MFpYTjBYM1pwY25SMVlXeGZi
        bVYwZDI5eWF5NWxlR0Z0Y0d4bExuTjFZbTVsZEZzd1hTNXVZVzFsQ2lBZ2MzUnZjbUZuWlY5MGVY
        QmxJQ0FnSUNBZ0lDQWdJQ0E5SUNKUWNtVnRhWFZ0SWdvZ0lHNXZkR1Z6SUNBZ0lDQWdJQ0FnSUNB
        Z0lDQWdJQ0FnUFNBaVUyOXRaU0J1YjNSbGN5QmhZbTkxZENCMGFHbHpJRlpwY25SMVlXd2dUV0Zq
        YUdsdVpTNGlDZ29nSUdkaGJHeGxjbmxmYVcxaFoyVmZjbVZtWlhKbGJtTmxJSHNLSUNBZ0lHOW1a
        bVZ5SUNBZ0lDQTlJQ0pYYVc1a2IzZHpVMlZ5ZG1WeUlnb2dJQ0FnY0hWaWJHbHphR1Z5SUQwZ0lr
        MXBZM0p2YzI5bWRGZHBibVJ2ZDNOVFpYSjJaWElpQ2lBZ0lDQnphM1VnSUNBZ0lDQWdQU0FpTWpB
        eE9TMUVZWFJoWTJWdWRHVnlJZ29nSUNBZ2RtVnljMmx2YmlBZ0lEMGdJbXhoZEdWemRDSUtJQ0I5
        Q24wSw==
    import: !!binary |
        Q2dwRVpYWlVaWE4wSUZkcGJtUnZkM01nVm1seWRIVmhiQ0JOWVdOb2FXNWxjeUJqWVc0Z1ltVWdh
        VzF3YjNKMFpXUWdkWE5wYm1jZ2RHaGxJR0J5WlhOdmRYSmpaU0JwWkdBc0lHVXVaeTRLQ2c9PQ==
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdlpHVjJYM1JsYzNSZmQybHVaRzkzYzE5MmFYSjBkV0ZzWDIxaFkyaHBibVV1YUhS
        dGJDNXRZWEpyWkc5M2JnPT0=
