azurerm_api_management_backend:
    status: HOLD
    subcategory: API Management
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_api_management_backend'
    description: Manages a backend within an API Management Service.
    arguments:
        name:
            description: The common name of the certificate.
            required: true
            policy: ''
            notes: ''
        api_management_name:
            description: The Name of the API Management Service where this backend
                should be created. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: The Name of the Resource Group where the API Management Service
                exists. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        protocol:
            description: The protocol used by the backend host. Possible values are
                `http` or `soap`.
            required: true
            policy: ''
            notes: ''
        url:
            description: The URL of the proxy server.
            required: false
            policy: ''
            notes: ''
        credentials:
            description: A `credentials` block as documented below.
            required: false
            policy: ''
            notes: ''
        description:
            description: The description of the backend.
            required: false
            policy: ''
            notes: ''
        proxy:
            description: A `proxy` block as documented below.
            required: false
            policy: ''
            notes: ''
        resource_id:
            description: The management URI of the backend host in an external system.
                This URI can be the ARM Resource ID of Logic Apps, Function Apps or
                API Apps, or the management endpoint of a Service Fabric cluster.
            required: false
            policy: ''
            notes: ''
        service_fabric_cluster:
            description: A `service_fabric_cluster` block as documented below.
            required: false
            policy: ''
            notes: ''
        title:
            description: The title of the backend.
            required: false
            policy: ''
            notes: ''
        tls:
            description: A `tls` block as documented below.
            required: false
            policy: ''
            notes: ''
        authorization:
            description: An `authorization` block as defined below.
            required: false
            policy: ''
            notes: ''
        certificate:
            description: A list of client certificate thumbprints to present to the
                backend host. The certificates must exist within the API Management
                Service.
            required: false
            policy: ''
            notes: ''
        header:
            description: A mapping of header parameters to pass to the backend host.
                The keys are the header names and the values are a comma separated
                string of header values. This is converted to a list before being
                passed to the API.
            required: false
            policy: ''
            notes: ''
        query:
            description: A mapping of query parameters to pass to the backend host.
                The keys are the query names and the values are a comma separated
                string of query values. This is converted to a list before being passed
                to the API.
            required: false
            policy: ''
            notes: ''
        parameter:
            description: The authentication Parameter value.
            required: false
            policy: ''
            notes: ''
        scheme:
            description: The authentication Scheme name.
            required: false
            policy: ''
            notes: ''
        password:
            description: The password to connect to the proxy server.
            required: false
            policy: ''
            notes: ''
        username:
            description: The username to connect to the proxy server.
            required: false
            policy: ''
            notes: ''
        client_certificate_thumbprint:
            description: The client certificate thumbprint for the management endpoint.
            required: true
            policy: ''
            notes: ''
        management_endpoints:
            description: A list of cluster management endpoints.
            required: true
            policy: ''
            notes: ''
        max_partition_resolution_retries:
            description: The maximum number of retries when attempting resolve the
                partition.
            required: true
            policy: ''
            notes: ''
        server_certificate_thumbprints:
            description: A list of thumbprints of the server certificates of the Service
                Fabric cluster.
            required: false
            policy: ''
            notes: ''
        server_x509_name:
            description: One or more `server_x509_name` blocks as documented below.
            required: false
            policy: ''
            notes: ''
        issuer_certificate_thumbprint:
            description: The thumbprint for the issuer of the certificate.
            required: true
            policy: ''
            notes: ''
        validate_certificate_chain:
            description: Flag indicating whether SSL certificate chain validation
                should be done when using self-signed certificates for the backend
                host.
            required: false
            policy: ''
            notes: ''
        validate_certificate_name:
            description: Flag indicating whether SSL certificate name validation should
                be done when using self-signed certificates for the backend host.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the API Management API.
    timeouts:
        create:
            description: Used when creating the API Management Backend.
            required: false
            timeout: 30
        update:
            description: Used when updating the API Management Backend.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the API Management Backend.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the API Management Backend.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbVY0WVcxd2JHVXRjbVZ6YjNWeVkyVnpJZ29nSUd4dlky
        RjBhVzl1SUQwZ0lsZGxjM1FnUlhWeWIzQmxJZ3A5Q2dweVpYTnZkWEpqWlNBaVlYcDFjbVZ5YlY5
        aGNHbGZiV0Z1WVdkbGJXVnVkQ0lnSW1WNFlXMXdiR1VpSUhzS0lDQnVZVzFsSUNBZ0lDQWdJQ0Fn
        SUNBZ0lDQWdJRDBnSW1WNFlXMXdiR1V0WVhCcGJTSUtJQ0JzYjJOaGRHbHZiaUFnSUNBZ0lDQWdJ
        Q0FnSUQwZ1lYcDFjbVZ5YlY5eVpYTnZkWEpqWlY5bmNtOTFjQzVsZUdGdGNHeGxMbXh2WTJGMGFX
        OXVDaUFnY21WemIzVnlZMlZmWjNKdmRYQmZibUZ0WlNBOUlHRjZkWEpsY20xZmNtVnpiM1Z5WTJW
        ZlozSnZkWEF1WlhoaGJYQnNaUzV1WVcxbENpQWdjSFZpYkdsemFHVnlYMjVoYldVZ0lDQWdJQ0E5
        SUNKTmVTQkRiMjF3WVc1NUlnb2dJSEIxWW14cGMyaGxjbDlsYldGcGJDQWdJQ0FnUFNBaVkyOXRj
        R0Z1ZVVCMFpYSnlZV1p2Y20wdWFXOGlDZ29nSUhOcmRWOXVZVzFsSUQwZ0lrUmxkbVZzYjNCbGNs
        OHhJZ3A5Q2dweVpYTnZkWEpqWlNBaVlYcDFjbVZ5YlY5aGNHbGZiV0Z1WVdkbGJXVnVkRjlpWVdO
        clpXNWtJaUFpWlhoaGJYQnNaU0lnZXdvZ0lHNWhiV1VnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdQU0Fp
        WlhoaGJYQnNaUzFpWVdOclpXNWtJZ29nSUhKbGMyOTFjbU5sWDJkeWIzVndYMjVoYldVZ1BTQmhl
        blZ5WlhKdFgzSmxjMjkxY21ObFgyZHliM1Z3TG1WNFlXMXdiR1V1Ym1GdFpRb2dJR0Z3YVY5dFlX
        NWhaMlZ0Wlc1MFgyNWhiV1VnUFNCaGVuVnlaWEp0WDJGd2FWOXRZVzVoWjJWdFpXNTBMbVY0WVcx
        d2JHVXVibUZ0WlFvZ0lIQnliM1J2WTI5c0lDQWdJQ0FnSUNBZ0lDQWdQU0FpYUhSMGNDSUtJQ0Ix
        Y213Z0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUQwZ0ltaDBkSEJ6T2k4dlltRmphMlZ1WkNJS2ZRbz0=
    import: !!binary |
        Q2dwQlVFa2dUV0Z1WVdkbGJXVnVkQ0JpWVdOclpXNWtjeUJqWVc0Z1ltVWdhVzF3YjNKMFpXUWdk
        WE5wYm1jZ2RHaGxJR0J5WlhOdmRYSmpaU0JwWkdBc0lHVXVaeTRLQ2c9PQ==
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdllYQnBYMjFoYm1GblpXMWxiblJmWW1GamEyVnVaQzVvZEcxc0xtMWhjbXRrYjNk
        dQ==
