azurerm_private_dns_srv_record:
    status: HOLD
    subcategory: Private DNS
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_private_dns_srv_record'
    description: Manages a Private DNS SRV Record.
    arguments:
        name:
            description: The name of the DNS SRV Record. Changing this forces a new
                resource to be created.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: Specifies the resource group where the resource exists. Changing
                this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        zone_name:
            description: Specifies the Private DNS Zone where the resource exists.
                Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        record:
            description: One or more `record` blocks as defined below.
            required: true
            policy: ''
            notes: ''
        'ttl ':
            description: The Time To Live (TTL
            required: true
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
        priority:
            description: The priority of the SRV record.
            required: true
            policy: ''
            notes: ''
        weight:
            description: The Weight of the SRV record.
            required: true
            policy: ''
            notes: ''
        port:
            description: The Port the service is listening on.
            required: true
            policy: ''
            notes: ''
        target:
            description: The FQDN of the service.
            required: true
            policy: ''
            notes: ''
    attributes:
        id:
            description: The Private DNS SRV Record ID.
        fqdn:
            description: The FQDN of the DNS SRV Record.
    timeouts:
        create:
            description: Used when creating the Private DNS SRV Record.
            required: false
            timeout: 30
        update:
            description: Used when updating the Private DNS SRV Record.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Private DNS SRV Record.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Private DNS SRV Record.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbUZqWTJWd2RHRnVZMlZVWlhOMFVtVnpiM1Z5WTJWSGNt
        OTFjREVpQ2lBZ2JHOWpZWFJwYjI0Z1BTQWlWMlZ6ZENCVlV5SUtmUW9LY21WemIzVnlZMlVnSW1G
        NmRYSmxjbTFmY0hKcGRtRjBaVjlrYm5OZmVtOXVaU0lnSW5SbGMzUWlJSHNLSUNCdVlXMWxJQ0Fn
        SUNBZ0lDQWdJQ0FnSUNBZ0lEMGdJbU52Ym5SdmMyOHVZMjl0SWdvZ0lISmxjMjkxY21ObFgyZHli
        M1Z3WDI1aGJXVWdQU0JoZW5WeVpYSnRYM0psYzI5MWNtTmxYMmR5YjNWd0xuUmxjM1F1Ym1GdFpR
        cDlDZ3B5WlhOdmRYSmpaU0FpWVhwMWNtVnliVjl3Y21sMllYUmxYMlJ1YzE5emNuWmZjbVZqYjNK
        a0lpQWlkR1Z6ZENJZ2V3b2dJRzVoYldVZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnUFNBaWRHVnpkQ0lL
        SUNCeVpYTnZkWEpqWlY5bmNtOTFjRjl1WVcxbElEMGdZWHAxY21WeWJWOXlaWE52ZFhKalpWOW5j
        bTkxY0M1MFpYTjBMbTVoYldVS0lDQjZiMjVsWDI1aGJXVWdJQ0FnSUNBZ0lDQWdJRDBnWVhwMWNt
        VnliVjl3Y21sMllYUmxYMlJ1YzE5NmIyNWxMblJsYzNRdWJtRnRaUW9nSUhSMGJDQWdJQ0FnSUNB
        Z0lDQWdJQ0FnSUNBZ1BTQXpNREFLQ2lBZ2NtVmpiM0prSUhzS0lDQWdJSEJ5YVc5eWFYUjVJRDBn
        TVFvZ0lDQWdkMlZwWjJoMElDQWdQU0ExQ2lBZ0lDQndiM0owSUNBZ0lDQTlJRGd3T0RBS0lDQWdJ
        SFJoY21kbGRDQWdJRDBnSW5SaGNtZGxkREV1WTI5dWRHOXpieTVqYjIwaUNpQWdmUW9LSUNCeVpX
        TnZjbVFnZXdvZ0lDQWdjSEpwYjNKcGRIa2dQU0F4TUFvZ0lDQWdkMlZwWjJoMElDQWdQU0F4TUFv
        Z0lDQWdjRzl5ZENBZ0lDQWdQU0E0TURnd0NpQWdJQ0IwWVhKblpYUWdJQ0E5SUNKMFlYSm5aWFF5
        TG1OdmJuUnZjMjh1WTI5dElnb2dJSDBLQ2lBZ2RHRm5jeUE5SUhzS0lDQWdJRVZ1ZG1seWIyNXRa
        VzUwSUQwZ0lsQnliMlIxWTNScGIyNGlDaUFnZlFwOUNnPT0=
    import: !!binary |
        Q2dwUWNtbDJZWFJsSUVST1V5QlRVbFlnVW1WamIzSmtjeUJqWVc0Z1ltVWdhVzF3YjNKMFpXUWdk
        WE5wYm1jZ2RHaGxJR0J5WlhOdmRYSmpaU0JwWkdBc0lHVXVaeTRLQ2c9PQ==
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmNISnBkbUYwWlY5a2JuTmZjM0oyWDNKbFkyOXlaQzVvZEcxc0xtMWhjbXRrYjNk
        dQ==
