azurerm_iothub_consumer_group:
    status: HOLD
    subcategory: IoT Hub
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_iothub_consumer_group'
    description: Manages a Consumer Group within an IotHub
    arguments:
        name:
            description: The name of this Consumer Group. Changing this forces a new
                resource to be created.
            required: true
            policy: ''
            notes: ''
        iothub_name:
            description: The name of the IoT Hub. Changing this forces a new resource
                to be created.
            required: true
            policy: ''
            notes: ''
        eventhub_endpoint_name:
            description: The name of the Event Hub-compatible endpoint in the IoT
                hub. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group that contains the IoT hub.
                Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the IoTHub Consumer Group.
    timeouts:
        create:
            description: Used when creating the IotHub Consumer Group.
            required: false
            timeout: 30
        update:
            description: Used when updating the IotHub Consumer Group.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the IotHub Consumer Group.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the IotHub Consumer Group.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbkpsYzI5MWNtTmxSM0p2ZFhBeElnb2dJR3h2WTJGMGFX
        OXVJRDBnSWxkbGMzUWdWVk1pQ24wS0NuSmxjMjkxY21ObElDSmhlblZ5WlhKdFgybHZkR2gxWWlJ
        Z0ltVjRZVzF3YkdVaUlIc0tJQ0J1WVcxbElDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUQwZ0luUmxjM1Fp
        Q2lBZ2NtVnpiM1Z5WTJWZlozSnZkWEJmYm1GdFpTQTlJR0Y2ZFhKbGNtMWZjbVZ6YjNWeVkyVmZa
        M0p2ZFhBdVpYaGhiWEJzWlM1dVlXMWxDaUFnYkc5allYUnBiMjRnSUNBZ0lDQWdJQ0FnSUNBOUlH
        RjZkWEpsY20xZmNtVnpiM1Z5WTJWZlozSnZkWEF1WlhoaGJYQnNaUzVzYjJOaGRHbHZiZ29LSUNC
        emEzVWdld29nSUNBZ2JtRnRaU0FnSUNBZ1BTQWlVekVpQ2lBZ0lDQmpZWEJoWTJsMGVTQTlJQ0l4
        SWdvZ0lIMEtDaUFnZEdGbmN5QTlJSHNLSUNBZ0lIQjFjbkJ2YzJVZ1BTQWlkR1Z6ZEdsdVp5SUtJ
        Q0I5Q24wS0NuSmxjMjkxY21ObElDSmhlblZ5WlhKdFgybHZkR2gxWWw5amIyNXpkVzFsY2w5bmNt
        OTFjQ0lnSW1WNFlXMXdiR1VpSUhzS0lDQnVZVzFsSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUQw
        Z0luUmxjbkpoWm05eWJTSUtJQ0JwYjNSb2RXSmZibUZ0WlNBZ0lDQWdJQ0FnSUNBZ0lEMGdZWHAx
        Y21WeWJWOXBiM1JvZFdJdVpYaGhiWEJzWlM1dVlXMWxDaUFnWlhabGJuUm9kV0pmWlc1a2NHOXBi
        blJmYm1GdFpTQTlJQ0psZG1WdWRITWlDaUFnY21WemIzVnlZMlZmWjNKdmRYQmZibUZ0WlNBZ0lD
        QTlJR0Y2ZFhKbGNtMWZjbVZ6YjNWeVkyVmZaM0p2ZFhBdVptOXZMbTVoYldVS2ZRbz0=
    import: !!binary |
        Q2dwSmIxUklkV0lnUTI5dWMzVnRaWElnUjNKdmRYQnpJR05oYmlCaVpTQnBiWEJ2Y25SbFpDQjFj
        Mmx1WnlCMGFHVWdZSEpsYzI5MWNtTmxJR2xrWUN3Z1pTNW5MZ29L
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmFXOTBhSFZpWDJOdmJuTjFiV1Z5WDJkeWIzVndMbWgwYld3dWJXRnlhMlJ2ZDI0
        PQ==
