azurerm_logic_app_workflow:
    status: ASSESS
    subcategory: Logic App
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_logic_app_workflow'
    description: Manages a Logic App Workflow.
    arguments:
        name:
            description: Specifies the name of the Logic App Workflow. Changing this
                forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the Resource Group in which the Logic App Workflow
                should be created. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        location:
            description: Specifies the supported Azure location where the Logic App
                Workflow exists. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        workflow_schema:
            description: Specifies the Schema to use for this Logic App Workflow.
                Defaults to `https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#`.
                Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        workflow_version:
            description: Specifies the version of the Schema used for this Logic App
                Workflow. Defaults to `1.0.0.0`. Changing this forces a new resource
                to be created.
            required: false
            policy: ''
            notes: ''
        parameters:
            description: A map of Key-Value pairs.
            required: false
            policy: ''
            notes: Any parameters specified must exist in the Schema defined in `workflow_schema`.
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The Logic App Workflow ID.
        access_endpoint:
            description: The Access Endpoint for the Logic App Workflow.
        connector_endpoint_ip_addresses:
            description: The list of access endpoint ip addresses of connector.
        connector_outbound_ip_addresses:
            description: The list of outgoing ip addresses of connector.
        workflow_endpoint_ip_addresses:
            description: The list of access endpoint ip addresses of workflow.
        workflow_outbound_ip_addresses:
            description: The list of outgoing ip addresses of workflow.
    timeouts:
        create:
            description: Used when creating the Logic App Workflow.
            required: false
            timeout: 30
        update:
            description: Used when updating the Logic App Workflow.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Logic App Workflow.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Logic App Workflow.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbmR2Y210bWJHOTNMWEpsYzI5MWNtTmxjeUlLSUNCc2Iy
        TmhkR2x2YmlBOUlDSkZZWE4wSUZWVElncDlDZ3B5WlhOdmRYSmpaU0FpWVhwMWNtVnliVjlzYjJk
        cFkxOWhjSEJmZDI5eWEyWnNiM2NpSUNKbGVHRnRjR3hsSWlCN0NpQWdibUZ0WlNBZ0lDQWdJQ0Fn
        SUNBZ0lDQWdJQ0E5SUNKM2IzSnJabXh2ZHpFaUNpQWdiRzlqWVhScGIyNGdJQ0FnSUNBZ0lDQWdJ
        Q0E5SUdGNmRYSmxjbTFmY21WemIzVnlZMlZmWjNKdmRYQXVaWGhoYlhCc1pTNXNiMk5oZEdsdmJn
        b2dJSEpsYzI5MWNtTmxYMmR5YjNWd1gyNWhiV1VnUFNCaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJk
        eWIzVndMbVY0WVcxd2JHVXVibUZ0WlFwOUNnPT0=
    import: !!binary |
        Q2dwTWIyZHBZeUJCY0hBZ1YyOXlhMlpzYjNkeklHTmhiaUJpWlNCcGJYQnZjblJsWkNCMWMybHVa
        eUIwYUdVZ1lISmxjMjkxY21ObElHbGtZQ3dnWlM1bkxnb0s=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmJHOW5hV05mWVhCd1gzZHZjbXRtYkc5M0xtaDBiV3d1YldGeWEyUnZkMjQ9
