azurerm_sentinel_alert_rule_ms_security_incident:
    status: ASSESS
    subcategory: Sentinel
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_sentinel_alert_rule_ms_security_incident'
    description: Manages a Sentinel MS Security Incident Alert Rule.
    arguments: {}
    attributes: {}
    timeouts: {}
