azurerm_frontdoor_firewall_policy:
    status: ASSESS
    subcategory: Network
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_frontdoor_firewall_policy'
    description: Manages an Azure Front Door Web Application Firewall Policy instance.
    arguments:
        name:
            description: Gets name of the resource that is unique within a policy.
                This name can be used to access the resource.
            required: false
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group. Changing this forces a new
                resource to be created.
            required: false
            policy: ''
            notes: ''
        enabled:
            description: Is the managed rule override enabled or disabled. Defaults
                to `false`
            required: false
            policy: ''
            notes: ''
        mode:
            description: The firewall policy mode. Possible values are `Detection`,
                `Prevention` and defaults to `Prevention`.
            required: false
            policy: ''
            notes: ''
        redirect_url:
            description: If action type is redirect, this field represents redirect
                URL for the client.
            required: false
            policy: ''
            notes: ''
        custom_rule:
            description: One or more `custom_rule` blocks as defined below.
            required: false
            policy: ''
            notes: ''
        custom_block_response_status_code:
            description: If a `custom_rule` block's action type is `block`, this is
                the response status code. Possible values are `200`, `403`, `405`,
                `406`, or `429`.
            required: false
            policy: ''
            notes: ''
        custom_block_response_body:
            description: If a `custom_rule` block's action type is `block`, this is
                the response body. The body must be specified in base64 encoding.
            required: false
            policy: ''
            notes: ''
        managed_rule:
            description: One or more `managed_rule` blocks as defined below.
            required: false
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the Web Application Firewall
                Policy.
            required: false
            policy: ''
            notes: ''
        action:
            description: The action to be applied when the rule matches. Possible
                values are `Allow`, `Block`, `Log`, or `Redirect`.
            required: false
            policy: ''
            notes: ''
        priority:
            description: The priority of the rule. Rules with a lower value will be
                evaluated before rules with a higher value. Defaults to `1`.
            required: false
            policy: ''
            notes: ''
        type:
            description: The name of the managed rule to use with this resource.
            required: false
            policy: ''
            notes: ''
        match_condition:
            description: One or more `match_condition` block defined below.
            required: false
            policy: ''
            notes: ''
        rate_limit_duration_in_minutes:
            description: The rate limit duration in minutes. Defaults to `1`.
            required: false
            policy: ''
            notes: ''
        rate_limit_threshold:
            description: The rate limit threshold. Defaults to `10`.
            required: false
            policy: ''
            notes: ''
        match_variable:
            description: The variable type to be excluded. Possible values are `QueryStringArgNames`,
                `RequestBodyPostArgNames`, `RequestCookieNames`, `RequestHeaderNames`.
            required: false
            policy: ''
            notes: ''
        match_values:
            description: Up to `100` possible values to match.
            required: false
            policy: ''
            notes: ''
        operator:
            description: 'Comparison operator to apply to the selector when specifying
                which elements in the collection this exclusion applies to. Possible
                values are: `Equals`, `Contains`, `StartsWith`, `EndsWith`, `EqualsAny`.'
            required: false
            policy: ''
            notes: ''
        selector:
            description: Selector for the value in the `match_variable` attribute
                this exclusion applies to.
            required: false
            policy: ''
            notes: ''
        negation_condition:
            description: Should the result of the condition be negated.
            required: false
            policy: ''
            notes: ''
        transforms:
            description: Up to `5` transforms to apply. Possible values are `Lowercase`,
                `RemoveNulls`, `Trim`, `Uppercase`, `URLDecode` or`URLEncode`.
            required: false
            policy: ''
            notes: ''
        version:
            description: The version on the managed rule to use with this resource.
            required: false
            policy: ''
            notes: ''
        exclusion:
            description: One or more `exclusion` blocks as defined below.
            required: false
            policy: ''
            notes: ''
        override:
            description: One or more `override` blocks as defined below.
            required: false
            policy: ''
            notes: ''
        rule_group_name:
            description: The managed rule group to override.
            required: false
            policy: ''
            notes: ''
        rule:
            description: One or more `rule` blocks as defined below. If none are specified,
                all of the rules in the group will be disabled.
            required: false
            policy: ''
            notes: ''
        rule_id:
            description: Identifier for the managed rule.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: Resource ID.
        location:
            description: Resource location.
        frontend_endpoint_ids:
            description: the Frontend Endpoints associated with this Front Door Web
                Application Firewall policy.
    timeouts:
        create:
            description: Used when creating the FrontDoor Web Application Firewall
                Policy.
            required: false
            timeout: 30
        update:
            description: Used when updating the FrontDoor Web Application Firewall
                Policy.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the FrontDoor Web Application Firewall
                Policy.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the FrontDoor Web Application Firewall
                Policy.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbVY0WVcxd2JHVXRjbWNpQ2lBZ2JHOWpZWFJwYjI0Z1BT
        QWlWMlZ6ZENCVlV5QXlJZ3A5Q2dweVpYTnZkWEpqWlNBaVlYcDFjbVZ5YlY5bWNtOXVkR1J2YjNK
        ZlptbHlaWGRoYkd4ZmNHOXNhV041SWlBaVpYaGhiWEJzWlNJZ2V3b2dJRzVoYldVZ0lDQWdJQ0Fn
        SUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQTlJQ0psZUdGdGNHeGxMV1prZDJGbWNHOXNh
        V041SWdvZ0lISmxjMjkxY21ObFgyZHliM1Z3WDI1aGJXVWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBOUlH
        RjZkWEpsY20xZmNtVnpiM1Z5WTJWZlozSnZkWEF1WlhoaGJYQnNaUzV1WVcxbENpQWdaVzVoWW14
        bFpDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lEMGdkSEoxWlFvZ0lHMXZaR1Vn
        SUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBOUlDSlFjbVYyWlc1MGFXOXVJ
        Z29nSUhKbFpHbHlaV04wWDNWeWJDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0E5SUNKb2RI
        Undjem92TDNkM2R5NWpiMjUwYjNOdkxtTnZiU0lLSUNCamRYTjBiMjFmWW14dlkydGZjbVZ6Y0c5
        dWMyVmZjM1JoZEhWelgyTnZaR1VnUFNBME1ETUtJQ0JqZFhOMGIyMWZZbXh2WTJ0ZmNtVnpjRzl1
        YzJWZlltOWtlU0FnSUNBZ0lDQWdQU0FpVUVkb01HSlhkeXREYW5odldsZEdhMXBZU1N0UVNGSnda
        RWQ0YkZCcmFHeGlSM2gyVUVNNU1HRllVbk5hVkRRNFRESm9iRmxYVW14amFqUkxVRWRLZGxwSWF5
        dERhMmhzWWtkNGRrbElaSFpqYlhoclEycDNkbGx0T1d0bFZEUkxVRU01YjJSSE1YTlFaejA5SWdv
        S0lDQmpkWE4wYjIxZmNuVnNaU0I3Q2lBZ0lDQnVZVzFsSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0Fn
        SUNBZ0lDQWdJQ0FnUFNBaVVuVnNaVEVpQ2lBZ0lDQmxibUZpYkdWa0lDQWdJQ0FnSUNBZ0lDQWdJ
        Q0FnSUNBZ0lDQWdJQ0FnUFNCMGNuVmxDaUFnSUNCd2NtbHZjbWwwZVNBZ0lDQWdJQ0FnSUNBZ0lD
        QWdJQ0FnSUNBZ0lDQWdQU0F4Q2lBZ0lDQnlZWFJsWDJ4cGJXbDBYMlIxY21GMGFXOXVYMmx1WDIx
        cGJuVjBaWE1nUFNBeENpQWdJQ0J5WVhSbFgyeHBiV2wwWDNSb2NtVnphRzlzWkNBZ0lDQWdJQ0Fn
        SUNBZ1BTQXhNQW9nSUNBZ2RIbHdaU0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJ
        RDBnSWsxaGRHTm9VblZzWlNJS0lDQWdJR0ZqZEdsdmJpQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lD
        QWdJQ0FnSUNBOUlDSkNiRzlqYXlJS0NpQWdJQ0J0WVhSamFGOWpiMjVrYVhScGIyNGdld29nSUNB
        Z0lDQnRZWFJqYUY5MllYSnBZV0pzWlNBZ0lDQWdQU0FpVW1WdGIzUmxRV1JrY2lJS0lDQWdJQ0Fn
        YjNCbGNtRjBiM0lnSUNBZ0lDQWdJQ0FnSUQwZ0lrbFFUV0YwWTJnaUNpQWdJQ0FnSUc1bFoyRjBh
        Vzl1WDJOdmJtUnBkR2x2YmlBOUlHWmhiSE5sQ2lBZ0lDQWdJRzFoZEdOb1gzWmhiSFZsY3lBZ0lD
        QWdJQ0E5SUZzaU1Ua3lMakUyT0M0eExqQXZNalFpTENBaU1UQXVNQzR3TGpBdk1qUWlYUW9nSUNB
        Z2ZRb2dJSDBLQ2lBZ1kzVnpkRzl0WDNKMWJHVWdld29nSUNBZ2JtRnRaU0FnSUNBZ0lDQWdJQ0Fn
        SUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJRDBnSWxKMWJHVXlJZ29nSUNBZ1pXNWhZbXhsWkNBZ0lDQWdJ
        Q0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJRDBnZEhKMVpRb2dJQ0FnY0hKcGIzSnBkSGtnSUNBZ0lD
        QWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lEMGdNZ29nSUNBZ2NtRjBaVjlzYVcxcGRGOWtkWEpoZEds
        dmJsOXBibDl0YVc1MWRHVnpJRDBnTVFvZ0lDQWdjbUYwWlY5c2FXMXBkRjkwYUhKbGMyaHZiR1Fn
        SUNBZ0lDQWdJQ0FnSUQwZ01UQUtJQ0FnSUhSNWNHVWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJ
        Q0FnSUNBZ0lDQTlJQ0pOWVhSamFGSjFiR1VpQ2lBZ0lDQmhZM1JwYjI0Z0lDQWdJQ0FnSUNBZ0lD
        QWdJQ0FnSUNBZ0lDQWdJQ0FnUFNBaVFteHZZMnNpQ2dvZ0lDQWdiV0YwWTJoZlkyOXVaR2wwYVc5
        dUlIc0tJQ0FnSUNBZ2JXRjBZMmhmZG1GeWFXRmliR1VnSUNBZ0lEMGdJbEpsYlc5MFpVRmtaSElp
        Q2lBZ0lDQWdJRzl3WlhKaGRHOXlJQ0FnSUNBZ0lDQWdJQ0E5SUNKSlVFMWhkR05vSWdvZ0lDQWdJ
        Q0J1WldkaGRHbHZibDlqYjI1a2FYUnBiMjRnUFNCbVlXeHpaUW9nSUNBZ0lDQnRZWFJqYUY5MllX
        eDFaWE1nSUNBZ0lDQWdQU0JiSWpFNU1pNHhOamd1TVM0d0x6STBJbDBLSUNBZ0lIMEtDaUFnSUNC
        dFlYUmphRjlqYjI1a2FYUnBiMjRnZXdvZ0lDQWdJQ0J0WVhSamFGOTJZWEpwWVdKc1pTQWdJQ0Fn
        UFNBaVVtVnhkV1Z6ZEVobFlXUmxjaUlLSUNBZ0lDQWdjMlZzWldOMGIzSWdJQ0FnSUNBZ0lDQWdJ
        RDBnSWxWelpYSkJaMlZ1ZENJS0lDQWdJQ0FnYjNCbGNtRjBiM0lnSUNBZ0lDQWdJQ0FnSUQwZ0lr
        TnZiblJoYVc1eklnb2dJQ0FnSUNCdVpXZGhkR2x2Ymw5amIyNWthWFJwYjI0Z1BTQm1ZV3h6WlFv
        Z0lDQWdJQ0J0WVhSamFGOTJZV3gxWlhNZ0lDQWdJQ0FnUFNCYkluZHBibVJ2ZDNNaVhRb2dJQ0Fn
        SUNCMGNtRnVjMlp2Y20xeklDQWdJQ0FnSUNBZ1BTQmJJa3h2ZDJWeVkyRnpaU0lzSUNKVWNtbHRJ
        bDBLSUNBZ0lIMEtJQ0I5Q2dvZ0lHMWhibUZuWldSZmNuVnNaU0I3Q2lBZ0lDQjBlWEJsSUNBZ0lE
        MGdJa1JsWm1GMWJIUlNkV3hsVTJWMElnb2dJQ0FnZG1WeWMybHZiaUE5SUNJeExqQWlDZ29nSUNB
        Z1pYaGpiSFZ6YVc5dUlIc0tJQ0FnSUNBZ2JXRjBZMmhmZG1GeWFXRmliR1VnUFNBaVVYVmxjbmxU
        ZEhKcGJtZEJjbWRPWVcxbGN5SUtJQ0FnSUNBZ2IzQmxjbUYwYjNJZ0lDQWdJQ0FnUFNBaVJYRjFZ
        V3h6SWdvZ0lDQWdJQ0J6Wld4bFkzUnZjaUFnSUNBZ0lDQTlJQ0p1YjNSZmMzVnpjR2xqYVc5MWN5
        SUtJQ0FnSUgwS0NpQWdJQ0J2ZG1WeWNtbGtaU0I3Q2lBZ0lDQWdJSEoxYkdWZlozSnZkWEJmYm1G
        dFpTQTlJQ0pRU0ZBaUNnb2dJQ0FnSUNCeWRXeGxJSHNLSUNBZ0lDQWdJQ0J5ZFd4bFgybGtJRDBn
        SWprek16RXdNQ0lLSUNBZ0lDQWdJQ0JsYm1GaWJHVmtJRDBnWm1Gc2MyVUtJQ0FnSUNBZ0lDQmhZ
        M1JwYjI0Z0lEMGdJa0pzYjJOcklnb2dJQ0FnSUNCOUNpQWdJQ0I5Q2dvZ0lDQWdiM1psY25KcFpH
        VWdld29nSUNBZ0lDQnlkV3hsWDJkeWIzVndYMjVoYldVZ1BTQWlVMUZNU1NJS0NpQWdJQ0FnSUdW
        NFkyeDFjMmx2YmlCN0NpQWdJQ0FnSUNBZ2JXRjBZMmhmZG1GeWFXRmliR1VnUFNBaVVYVmxjbmxU
        ZEhKcGJtZEJjbWRPWVcxbGN5SUtJQ0FnSUNBZ0lDQnZjR1Z5WVhSdmNpQWdJQ0FnSUNBOUlDSkZj
        WFZoYkhNaUNpQWdJQ0FnSUNBZ2MyVnNaV04wYjNJZ0lDQWdJQ0FnUFNBaWNtVmhiR3g1WDI1dmRG
        OXpkWE53YVdOcGIzVnpJZ29nSUNBZ0lDQjlDZ29nSUNBZ0lDQnlkV3hsSUhzS0lDQWdJQ0FnSUNC
        eWRXeGxYMmxrSUQwZ0lqazBNakl3TUNJS0lDQWdJQ0FnSUNCaFkzUnBiMjRnSUQwZ0lrSnNiMk5y
        SWdvS0lDQWdJQ0FnSUNCbGVHTnNkWE5wYjI0Z2V3b2dJQ0FnSUNBZ0lDQWdiV0YwWTJoZmRtRnlh
        V0ZpYkdVZ1BTQWlVWFZsY25sVGRISnBibWRCY21kT1lXMWxjeUlLSUNBZ0lDQWdJQ0FnSUc5d1pY
        SmhkRzl5SUNBZ0lDQWdJRDBnSWtWeGRXRnNjeUlLSUNBZ0lDQWdJQ0FnSUhObGJHVmpkRzl5SUNB
        Z0lDQWdJRDBnSW1sdWJtOWpaVzUwSWdvZ0lDQWdJQ0FnSUgwS0lDQWdJQ0FnZlFvZ0lDQWdmUW9n
        SUgwS0NpQWdiV0Z1WVdkbFpGOXlkV3hsSUhzS0lDQWdJSFI1Y0dVZ0lDQWdQU0FpVFdsamNtOXpi
        MlowWDBKdmRFMWhibUZuWlhKU2RXeGxVMlYwSWdvZ0lDQWdkbVZ5YzJsdmJpQTlJQ0l4TGpBaUNp
        QWdmUXA5Q2c9PQ==
    import: !!binary |
        Q2dwR2NtOXVkRVJ2YjNJZ1YyVmlJRUZ3Y0d4cFkyRjBhVzl1SUVacGNtVjNZV3hzSUZCdmJHbGpl
        U0JqWVc0Z1ltVWdhVzF3YjNKMFpXUWdkWE5wYm1jZ2RHaGxJR0J5WlhOdmRYSmpaU0JwWkdBc0lH
        VXVaeTRLQ2c9PQ==
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdlpuSnZiblJrYjI5eVgyWnBjbVYzWVd4c1gzQnZiR2xqZVM1b2RHMXNMbTFoY210
        a2IzZHU=
