azurerm_api_management_api:
    status: ASSESS
    subcategory: API Management
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_api_management_api'
    description: Manages an API within an API Management Service.
    arguments:
        name:
            description: The name of the API Management API. Changing this forces
                a new resource to be created.
            required: true
            policy: ''
            notes: ''
        api_management_name:
            description: The Name of the API Management Service where this API should
                be created. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: The Name of the Resource Group where the API Management API
                exists. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        revision:
            description: The Revision which used for this API.
            required: true
            policy: ''
            notes: ''
        display_name:
            description: The display name of the API.
            required: true
            policy: ''
            notes: ''
        path:
            description: The Path for this API Management API, which is a relative
                URL which uniquely identifies this API and all of it's resource paths
                within the API Management Service.
            required: true
            policy: ''
            notes: ''
        protocols:
            description: A list of protocols the operations in this API can be invoked.
                Possible values are `http` and `https`.
            required: true
            policy: ''
            notes: ''
        description:
            description: A description of the API Management API, which may include
                HTML formatting tags.
            required: false
            policy: ''
            notes: ''
        import:
            description: A `import` block as documented below.
            required: false
            policy: ''
            notes: ''
        service_url:
            description: Absolute URL of the backend service implementing this API.
            required: false
            policy: ''
            notes: ''
        soap_pass_through:
            description: Should this API expose a SOAP frontend, rather than a HTTP
                frontend? Defaults to `false`.
            required: false
            policy: ''
            notes: ''
        subscription_key_parameter_names:
            description: A `subscription_key_parameter_names` block as documented
                below.
            required: false
            policy: ''
            notes: ''
        version:
            description: The Version number of this API, if this API is versioned.
            required: false
            policy: ''
            notes: ''
        version_set_id:
            description: The ID of the Version Set which this API is associated with.
            required: false
            policy: ''
            notes: When `version` is set, `version_set_id` must also be specified
        content_format:
            description: 'The format of the content from which the API Definition
                should be imported. Possible values are: `swagger-json`, `swagger-link-json`,
                `wadl-link-json`, `wadl-xml`, `wsdl` and `wsdl-link`.'
            required: true
            policy: ''
            notes: ''
        content_value:
            description: The Content from which the API Definition should be imported.
                When a `content_format` of `*-link-*` is specified this must be a
                URL, otherwise this must be defined inline.
            required: true
            policy: ''
            notes: ''
        wsdl_selector:
            description: A `wsdl_selector` block as defined below, which allows you
                to limit the import of a WSDL to only a subset of the document. This
                can only be specified when `content_format` is `wsdl` or `wsdl-link`.
            required: false
            policy: ''
            notes: ''
        header:
            description: The name of the HTTP Header which should be used for the
                Subscription Key.
            required: true
            policy: ''
            notes: ''
        query:
            description: The name of the QueryString parameter which should be used
                for the Subscription Key.
            required: true
            policy: ''
            notes: ''
        service_name:
            description: The name of service to import from WSDL.
            required: true
            policy: ''
            notes: ''
        endpoint_name:
            description: The name of endpoint (port
            required: true
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the API Management API.
        is_current:
            description: Is this the current API Revision?
        is_online:
            description: Is this API Revision online/accessible via the Gateway?
        version:
            description: The Version number of this API, if this API is versioned.
        version_set_id:
            description: The ID of the Version Set which this API is associated with.
    timeouts:
        create:
            description: Used when creating the API Management API.
            required: false
            timeout: 30
        update:
            description: Used when updating the API Management API.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the API Management API.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the API Management API.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbVY0WVcxd2JHVXRjbVZ6YjNWeVkyVnpJZ29nSUd4dlky
        RjBhVzl1SUQwZ0lsZGxjM1FnUlhWeWIzQmxJZ3A5Q2dweVpYTnZkWEpqWlNBaVlYcDFjbVZ5YlY5
        aGNHbGZiV0Z1WVdkbGJXVnVkQ0lnSW1WNFlXMXdiR1VpSUhzS0lDQnVZVzFsSUNBZ0lDQWdJQ0Fn
        SUNBZ0lDQWdJRDBnSW1WNFlXMXdiR1V0WVhCcGJTSUtJQ0JzYjJOaGRHbHZiaUFnSUNBZ0lDQWdJ
        Q0FnSUQwZ1lYcDFjbVZ5YlY5eVpYTnZkWEpqWlY5bmNtOTFjQzVsZUdGdGNHeGxMbXh2WTJGMGFX
        OXVDaUFnY21WemIzVnlZMlZmWjNKdmRYQmZibUZ0WlNBOUlHRjZkWEpsY20xZmNtVnpiM1Z5WTJW
        ZlozSnZkWEF1WlhoaGJYQnNaUzV1WVcxbENpQWdjSFZpYkdsemFHVnlYMjVoYldVZ0lDQWdJQ0E5
        SUNKTmVTQkRiMjF3WVc1NUlnb2dJSEIxWW14cGMyaGxjbDlsYldGcGJDQWdJQ0FnUFNBaVkyOXRj
        R0Z1ZVVCMFpYSnlZV1p2Y20wdWFXOGlDZ29nSUhOcmRWOXVZVzFsSUQwZ0lrUmxkbVZzYjNCbGNs
        OHhJZ3A5Q2dweVpYTnZkWEpqWlNBaVlYcDFjbVZ5YlY5aGNHbGZiV0Z1WVdkbGJXVnVkRjloY0dr
        aUlDSmxlR0Z0Y0d4bElpQjdDaUFnYm1GdFpTQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBOUlDSmxlR0Z0
        Y0d4bExXRndhU0lLSUNCeVpYTnZkWEpqWlY5bmNtOTFjRjl1WVcxbElEMGdZWHAxY21WeWJWOXla
        WE52ZFhKalpWOW5jbTkxY0M1bGVHRnRjR3hsTG01aGJXVUtJQ0JoY0dsZmJXRnVZV2RsYldWdWRG
        OXVZVzFsSUQwZ1lYcDFjbVZ5YlY5aGNHbGZiV0Z1WVdkbGJXVnVkQzVsZUdGdGNHeGxMbTVoYldV
        S0lDQnlaWFpwYzJsdmJpQWdJQ0FnSUNBZ0lDQWdJRDBnSWpFaUNpQWdaR2x6Y0d4aGVWOXVZVzFs
        SUNBZ0lDQWdJQ0E5SUNKRmVHRnRjR3hsSUVGUVNTSUtJQ0J3WVhSb0lDQWdJQ0FnSUNBZ0lDQWdJ
        Q0FnSUQwZ0ltVjRZVzF3YkdVaUNpQWdjSEp2ZEc5amIyeHpJQ0FnSUNBZ0lDQWdJQ0E5SUZzaWFI
        UjBjSE1pWFFvS0lDQnBiWEJ2Y25RZ2V3b2dJQ0FnWTI5dWRHVnVkRjltYjNKdFlYUWdQU0FpYzNk
        aFoyZGxjaTFzYVc1ckxXcHpiMjRpQ2lBZ0lDQmpiMjUwWlc1MFgzWmhiSFZsSUNBOUlDSm9kSFJ3
        T2k4dlkyOXVabVZ5Wlc1alpXRndhUzVoZW5WeVpYZGxZbk5wZEdWekxtNWxkQzgvWm05eWJXRjBQ
        V3B6YjI0aUNpQWdmUXA5Q2c9PQ==
    import: !!binary |
        Q2dwQlVFa2dUV0Z1WVdkbGJXVnVkQ0JCVUVrbmN5QmpZVzRnWW1VZ2FXMXdiM0owWldRZ2RYTnBi
        bWNnZEdobElHQnlaWE52ZFhKalpTQnBaR0FzSUdVdVp5NEtDZz09
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdllYQnBYMjFoYm1GblpXMWxiblJmWVhCcExtaDBiV3d1YldGeWEyUnZkMjQ9
