azurerm_data_factory_linked_service_postgresql:
    status: ASSESS
    subcategory: Data Factory
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_data_factory_linked_service_postgresql'
    description: Manages a Linked Service (connection) between PostgreSQL and Azure
        Data Factory.
    arguments:
        name:
            description: Specifies the name of the Data Factory Linked Service PostgreSQL.
                Changing this forces a new resource to be created. Must be globally
                unique. See the [Microsoft documentation](https://docs.microsoft.com/en-us/azure/data-factory/naming-rules
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group in which to create the Data
                Factory Linked Service PostgreSQL. Changing this forces a new resource
            required: true
            policy: ''
            notes: ''
        data_factory_name:
            description: The Data Factory name in which to associate the Linked Service
                with. Changing this forces a new resource.
            required: true
            policy: ''
            notes: ''
        connection_string:
            description: The connection string in which to authenticate with PostgreSQL.
            required: true
            policy: ''
            notes: ''
        description:
            description: The description for the Data Factory Linked Service PostgreSQL.
            required: false
            policy: ''
            notes: ''
        integration_runtime_name:
            description: The integration runtime reference to associate with the Data
                Factory Linked Service PostgreSQL.
            required: false
            policy: ''
            notes: ''
        annotations:
            description: List of tags that can be used for describing the Data Factory
                Linked Service PostgreSQL.
            required: false
            policy: ''
            notes: ''
        parameters:
            description: A map of parameters to associate with the Data Factory Linked
                Service PostgreSQL.
            required: false
            policy: ''
            notes: ''
        additional_properties:
            description: A map of additional properties to associate with the Data
                Factory Linked Service PostgreSQL.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the Data Factory PostgreSQL Linked Service.
    timeouts:
        create:
            description: Used when creating the Data Factory PostgreSQL Linked Service.
            required: false
            timeout: 30
        update:
            description: Used when updating the Data Factory PostgreSQL Linked Service.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Data Factory PostgreSQL Linked Service.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Data Factory PostgreSQL Linked Service.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbVY0WVcxd2JHVXRjbVZ6YjNWeVkyVnpJZ29nSUd4dlky
        RjBhVzl1SUQwZ0ltNXZjblJvWlhWeWIzQmxJZ3A5Q2dweVpYTnZkWEpqWlNBaVlYcDFjbVZ5YlY5
        a1lYUmhYMlpoWTNSdmNua2lJQ0psZUdGdGNHeGxJaUI3Q2lBZ2JtRnRaU0FnSUNBZ0lDQWdJQ0Fn
        SUNBZ0lDQTlJQ0psZUdGdGNHeGxJZ29nSUd4dlkyRjBhVzl1SUNBZ0lDQWdJQ0FnSUNBZ1BTQmhl
        blZ5WlhKdFgzSmxjMjkxY21ObFgyZHliM1Z3TG1WNFlXMXdiR1V1Ykc5allYUnBiMjRLSUNCeVpY
        TnZkWEpqWlY5bmNtOTFjRjl1WVcxbElEMGdZWHAxY21WeWJWOXlaWE52ZFhKalpWOW5jbTkxY0M1
        bGVHRnRjR3hsTG01aGJXVUtmUW9LY21WemIzVnlZMlVnSW1GNmRYSmxjbTFmWkdGMFlWOW1ZV04w
        YjNKNVgyeHBibXRsWkY5elpYSjJhV05sWDNCdmMzUm5jbVZ6Y1d3aUlDSmxlR0Z0Y0d4bElpQjdD
        aUFnYm1GdFpTQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBOUlDSmxlR0Z0Y0d4bElnb2dJSEpsYzI5MWNt
        TmxYMmR5YjNWd1gyNWhiV1VnUFNCaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndMbVY0WVcx
        d2JHVXVibUZ0WlFvZ0lHUmhkR0ZmWm1GamRHOXllVjl1WVcxbElDQWdQU0JoZW5WeVpYSnRYMlJo
        ZEdGZlptRmpkRzl5ZVM1bGVHRnRjR3hsTG01aGJXVUtJQ0JqYjI1dVpXTjBhVzl1WDNOMGNtbHVa
        eUFnSUQwZ0lraHZjM1E5WlhoaGJYQnNaVHRRYjNKMFBUVTBNekk3UkdGMFlXSmhjMlU5WlhoaGJY
        QnNaVHRWU1VROVpYaGhiWEJzWlR0RmJtTnllWEIwYVc5dVRXVjBhRzlrUFRBN1VHRnpjM2R2Y21R
        OVpYaGhiWEJzWlNJS2ZRbz0=
    import: !!binary |
        Q2dwRVlYUmhJRVpoWTNSdmNua2dVRzl6ZEdkeVpWTlJUQ0JNYVc1clpXUWdVMlZ5ZG1salpTZHpJ
        R05oYmlCaVpTQnBiWEJ2Y25SbFpDQjFjMmx1WnlCMGFHVWdZSEpsYzI5MWNtTmxJR2xrWUN3Z1pT
        NW5MZ29L
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdlpHRjBZVjltWVdOMGIzSjVYMnhwYm10bFpGOXpaWEoyYVdObFgzQnZjM1JuY21W
        emNXd3VhSFJ0YkM1dFlYSnJaRzkzYmc9PQ==
