azurerm_log_analytics_datasource_windows_performance_counter:
    status: ASSESS
    subcategory: Log Analytics
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_log_analytics_datasource_windows_performance_counter'
    description: Manages a Log Analytics (formally Operational Insights) Windows Performance
        Counter DataSource.
    arguments: {}
    attributes: {}
    timeouts: {}
    usage: {}
    import: {}
    hcl_url: {}
