azurerm_sql_database:
    status: ASSESS
    subcategory: Database
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_sql_database'
    description: Manages a SQL Database.
    arguments:
        name:
            description: The name of the database.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group in which to create the database.  This
                must be the same as Database Server resource group currently.
            required: true
            policy: ''
            notes: ''
        location:
            description: Specifies the supported Azure location where the resource
                exists. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        server_name:
            description: The name of the SQL Server on which to create the database.
            required: true
            policy: ''
            notes: ''
        create_mode:
            description: 'Specifies how to create the database. Valid values are:
                `Default`, `Copy`, `OnlineSecondary`, `NonReadableSecondary`,  `PointInTimeRestore`,
                `Recovery`, `Restore` or `RestoreLongTermRetentionBackup`. Must be
                `Default` to create a new database. Defaults to `Default`. Please
                see [Azure SQL Database REST API](https://docs.microsoft.com/en-us/rest/api/sql/databases/createorupdate#createmode)'
            required: false
            policy: ''
            notes: ''
        import:
            description: A Database Import block as documented below. `create_mode`
                must be set to `Default`.
            required: false
            policy: ''
            notes: ''
        source_database_id:
            description: The URI of the source database if `create_mode` value is
                not `Default`.
            required: false
            policy: ''
            notes: ''
        restore_point_in_time:
            description: The point in time for the restore. Only applies if `create_mode`
                is `PointInTimeRestore` e.g. 2013-11-08T22:00:40Z
            required: false
            policy: ''
            notes: ''
        edition:
            description: 'The edition of the database to be created. Applies only
                if `create_mode` is `Default`. Valid values are: `Basic`, `Standard`,
                `Premium`, `DataWarehouse`, `Business`, `BusinessCritical`, `Free`,
                `GeneralPurpose`, `Hyperscale`, `Premium`, `PremiumRS`, `Standard`,
                `Stretch`, `System`, `System2`, or `Web`. Please see [Azure SQL Database
                Service Tiers](https://azure.microsoft.com/en-gb/documentation/articles/sql-database-service-tiers/).'
            required: false
            policy: ''
            notes: ''
        collation:
            description: The name of the collation. Applies only if `create_mode`
                is `Default`.  Azure default is `SQL_LATIN1_GENERAL_CP1_CI_AS`. Changing
                this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        max_size_bytes:
            description: The maximum size that the database can grow to. Applies only
                if `create_mode` is `Default`.  Please see [Azure SQL Database Service
                Tiers](https://azure.microsoft.com/en-gb/documentation/articles/sql-database-service-tiers/).
            required: false
            policy: ''
            notes: ''
        requested_service_objective_id:
            description: A GUID/UUID corresponding to a configured Service Level Objective
                for the Azure SQL database which can be used to configure a performance
                level.
            required: false
            policy: ''
            notes: ''
        requested_service_objective_name:
            description: 'The service objective name for the database. Valid values
                depend on edition and location and may include `S0`, `S1`, `S2`, `S3`,
                `P1`, `P2`, `P4`, `P6`, `P11` and `ElasticPool`. You can list the
                available names with the cli: ```shell az sql db list-editions -l
                westus --edition Standard -o table ```. For further information please
                see [Azure CLI - az sql db](https://docs.microsoft.com/en-us/cli/azure/sql/db?view=azure-cli-latest#az-sql-db-list-editions).'
            required: false
            policy: ''
            notes: ''
        source_database_deletion_date:
            description: The deletion date time of the source database. Only applies
                to deleted databases where `create_mode` is `PointInTimeRestore`.
            required: false
            policy: ''
            notes: ''
        elastic_pool_name:
            description: The name of the elastic database pool.
            required: false
            policy: ''
            notes: ''
        threat_detection_policy:
            description: Threat detection policy configuration. The `threat_detection_policy`
                block supports fields documented below.
            required: false
            policy: ''
            notes: ''
        read_scale:
            description: Read-only connections will be redirected to a high-available
                replica. Please see [Use read-only replicas to load-balance read-only
                query workloads](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-read-scale-out).
            required: false
            policy: ''
            notes: ''
        zone_redundant:
            description: Whether or not this database is zone redundant, which means
                the replicas of this database will be spread across multiple availability
                zones.
            required: false
            policy: ''
            notes: ''
        extended_auditing_policy:
            description: A `extended_auditing_policy` block as defined below.
            required: false
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
        storage_uri:
            description: Specifies the blob URI of the .bacpac file.
            required: true
            policy: ''
            notes: ''
        storage_key:
            description: Specifies the access key for the storage account.
            required: true
            policy: ''
            notes: ''
        storage_key_type:
            description: Specifies the type of access key for the storage account.
                Valid values are `StorageAccessKey` or `SharedAccessKey`.
            required: true
            policy: ''
            notes: ''
        administrator_login:
            description: Specifies the name of the SQL administrator.
            required: true
            policy: ''
            notes: ''
        administrator_login_password:
            description: Specifies the password of the SQL administrator.
            required: true
            policy: ''
            notes: ''
        authentication_type:
            description: Specifies the type of authentication used to access the server.
                Valid values are `SQL` or `ADPassword`.
            required: true
            policy: ''
            notes: ''
        operation_mode:
            description: Specifies the type of import operation being performed. The
                only allowable value is `Import`.
            required: false
            policy: ''
            notes: ''
        state:
            description: The State of the Policy. Possible values are `Enabled`, `Disabled`
                or `New`.
            required: true
            policy: ''
            notes: ''
        disabled_alerts:
            description: Specifies a list of alerts which should be disabled. Possible
                values include `Access_Anomaly`, `Sql_Injection` and `Sql_Injection_Vulnerability`.
            required: false
            policy: ''
            notes: ''
        email_account_admins:
            description: Should the account administrators be emailed when this alert
                is triggered?
            required: false
            policy: ''
            notes: ''
        email_addresses:
            description: A list of email addresses which alerts should be sent to.
            required: false
            policy: ''
            notes: ''
        retention_days:
            description: Specifies the number of days to keep in the Threat Detection
                audit logs.
            required: false
            policy: ''
            notes: ''
        storage_account_access_key:
            description: ' Specifies the access key to use for the auditing storage
                account.'
            required: true
            policy: ''
            notes: ''
        storage_endpoint:
            description: Specifies the blob storage endpoint (e.g. https://MyAccount.blob.core.windows.net).
            required: true
            policy: ''
            notes: ''
        use_server_default:
            description: Should the default server policy be used? Defaults to `Disabled`.
            required: false
            policy: ''
            notes: ''
        storage_account_access_key_is_secondary:
            description: Specifies whether `storage_account_access_key` value is the
                storage's secondary key.
            required: false
            policy: ''
            notes: ''
        retention_in_days:
            description: Specifies the number of days to retain logs for in the storage
                account.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The SQL Database ID.
        creation_date:
            description: The creation date of the SQL Database.
        default_secondary_location:
            description: The default secondary location of the SQL Database.
    timeouts:
        create:
            description: Used when creating the SQL Database.
            required: false
            timeout: 60
        update:
            description: Used when updating the SQL Database.
            required: false
            timeout: 60
        read:
            description: Used when retrieving the SQL Database.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the SQL Database.
            required: false
            timeout: 60
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbUZqWTJWd2RHRnVZMlZVWlhOMFVtVnpiM1Z5WTJWSGNt
        OTFjREVpQ2lBZ2JHOWpZWFJwYjI0Z1BTQWlWMlZ6ZENCVlV5SUtmUW9LY21WemIzVnlZMlVnSW1G
        NmRYSmxjbTFmYzNGc1gzTmxjblpsY2lJZ0ltVjRZVzF3YkdVaUlIc0tJQ0J1WVcxbElDQWdJQ0Fn
        SUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUQwZ0ltMTVjM0ZzYzJWeWRtVnlJZ29nSUhKbGMyOTFj
        bU5sWDJkeWIzVndYMjVoYldVZ0lDQWdJQ0FnSUNBZ1BTQmhlblZ5WlhKdFgzSmxjMjkxY21ObFgy
        ZHliM1Z3TG1WNFlXMXdiR1V1Ym1GdFpRb2dJR3h2WTJGMGFXOXVJQ0FnSUNBZ0lDQWdJQ0FnSUNB
        Z0lDQWdJQ0FnUFNBaVYyVnpkQ0JWVXlJS0lDQjJaWEp6YVc5dUlDQWdJQ0FnSUNBZ0lDQWdJQ0Fn
        SUNBZ0lDQWdJRDBnSWpFeUxqQWlDaUFnWVdSdGFXNXBjM1J5WVhSdmNsOXNiMmRwYmlBZ0lDQWdJ
        Q0FnSUNBOUlDSTBaRzB4YmpFMU4zSTBOekJ5SWdvZ0lHRmtiV2x1YVhOMGNtRjBiM0pmYkc5bmFX
        NWZjR0Z6YzNkdmNtUWdQU0FpTkMxMk0zSjVMVFV6WTNJek55MXdORFUxZHpCeVpDSUtDaUFnZEdG
        bmN5QTlJSHNLSUNBZ0lHVnVkbWx5YjI1dFpXNTBJRDBnSW5CeWIyUjFZM1JwYjI0aUNpQWdmUXA5
        Q2dweVpYTnZkWEpqWlNBaVlYcDFjbVZ5YlY5emRHOXlZV2RsWDJGalkyOTFiblFpSUNKbGVHRnRj
        R3hsSWlCN0NpQWdibUZ0WlNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lEMGdJbVY0WVcxd2JH
        VnpZU0lLSUNCeVpYTnZkWEpqWlY5bmNtOTFjRjl1WVcxbElDQWdJQ0FnUFNCaGVuVnlaWEp0WDNK
        bGMyOTFjbU5sWDJkeWIzVndMbVY0WVcxd2JHVXVibUZ0WlFvZ0lHeHZZMkYwYVc5dUlDQWdJQ0Fn
        SUNBZ0lDQWdJQ0FnSUNBOUlHRjZkWEpsY20xZmNtVnpiM1Z5WTJWZlozSnZkWEF1WlhoaGJYQnNa
        UzVzYjJOaGRHbHZiZ29nSUdGalkyOTFiblJmZEdsbGNpQWdJQ0FnSUNBZ0lDQWdJQ0E5SUNKVGRH
        RnVaR0Z5WkNJS0lDQmhZMk52ZFc1MFgzSmxjR3hwWTJGMGFXOXVYM1I1Y0dVZ1BTQWlURkpUSWdw
        OUNncHlaWE52ZFhKalpTQWlZWHAxY21WeWJWOXpjV3hmWkdGMFlXSmhjMlVpSUNKbGVHRnRjR3hs
        SWlCN0NpQWdibUZ0WlNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0E5SUNKdGVYTnhiR1JoZEdGaVlYTmxJ
        Z29nSUhKbGMyOTFjbU5sWDJkeWIzVndYMjVoYldVZ1BTQmhlblZ5WlhKdFgzSmxjMjkxY21ObFgy
        ZHliM1Z3TG1WNFlXMXdiR1V1Ym1GdFpRb2dJR3h2WTJGMGFXOXVJQ0FnSUNBZ0lDQWdJQ0FnUFNB
        aVYyVnpkQ0JWVXlJS0lDQnpaWEoyWlhKZmJtRnRaU0FnSUNBZ0lDQWdJRDBnWVhwMWNtVnliVjl6
        Y1d4ZmMyVnlkbVZ5TG1WNFlXMXdiR1V1Ym1GdFpRb0tJQ0JsZUhSbGJtUmxaRjloZFdScGRHbHVa
        MTl3YjJ4cFkza2dld29nSUNBZ2MzUnZjbUZuWlY5bGJtUndiMmx1ZENBZ0lDQWdJQ0FnSUNBZ0lD
        QWdJQ0FnSUNBZ0lDQWdJRDBnWVhwMWNtVnliVjl6ZEc5eVlXZGxYMkZqWTI5MWJuUXVaWGhoYlhC
        c1pTNXdjbWx0WVhKNVgySnNiMkpmWlc1a2NHOXBiblFLSUNBZ0lITjBiM0poWjJWZllXTmpiM1Z1
        ZEY5aFkyTmxjM05mYTJWNUlDQWdJQ0FnSUNBZ0lDQWdJQ0E5SUdGNmRYSmxjbTFmYzNSdmNtRm5a
        VjloWTJOdmRXNTBMbVY0WVcxd2JHVXVjSEpwYldGeWVWOWhZMk5sYzNOZmEyVjVDaUFnSUNCemRH
        OXlZV2RsWDJGalkyOTFiblJmWVdOalpYTnpYMnRsZVY5cGMxOXpaV052Ym1SaGNua2dQU0IwY25W
        bENpQWdJQ0J5WlhSbGJuUnBiMjVmYVc1ZlpHRjVjeUFnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0Fn
        SUNBZ1BTQTJDaUFnZlFvS0Nnb2dJSFJoWjNNZ1BTQjdDaUFnSUNCbGJuWnBjbTl1YldWdWRDQTlJ
        Q0p3Y205a2RXTjBhVzl1SWdvZ0lIMEtmUW89
    import: !!binary |
        Q2dwVFVVd2dSR0YwWVdKaGMyVnpJR05oYmlCaVpTQnBiWEJ2Y25SbFpDQjFjMmx1WnlCMGFHVWdZ
        SEpsYzI5MWNtTmxJR2xrWUN3Z1pTNW5MZ29L
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmMzRnNYMlJoZEdGaVlYTmxMbWgwYld3dWJXRnlhMlJ2ZDI0PQ==
