azurerm_automation_variable_string:
    status: ASSESS
    subcategory: Automation
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_automation_variable_string'
    description: Manages a string variable in Azure Automation.
    arguments:
        name:
            description: The name of the Automation Variable. Changing this forces
                a new resource to be created.
            required: false
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group in which to create the Automation
                Variable. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        automation_account_name:
            description: The name of the automation account in which the Variable
                is created. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        description:
            description: The description of the Automation Variable.
            required: false
            policy: ''
            notes: ''
        encrypted:
            description: Specifies if the Automation Variable is encrypted. Defaults
                to `false`.
            required: false
            policy: ''
            notes: ''
        value:
            description: The value of the Automation Variable as a `string`.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the Automation Variable.
    timeouts:
        create:
            description: Used when creating the Automation String Variable.
            required: false
            timeout: 30
        update:
            description: Used when updating the Automation String Variable.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Automation String Variable.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Automation String Variable.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJblJtWlhndFpYaGhiWEJzWlMxeVp5SUtJQ0JzYjJOaGRH
        bHZiaUE5SUNKWFpYTjBJRlZUSWdwOUNncHlaWE52ZFhKalpTQWlZWHAxY21WeWJWOWhkWFJ2YldG
        MGFXOXVYMkZqWTI5MWJuUWlJQ0psZUdGdGNHeGxJaUI3Q2lBZ2JtRnRaU0FnSUNBZ0lDQWdJQ0Fn
        SUNBZ0lDQTlJQ0owWm1WNExXVjRZVzF3YkdVdFlXTmpiM1Z1ZENJS0lDQnNiMk5oZEdsdmJpQWdJ
        Q0FnSUNBZ0lDQWdJRDBnWVhwMWNtVnliVjl5WlhOdmRYSmpaVjluY205MWNDNWxlR0Z0Y0d4bExt
        eHZZMkYwYVc5dUNpQWdjbVZ6YjNWeVkyVmZaM0p2ZFhCZmJtRnRaU0E5SUdGNmRYSmxjbTFmY21W
        emIzVnlZMlZmWjNKdmRYQXVaWGhoYlhCc1pTNXVZVzFsQ2dvZ0lITnJkU0I3Q2lBZ0lDQnVZVzFs
        SUQwZ0lrSmhjMmxqSWdvZ0lIMEtmUW9LY21WemIzVnlZMlVnSW1GNmRYSmxjbTFmWVhWMGIyMWhk
        R2x2Ymw5MllYSnBZV0pzWlY5emRISnBibWNpSUNKbGVHRnRjR3hsSWlCN0NpQWdibUZ0WlNBZ0lD
        QWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ1BTQWlkR1psZUMxbGVHRnRjR3hsTFhaaGNpSUtJQ0J5WlhO
        dmRYSmpaVjluY205MWNGOXVZVzFsSUNBZ0lDQTlJR0Y2ZFhKbGNtMWZjbVZ6YjNWeVkyVmZaM0p2
        ZFhBdVpYaGhiWEJzWlM1dVlXMWxDaUFnWVhWMGIyMWhkR2x2Ymw5aFkyTnZkVzUwWDI1aGJXVWdQ
        U0JoZW5WeVpYSnRYMkYxZEc5dFlYUnBiMjVmWVdOamIzVnVkQzVsZUdGdGNHeGxMbTVoYldVS0lD
        QjJZV3gxWlNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBOUlDSklaV3hzYnl3Z1ZHVnljbUZtYjNK
        dElFSmhjMmxqSUZSbGMzUXVJZ3A5Q2c9PQ==
    import: !!binary |
        Q2dwQmRYUnZiV0YwYVc5dUlGTjBjbWx1WnlCV1lYSnBZV0pzWlNCallXNGdZbVVnYVcxd2IzSjBa
        V1FnZFhOcGJtY2dkR2hsSUdCeVpYTnZkWEpqWlNCcFpHQXNJR1V1Wnk0S0NnPT0=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdllYVjBiMjFoZEdsdmJsOTJZWEpwWVdKc1pWOXpkSEpwYm1jdWFIUnRiQzV0WVhK
        clpHOTNiZz09
