azurerm_dns_ns_record:
    status: ASSESS
    subcategory: DNS
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_dns_ns_record'
    description: Manages a DNS NS Record.
    arguments:
        name:
            description: The name of the DNS NS Record.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: Specifies the resource group where the resource exists. Changing
                this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        zone_name:
            description: Specifies the DNS Zone where the DNS Zone (parent resource
            required: true
            policy: ''
            notes: ''
        ttl:
            description: The Time To Live (TTL
            required: true
            policy: ''
            notes: ''
        records:
            description: 'A list of values that make up the NS record. '
            required: true
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The DNS NS Record ID.
        fqdn:
            description: The FQDN of the DNS NS Record.
    timeouts:
        create:
            description: Used when creating the DNS NS Record.
            required: false
            timeout: 30
        update:
            description: Used when updating the DNS NS Record.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the DNS NS Record.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the DNS NS Record.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbUZqWTJWd2RHRnVZMlZVWlhOMFVtVnpiM1Z5WTJWSGNt
        OTFjREVpQ2lBZ2JHOWpZWFJwYjI0Z1BTQWlWMlZ6ZENCVlV5SUtmUW9LY21WemIzVnlZMlVnSW1G
        NmRYSmxjbTFmWkc1elgzcHZibVVpSUNKbGVHRnRjR3hsSWlCN0NpQWdibUZ0WlNBZ0lDQWdJQ0Fn
        SUNBZ0lDQWdJQ0E5SUNKdGVXUnZiV0ZwYmk1amIyMGlDaUFnY21WemIzVnlZMlZmWjNKdmRYQmZi
        bUZ0WlNBOUlHRjZkWEpsY20xZmNtVnpiM1Z5WTJWZlozSnZkWEF1WlhoaGJYQnNaUzV1WVcxbENu
        MEtDbkpsYzI5MWNtTmxJQ0poZW5WeVpYSnRYMlJ1YzE5dWMxOXlaV052Y21RaUlDSmxlR0Z0Y0d4
        bElpQjdDaUFnYm1GdFpTQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBOUlDSjBaWE4wSWdvZ0lIcHZibVZm
        Ym1GdFpTQWdJQ0FnSUNBZ0lDQWdQU0JoZW5WeVpYSnRYMlJ1YzE5NmIyNWxMbVY0WVcxd2JHVXVi
        bUZ0WlFvZ0lISmxjMjkxY21ObFgyZHliM1Z3WDI1aGJXVWdQU0JoZW5WeVpYSnRYM0psYzI5MWNt
        TmxYMmR5YjNWd0xtVjRZVzF3YkdVdWJtRnRaUW9nSUhSMGJDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNB
        Z1BTQXpNREFLQ2lBZ2NtVmpiM0prY3lBOUlGc2libk14TG1OdmJuUnZjMjh1WTI5dElpd2dJbTV6
        TWk1amIyNTBiM052TG1OdmJTSmRDZ29nSUhSaFozTWdQU0I3Q2lBZ0lDQkZiblpwY205dWJXVnVk
        Q0E5SUNKUWNtOWtkV04wYVc5dUlnb2dJSDBLZlFvPQ==
    import: !!binary |
        Q2dwT1V5QnlaV052Y21SeklHTmhiaUJpWlNCcGJYQnZjblJsWkNCMWMybHVaeUIwYUdVZ1lISmxj
        MjkxY21ObElHbGtZQ3dnWlM1bkxnb0s=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdlpHNXpYMjV6WDNKbFkyOXlaQzVvZEcxc0xtMWhjbXRrYjNkdQ==
