azurerm_api_management_product_api:
    status: ASSESS
    subcategory: API Management
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_api_management_product_api'
    description: Manages an API Management API Assignment to a Product.
    arguments:
        api_name:
            description: The Name of the API Management API within the API Management
                Service. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        api_management_name:
            description: The name of the API Management Service. Changing this forces
                a new resource to be created.
            required: false
            policy: ''
            notes: ''
        product_id:
            description: The ID of the API Management Product within the API Management
                Service. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the Resource Group in which the API Management
                Service exists. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the API Management Product API.
    timeouts:
        create:
            description: Used when creating the API Management Product API.
            required: false
            timeout: 30
        update:
            description: Used when updating the API Management Product API.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the API Management Product API.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the API Management Product API.
            required: false
            timeout: 30
    usage: !!binary |
        Q21SaGRHRWdJbUY2ZFhKbGNtMWZZWEJwWDIxaGJtRm5aVzFsYm5RaUlDSmxlR0Z0Y0d4bElpQjdD
        aUFnYm1GdFpTQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBOUlDSmxlR0Z0Y0d4bExXRndhU0lLSUNCeVpY
        TnZkWEpqWlY5bmNtOTFjRjl1WVcxbElEMGdJbVY0WVcxd2JHVXRjbVZ6YjNWeVkyVnpJZ3A5Q2dw
        a1lYUmhJQ0poZW5WeVpYSnRYMkZ3YVY5dFlXNWhaMlZ0Wlc1MFgyRndhU0lnSW1WNFlXMXdiR1Vp
        SUhzS0lDQnVZVzFsSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJRDBnSW5ObFlYSmphQzFoY0draUNpQWdZ
        WEJwWDIxaGJtRm5aVzFsYm5SZmJtRnRaU0E5SUdSaGRHRXVZWHAxY21WeWJWOWhjR2xmYldGdVlX
        ZGxiV1Z1ZEM1bGVHRnRjR3hsTG01aGJXVUtJQ0J5WlhOdmRYSmpaVjluY205MWNGOXVZVzFsSUQw
        Z1pHRjBZUzVoZW5WeVpYSnRYMkZ3YVY5dFlXNWhaMlZ0Wlc1MExtVjRZVzF3YkdVdWNtVnpiM1Z5
        WTJWZlozSnZkWEJmYm1GdFpRb2dJSEpsZG1semFXOXVJQ0FnSUNBZ0lDQWdJQ0FnUFNBaU1pSUtm
        UW9LWkdGMFlTQWlZWHAxY21WeWJWOWhjR2xmYldGdVlXZGxiV1Z1ZEY5d2NtOWtkV04wSWlBaVpY
        aGhiWEJzWlNJZ2V3b2dJSEJ5YjJSMVkzUmZhV1FnSUNBZ0lDQWdJQ0FnUFNBaWJYa3RjSEp2WkhW
        amRDSUtJQ0JoY0dsZmJXRnVZV2RsYldWdWRGOXVZVzFsSUQwZ1pHRjBZUzVoZW5WeVpYSnRYMkZ3
        YVY5dFlXNWhaMlZ0Wlc1MExtVjRZVzF3YkdVdWJtRnRaUW9nSUhKbGMyOTFjbU5sWDJkeWIzVndY
        MjVoYldVZ1BTQmtZWFJoTG1GNmRYSmxjbTFmWVhCcFgyMWhibUZuWlcxbGJuUXVaWGhoYlhCc1pT
        NXlaWE52ZFhKalpWOW5jbTkxY0Y5dVlXMWxDbjBLQ25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDJG
        d2FWOXRZVzVoWjJWdFpXNTBYM0J5YjJSMVkzUmZZWEJwSWlBaVpYaGhiWEJzWlNJZ2V3b2dJR0Z3
        YVY5dVlXMWxJQ0FnSUNBZ0lDQWdJQ0FnUFNCa1lYUmhMbUY2ZFhKbGNtMWZZWEJwWDIxaGJtRm5a
        VzFsYm5SZllYQnBMbVY0WVcxd2JHVXVibUZ0WlFvZ0lIQnliMlIxWTNSZmFXUWdJQ0FnSUNBZ0lD
        QWdQU0JrWVhSaExtRjZkWEpsY20xZllYQnBYMjFoYm1GblpXMWxiblJmY0hKdlpIVmpkQzVsZUdG
        dGNHeGxMbkJ5YjJSMVkzUmZhV1FLSUNCaGNHbGZiV0Z1WVdkbGJXVnVkRjl1WVcxbElEMGdaR0Yw
        WVM1aGVuVnlaWEp0WDJGd2FWOXRZVzVoWjJWdFpXNTBMbVY0WVcxd2JHVXVibUZ0WlFvZ0lISmxj
        MjkxY21ObFgyZHliM1Z3WDI1aGJXVWdQU0JrWVhSaExtRjZkWEpsY20xZllYQnBYMjFoYm1GblpX
        MWxiblF1WlhoaGJYQnNaUzV5WlhOdmRYSmpaVjluY205MWNGOXVZVzFsQ24wSw==
    import: !!binary |
        Q2dwQlVFa2dUV0Z1WVdkbGJXVnVkQ0JRY205a2RXTjBJRUZRU1NkeklHTmhiaUJpWlNCcGJYQnZj
        blJsWkNCMWMybHVaeUIwYUdVZ1lISmxjMjkxY21ObElHbGtZQ3dnWlM1bkxnb0s=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdllYQnBYMjFoYm1GblpXMWxiblJmY0hKdlpIVmpkRjloY0drdWFIUnRiQzV0WVhK
        clpHOTNiZz09
