azurerm_logic_app_trigger_recurrence:
    status: ASSESS
    subcategory: Logic App
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_logic_app_trigger_recurrence'
    description: Manages a Recurrence Trigger within a Logic App Workflow
    arguments:
        name:
            description: Specifies the name of the Recurrence Triggers to be created
                within the Logic App Workflow. Changing this forces a new resource
                to be created.
            required: true
            policy: ''
            notes: This name must be unique across all Triggers within the Logic App
                Workflow.
        logic_app_id:
            description: Specifies the ID of the Logic App Workflow. Changing this
                forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        frequency:
            description: Specifies the Frequency at which this Trigger should be run.
                Possible values include `Month`, `Week`, `Day`, `Hour`, `Minute` and
                `Second`.
            required: true
            policy: ''
            notes: ''
        interval:
            description: Specifies interval used for the Frequency, for example a
                value of `4` for `interval` and `hour` for `frequency` would run the
                Trigger every 4 hours.
            required: true
            policy: ''
            notes: ''
        start_time:
            description: 'Specifies the start date and time for this trigger in RFC3339
                format: `2000-01-02T03:04:05Z`.'
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the Recurrence Trigger within the Logic App Workflow.
    timeouts:
        create:
            description: Used when creating the Logic App Recurrence Trigger.
            required: false
            timeout: 30
        update:
            description: Used when updating the Logic App Recurrence Trigger.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Logic App Recurrence Trigger.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Logic App Recurrence Trigger.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbmR2Y210bWJHOTNMWEpsYzI5MWNtTmxjeUlLSUNCc2Iy
        TmhkR2x2YmlBOUlDSkZZWE4wSUZWVElncDlDZ3B5WlhOdmRYSmpaU0FpWVhwMWNtVnliVjlzYjJk
        cFkxOWhjSEJmZDI5eWEyWnNiM2NpSUNKbGVHRnRjR3hsSWlCN0NpQWdibUZ0WlNBZ0lDQWdJQ0Fn
        SUNBZ0lDQWdJQ0E5SUNKM2IzSnJabXh2ZHpFaUNpQWdiRzlqWVhScGIyNGdJQ0FnSUNBZ0lDQWdJ
        Q0E5SUdGNmRYSmxjbTFmY21WemIzVnlZMlZmWjNKdmRYQXVaWGhoYlhCc1pTNXNiMk5oZEdsdmJn
        b2dJSEpsYzI5MWNtTmxYMmR5YjNWd1gyNWhiV1VnUFNCaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJk
        eWIzVndMbVY0WVcxd2JHVXVibUZ0WlFwOUNncHlaWE52ZFhKalpTQWlZWHAxY21WeWJWOXNiMmRw
        WTE5aGNIQmZkSEpwWjJkbGNsOXlaV04xY25KbGJtTmxJaUFpWlhoaGJYQnNaU0lnZXdvZ0lHNWhi
        V1VnSUNBZ0lDQWdJQ0E5SUNKeWRXNHRaWFpsY25rdFpHRjVJZ29nSUd4dloybGpYMkZ3Y0Y5cFpD
        QTlJR0Y2ZFhKbGNtMWZiRzluYVdOZllYQndYM2R2Y210bWJHOTNMbVY0WVcxd2JHVXVhV1FLSUNC
        bWNtVnhkV1Z1WTNrZ0lDQWdQU0FpUkdGNUlnb2dJR2x1ZEdWeWRtRnNJQ0FnSUNBOUlERUtmUW89
    import: !!binary |
        Q2dwTWIyZHBZeUJCY0hBZ1VtVmpkWEp5Wlc1alpTQlVjbWxuWjJWeWN5QmpZVzRnWW1VZ2FXMXdi
        M0owWldRZ2RYTnBibWNnZEdobElHQnlaWE52ZFhKalpTQnBaR0FzSUdVdVp5NEtDZz09
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmJHOW5hV05mWVhCd1gzUnlhV2RuWlhKZmNtVmpkWEp5Wlc1alpTNW9kRzFzTG0x
        aGNtdGtiM2R1
