azurerm_cdn_endpoint:
    status: ASSESS
    subcategory: CDN
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_cdn_endpoint'
    description: Manages a CDN Endpoint.
    arguments: {}
    attributes: {}
    timeouts: {}
    usage: {}
    import: {}
    hcl_url: {}
