azurerm_api_management_product:
    status: ASSESS
    subcategory: API Management
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_api_management_product'
    description: Manages an API Management Product.
    arguments:
        api_management_name:
            description: The name of the API Management Service. Changing this forces
                a new resource to be created.
            required: true
            policy: ''
            notes: ''
        approval_required:
            description: Do subscribers need to be approved prior to being able to
                use the Product?
            required: false
            policy: ''
            notes: '`approval_required` can only be set when `subscription_required`
                is set to `true`.'
        display_name:
            description: The Display Name for this API Management Product.
            required: true
            policy: ''
            notes: ''
        product_id:
            description: The Identifier for this Product, which must be unique within
                the API Management Service. Changing this forces a new resource to
                be created.
            required: true
            policy: ''
            notes: ''
        published:
            description: Is this Product Published?
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the Resource Group in which the API Management
                Service should be exist. Changing this forces a new resource to be
                created.
            required: true
            policy: ''
            notes: ''
        subscription_required:
            description: Is a Subscription required to access API's included in this
                Product?
            required: true
            policy: ''
            notes: ''
        description:
            description: A description of this Product, which may include HTML formatting
                tags.
            required: false
            policy: ''
            notes: ''
        subscriptions_limit:
            description: The number of subscriptions a user can have to this Product
                at the same time.
            required: false
            policy: ''
            notes: '`subscriptions_limit` can only be set when `subscription_required`
                is set to `true`.'
        terms:
            description: The Terms and Conditions for this Product, which must be
                accepted by Developers before they can begin the Subscription process.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the API Management Product.
    timeouts:
        create:
            description: Used when creating the API Management Product.
            required: false
            timeout: 30
        update:
            description: Used when updating the API Management Product.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the API Management Product.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the API Management Product.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbVY0WVcxd2JHVXRjbVZ6YjNWeVkyVnpJZ29nSUd4dlky
        RjBhVzl1SUQwZ0lsZGxjM1FnUlhWeWIzQmxJZ3A5Q2dweVpYTnZkWEpqWlNBaVlYcDFjbVZ5YlY5
        aGNHbGZiV0Z1WVdkbGJXVnVkQ0lnSW1WNFlXMXdiR1VpSUhzS0lDQnVZVzFsSUNBZ0lDQWdJQ0Fn
        SUNBZ0lDQWdJRDBnSW1WNFlXMXdiR1V0WVhCcGJTSUtJQ0JzYjJOaGRHbHZiaUFnSUNBZ0lDQWdJ
        Q0FnSUQwZ1lYcDFjbVZ5YlY5eVpYTnZkWEpqWlY5bmNtOTFjQzVsZUdGdGNHeGxMbXh2WTJGMGFX
        OXVDaUFnY21WemIzVnlZMlZmWjNKdmRYQmZibUZ0WlNBOUlHRjZkWEpsY20xZmNtVnpiM1Z5WTJW
        ZlozSnZkWEF1WlhoaGJYQnNaUzV1WVcxbENpQWdjSFZpYkdsemFHVnlYMjVoYldVZ0lDQWdJQ0E5
        SUNKTmVTQkRiMjF3WVc1NUlnb2dJSEIxWW14cGMyaGxjbDlsYldGcGJDQWdJQ0FnUFNBaVkyOXRj
        R0Z1ZVVCMFpYSnlZV1p2Y20wdWFXOGlDZ29nSUhOcmRWOXVZVzFsSUQwZ0lrUmxkbVZzYjNCbGNs
        OHhJZ3A5Q2dweVpYTnZkWEpqWlNBaVlYcDFjbVZ5YlY5aGNHbGZiV0Z1WVdkbGJXVnVkRjl3Y205
        a2RXTjBJaUFpWlhoaGJYQnNaU0lnZXdvZ0lIQnliMlIxWTNSZmFXUWdJQ0FnSUNBZ0lDQWdJQ0E5
        SUNKMFpYTjBMWEJ5YjJSMVkzUWlDaUFnWVhCcFgyMWhibUZuWlcxbGJuUmZibUZ0WlNBZ0lEMGdZ
        WHAxY21WeWJWOWhjR2xmYldGdVlXZGxiV1Z1ZEM1bGVHRnRjR3hsTG01aGJXVUtJQ0J5WlhOdmRY
        SmpaVjluY205MWNGOXVZVzFsSUNBZ1BTQmhlblZ5WlhKdFgzSmxjMjkxY21ObFgyZHliM1Z3TG1W
        NFlXMXdiR1V1Ym1GdFpRb2dJR1JwYzNCc1lYbGZibUZ0WlNBZ0lDQWdJQ0FnSUNBOUlDSlVaWE4w
        SUZCeWIyUjFZM1FpQ2lBZ2MzVmljMk55YVhCMGFXOXVYM0psY1hWcGNtVmtJRDBnZEhKMVpRb2dJ
        R0Z3Y0hKdmRtRnNYM0psY1hWcGNtVmtJQ0FnSUNBOUlIUnlkV1VLSUNCd2RXSnNhWE5vWldRZ0lD
        QWdJQ0FnSUNBZ0lDQWdQU0IwY25WbENuMEs=
    import: !!binary |
        Q2dwQlVFa2dUV0Z1WVdkbGJXVnVkQ0JRY205a2RXTjBjeUJqWVc0Z1ltVWdhVzF3YjNKMFpXUWdk
        WE5wYm1jZ2RHaGxJR0J5WlhOdmRYSmpaU0JwWkdBc0lHVXVaeTRLQ2c9PQ==
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdllYQnBYMjFoYm1GblpXMWxiblJmY0hKdlpIVmpkQzVvZEcxc0xtMWhjbXRrYjNk
        dQ==
