azurerm_iothub_dps_certificate:
    status: ASSESS
    subcategory: IoT Hub
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_iothub_dps_certificate'
    description: Manages an IoT Device Provisioning Service Certificate.
    arguments:
        name:
            description: Specifies the name of the Iot Device Provisioning Service
                Certificate resource. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group under which the Iot Device
                Provisioning Service Certificate resource has to be created. Changing
                this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        iot_dps_name:
            description: The name of the IoT Device Provisioning Service that this
                certificate will be attached to. Changing this forces a new resource
                to be created.
            required: false
            policy: ''
            notes: ''
        certificate_content:
            description: The Base-64 representation of the X509 leaf certificate .cer
                file or just a .pem file content.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the IoTHub Device Provisioning Service Certificate.
    timeouts:
        create:
            description: Used when creating the IotHub Device Provisioning Service
                Certificate.
            required: false
            timeout: 30
        update:
            description: Used when updating the IotHub Device Provisioning Service
                Certificate.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the IotHub Device Provisioning Service
                Certificate.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the IotHub Device Provisioning Service
                Certificate.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbkpsYzI5MWNtTmxSM0p2ZFhBeElnb2dJR3h2WTJGMGFX
        OXVJRDBnSWxkbGMzUWdWVk1pQ24wS0NuSmxjMjkxY21ObElDSmhlblZ5WlhKdFgybHZkR2gxWWw5
        a2NITWlJQ0psZUdGdGNHeGxJaUI3Q2lBZ2JtRnRaU0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQTlJQ0ps
        ZUdGdGNHeGxJZ29nSUhKbGMyOTFjbU5sWDJkeWIzVndYMjVoYldVZ1BTQmhlblZ5WlhKdFgzSmxj
        MjkxY21ObFgyZHliM1Z3TG1WNFlXMXdiR1V1Ym1GdFpRb2dJR3h2WTJGMGFXOXVJQ0FnSUNBZ0lD
        QWdJQ0FnUFNCaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndMbVY0WVcxd2JHVXViRzlqWVhS
        cGIyNEtDaUFnYzJ0MUlIc0tJQ0FnSUc1aGJXVWdJQ0FnSUQwZ0lsTXhJZ29nSUNBZ1kyRndZV05w
        ZEhrZ1BTQWlNU0lLSUNCOUNuMEtDbkpsYzI5MWNtTmxJQ0poZW5WeVpYSnRYMmx2ZEdoMVlsOWtj
        SE5mWTJWeWRHbG1hV05oZEdVaUlDSmxlR0Z0Y0d4bElpQjdDaUFnYm1GdFpTQWdJQ0FnSUNBZ0lD
        QWdJQ0FnSUNBOUlDSmxlR0Z0Y0d4bElnb2dJSEpsYzI5MWNtTmxYMmR5YjNWd1gyNWhiV1VnUFNC
        aGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndMbVY0WVcxd2JHVXVibUZ0WlFvZ0lHbHZkRjlr
        Y0hOZmJtRnRaU0FnSUNBZ0lDQWdQU0JoZW5WeVpYSnRYMmx2ZEdoMVlsOWtjSE11WlhoaGJYQnNa
        UzV1WVcxbENnb2dJR05sY25ScFptbGpZWFJsWDJOdmJuUmxiblFnUFNCbWFXeGxZbUZ6WlRZMEtD
        SmxlR0Z0Y0d4bExtTmxjaUlwQ24wSw==
    import: !!binary |
        Q2dwSmIxUklkV0lnUkdWMmFXTmxJRkJ5YjNacGMybHZibWx1WnlCVFpYSjJhV05sSUVObGNuUnBa
        bWxqWVhSbGN5QmpZVzRnWW1VZ2FXMXdiM0owWldRZ2RYTnBibWNnZEdobElHQnlaWE52ZFhKalpT
        QnBaR0FzSUdVdVp5NEtDZz09
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmFXOTBhSFZpWDJSd2MxOWpaWEowYVdacFkyRjBaUzVvZEcxc0xtMWhjbXRrYjNk
        dQ==
