azurerm_automation_credential:
    status: ASSESS
    subcategory: Automation
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_automation_credential'
    description: Manages a Automation Credential.
    arguments:
        name:
            description: Specifies the name of the Credential. Changing this forces
                a new resource to be created.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group in which the Credential is
                created. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        automation_account_name:
            description: The name of the automation account in which the Credential
                is created. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        username:
            description: The username associated with this Automation Credential.
            required: true
            policy: ''
            notes: ''
        password:
            description: The password associated with this Automation Credential.
            required: true
            policy: ''
            notes: ''
        description:
            description: The description associated with this Automation Credential.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the Automation Credential.
    timeouts:
        create:
            description: Used when creating the Automation Credential.
            required: false
            timeout: 30
        update:
            description: Used when updating the Automation Credential.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Automation Credential.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Automation Credential.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbkpsYzI5MWNtTmxSM0p2ZFhBeElnb2dJR3h2WTJGMGFX
        OXVJRDBnSWxkbGMzUWdSWFZ5YjNCbElncDlDZ3B5WlhOdmRYSmpaU0FpWVhwMWNtVnliVjloZFhS
        dmJXRjBhVzl1WDJGalkyOTFiblFpSUNKbGVHRnRjR3hsSWlCN0NpQWdibUZ0WlNBZ0lDQWdJQ0Fn
        SUNBZ0lDQWdJQ0E5SUNKaFkyTnZkVzUwTVNJS0lDQnNiMk5oZEdsdmJpQWdJQ0FnSUNBZ0lDQWdJ
        RDBnWVhwMWNtVnliVjl5WlhOdmRYSmpaVjluY205MWNDNWxlR0Z0Y0d4bExteHZZMkYwYVc5dUNp
        QWdjbVZ6YjNWeVkyVmZaM0p2ZFhCZmJtRnRaU0E5SUdGNmRYSmxjbTFmY21WemIzVnlZMlZmWjNK
        dmRYQXVaWGhoYlhCc1pTNXVZVzFsQ2dvZ0lITnJkU0I3Q2lBZ0lDQnVZVzFsSUQwZ0lrSmhjMmxq
        SWdvZ0lIMEtmUW9LY21WemIzVnlZMlVnSW1GNmRYSmxjbTFmWVhWMGIyMWhkR2x2Ymw5amNtVmta
        VzUwYVdGc0lpQWlaWGhoYlhCc1pTSWdld29nSUc1aGJXVWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lD
        QWdJRDBnSW1OeVpXUmxiblJwWVd3eElnb2dJSEpsYzI5MWNtTmxYMmR5YjNWd1gyNWhiV1VnSUNB
        Z0lEMGdZWHAxY21WeWJWOXlaWE52ZFhKalpWOW5jbTkxY0M1bGVHRnRjR3hsTG01aGJXVUtJQ0Jo
        ZFhSdmJXRjBhVzl1WDJGalkyOTFiblJmYm1GdFpTQTlJR0Y2ZFhKbGNtMWZZWFYwYjIxaGRHbHZi
        bDloWTJOdmRXNTBMbVY0WVcxd2JHVXVibUZ0WlFvZ0lIVnpaWEp1WVcxbElDQWdJQ0FnSUNBZ0lD
        QWdJQ0FnSUQwZ0ltVjRZVzF3YkdWZmRYTmxjaUlLSUNCd1lYTnpkMjl5WkNBZ0lDQWdJQ0FnSUNB
        Z0lDQWdJQ0E5SUNKbGVHRnRjR3hsWDNCM1pDSUtJQ0JrWlhOamNtbHdkR2x2YmlBZ0lDQWdJQ0Fn
        SUNBZ0lDQTlJQ0pVYUdseklHbHpJR0Z1SUdWNFlXMXdiR1VnWTNKbFpHVnVkR2xoYkNJS2ZRbz0=
    import: !!binary |
        Q2dwQmRYUnZiV0YwYVc5dUlFTnlaV1JsYm5ScFlXeHpJR05oYmlCaVpTQnBiWEJ2Y25SbFpDQjFj
        Mmx1WnlCMGFHVWdZSEpsYzI5MWNtTmxJR2xrWUN3Z1pTNW5MZ29L
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdllYVjBiMjFoZEdsdmJsOWpjbVZrWlc1MGFXRnNMbWgwYld3dWJXRnlhMlJ2ZDI0
        PQ==
