azurerm_mariadb_server:
    status: ASSESS
    subcategory: Database
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_mariadb_server'
    description: Manages a MariaDB Server.
    arguments:
        name:
            description: Specifies the name of the MariaDB Server. Changing this forces
                a new resource to be created.
            required: false
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group in which to create the MariaDB
                Server. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        location:
            description: Specifies the supported Azure location where the resource
                exists. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        sku_name:
            description: Specifies the SKU Name for this MariaDB Server. The name
                of the SKU, follows the `tier` + `family` + `cores` pattern (e.g.
                `B_Gen4_1`, `GP_Gen5_8`). For more information see the [product documentation](https://docs.microsoft.com/en-us/rest/api/mariadb/servers/create#sku).
            required: false
            policy: ''
            notes: ''
        storage_profile:
            description: A `storage_profile` block as defined below.
            required: false
            policy: ''
            notes: ''
        administrator_login:
            description: The Administrator Login for the MariaDB Server. Changing
                this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        administrator_login_password:
            description: The Password associated with the `administrator_login` for
                the MariaDB Server.
            required: false
            policy: ''
            notes: ''
        version:
            description: Specifies the version of MariaDB to use. Possible values
                are `10.2` and `10.3`. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        ssl_enforcement:
            description: Specifies if SSL should be enforced on connections. Possible
                values are `Enabled` and `Disabled`.
            required: false
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
        storage_mb:
            description: Max storage allowed for a server. Possible values are between
                `5120` MB (5GB
            required: false
            policy: ''
            notes: ''
        backup_retention_days:
            description: Backup retention days for the server, supported values are
                between `7` and `35` days.
            required: false
            policy: ''
            notes: ''
        geo_redundant_backup:
            description: Enable Geo-redundant or not for server backup. Valid values
                for this property are `Enabled` or `Disabled`. Changing this forces
                a new resource to be created.
            required: false
            policy: ''
            notes:
            - '-> '
            - ' Geo Redundant Backups cannot be configured when using the `Basic`
                tier, and is only allowed during server create.'
        auto_grow:
            description: Defines whether autogrow is enabled or disabled for the storage.
                Valid values are `Enabled` or `Disabled`.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the MariaDB Server.
        fqdn:
            description: The FQDN of the MariaDB Server.
    timeouts:
        create:
            description: Used when creating the MariaDB Server.
            required: false
            timeout: 60
        update:
            description: Used when updating the MariaDB Server.
            required: false
            timeout: 60
        read:
            description: Used when retrieving the MariaDB Server.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the MariaDB Server.
            required: false
            timeout: 60
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbUZ3YVMxeVp5MXdjbThpQ2lBZ2JHOWpZWFJwYjI0Z1BT
        QWlWMlZ6ZENCRmRYSnZjR1VpQ24wS0NuSmxjMjkxY21ObElDSmhlblZ5WlhKdFgyMWhjbWxoWkdK
        ZmMyVnlkbVZ5SWlBaVpYaGhiWEJzWlNJZ2V3b2dJRzVoYldVZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0Fn
        UFNBaWJXRnlhV0ZrWWkxelpYSjJaWEl0TVNJS0lDQnNiMk5oZEdsdmJpQWdJQ0FnSUNBZ0lDQWdJ
        RDBnSWlSN1lYcDFjbVZ5YlY5eVpYTnZkWEpqWlY5bmNtOTFjQzVsZUdGdGNHeGxMbXh2WTJGMGFX
        OXVmU0lLSUNCeVpYTnZkWEpqWlY5bmNtOTFjRjl1WVcxbElEMGdJaVI3WVhwMWNtVnliVjl5WlhO
        dmRYSmpaVjluY205MWNDNWxlR0Z0Y0d4bExtNWhiV1Y5SWdvS0lDQnphM1ZmYm1GdFpTQTlJQ0pD
        WDBkbGJqVmZNaUlLQ2lBZ2MzUnZjbUZuWlY5d2NtOW1hV3hsSUhzS0lDQWdJSE4wYjNKaFoyVmZi
        V0lnSUNBZ0lDQWdJQ0FnSUNBOUlEVXhNakFLSUNBZ0lHSmhZMnQxY0Y5eVpYUmxiblJwYjI1ZlpH
        RjVjeUE5SURjS0lDQWdJR2RsYjE5eVpXUjFibVJoYm5SZlltRmphM1Z3SUNBOUlDSkVhWE5oWW14
        bFpDSUtJQ0FnSUdGMWRHOWZaM0p2ZHlBZ0lDQWdJQ0FnSUNBZ0lDQTlJQ0pFYVhOaFlteGxaQ0lL
        SUNCOUNnb2dJR0ZrYldsdWFYTjBjbUYwYjNKZmJHOW5hVzRnSUNBZ0lDQWdJQ0FnUFNBaWJXRnlh
        V0ZrWW1Ga2JXbHVJZ29nSUdGa2JXbHVhWE4wY21GMGIzSmZiRzluYVc1ZmNHRnpjM2R2Y21RZ1BT
        QWlTRUJUYURGRGIxSXpJU0lLSUNCMlpYSnphVzl1SUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNB
        Z0lEMGdJakV3TGpJaUNpQWdjM05zWDJWdVptOXlZMlZ0Wlc1MElDQWdJQ0FnSUNBZ0lDQWdJQ0E5
        SUNKRmJtRmliR1ZrSWdwOUNnPT0=
    import: !!binary |
        Q2dwTllYSnBZVVJDSUZObGNuWmxjaWR6SUdOaGJpQmlaU0JwYlhCdmNuUmxaQ0IxYzJsdVp5QjBh
        R1VnWUhKbGMyOTFjbU5sSUdsa1lDd2daUzVuTGdvSw==
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmJXRnlhV0ZrWWw5elpYSjJaWEl1YUhSdGJDNXRZWEpyWkc5M2JnPT0=
