azurerm_role_assignment:
    status: ASSESS
    subcategory: Authorization
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_role_assignment'
    description: Assigns a given Principal (User or Application) to a given Role.
    arguments:
        name:
            description: A unique UUID/GUID for this Role Assignment - one will be
                generated if not specified. Changing this forces a new resource to
                be created.
            required: false
            policy: ''
            notes: ''
        scope:
            description: The scope at which the Role Assignment applies to, such as
                `/subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333`, `/subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333/resourceGroups/myGroup`,
                or `/subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333/resourceGroups/myGroup/providers/Microsoft.Compute/virtualMachines/myVM`,
                or `/providers/Microsoft.Management/managementGroups/myMG`. Changing
                this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        role_definition_id:
            description: The Scoped-ID of the Role Definition. Changing this forces
                a new resource to be created. Conflicts with `role_definition_name`.
            required: false
            policy: ''
            notes: ''
        role_definition_name:
            description: The name of a built-in Role. Changing this forces a new resource
                to be created. Conflicts with `role_definition_id`.
            required: false
            policy: ''
            notes: ''
        principal_id:
            description: The ID of the Principal (User, Group, Service Principal,
                or Application
            required: false
            policy: ''
            notes: ''
        skip_service_principal_aad_check:
            description: If the `principal_id` is a newly provisioned `Service Principal`
                set this value to `true` to skip the `Azure Active Directory` check
                which may fail due to replication lag. This argument is only valid
                if the `principal_id` is a `Service Principal` identity. If it is
                not a `Service Principal` identity it will cause the role assignment
                to fail. Defaults to `false`.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The Role Assignment ID.
        principal_type:
            description: The type of the `principal_id`, e.g. User, Group, Service
                Principal, Application, etc.
    timeouts:
        create:
            description: Used when creating the Role Assignment.
            required: false
            timeout: 30
        update:
            description: Used when updating the Role Assignment.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Role Assignment.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Role Assignment.
            required: false
            timeout: 30
    usage: !!binary |
        Q21SaGRHRWdJbUY2ZFhKbGNtMWZjM1ZpYzJOeWFYQjBhVzl1SWlBaWNISnBiV0Z5ZVNJZ2V3cDlD
        Z3BrWVhSaElDSmhlblZ5WlhKdFgyTnNhV1Z1ZEY5amIyNW1hV2NpSUNKbGVHRnRjR3hsSWlCN0Nu
        MEtDbkpsYzI5MWNtTmxJQ0poZW5WeVpYSnRYM0p2YkdWZllYTnphV2R1YldWdWRDSWdJbVY0WVcx
        d2JHVWlJSHNLSUNCelkyOXdaU0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQTlJR1JoZEdFdVlYcDFjbVZ5
        YlY5emRXSnpZM0pwY0hScGIyNHVjSEpwYldGeWVTNXBaQW9nSUhKdmJHVmZaR1ZtYVc1cGRHbHZi
        bDl1WVcxbElEMGdJbEpsWVdSbGNpSUtJQ0J3Y21sdVkybHdZV3hmYVdRZ0lDQWdJQ0FnSUNBOUlH
        UmhkR0V1WVhwMWNtVnliVjlqYkdsbGJuUmZZMjl1Wm1sbkxtVjRZVzF3YkdVdWIySnFaV04wWDJs
        a0NuMEs=
    import: !!binary |
        Q2dwU2IyeGxJRUZ6YzJsbmJtMWxiblJ6SUdOaGJpQmlaU0JwYlhCdmNuUmxaQ0IxYzJsdVp5QjBh
        R1VnWUhKbGMyOTFjbU5sSUdsa1lDd2daUzVuTGdvSw==
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmNtOXNaVjloYzNOcFoyNXRaVzUwTG1oMGJXd3ViV0Z5YTJSdmQyND0=
