azurerm_netapp_snapshot:
    status: HOLD
    subcategory: NetApp
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_netapp_snapshot'
    description: Manages a NetApp Snapshot.
    arguments:
        name:
            description: The name of the NetApp Snapshot. Changing this forces a new
                resource to be created.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group where the NetApp Snapshot
                should be created. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        account_name:
            description: The name of the NetApp account in which the NetApp Pool should
                be created. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        pool_name:
            description: The name of the NetApp pool in which the NetApp Volume should
                be created. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        volume_name:
            description: The name of the NetApp volume in which the NetApp Snapshot
                should be created. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        location:
            description: Specifies the supported Azure location where the resource
                exists. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the NetApp Snapshot.
    timeouts:
        create:
            description: Used when creating the NetApp Snapshot.
            required: false
            timeout: 30
        update:
            description: Used when updating the NetApp Snapshot.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the NetApp Snapshot.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the NetApp Snapshot.
            required: false
            timeout: 30
