azurerm_express_route_circuit_authorization:
    status: ASSESS
    subcategory: Network
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_express_route_circuit_authorization'
    description: Manages an ExpressRoute Circuit Authorization.
    arguments:
        name:
            description: The name of the ExpressRoute circuit. Changing this forces
                a
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group in which to
            required: true
            policy: ''
            notes: ''
        express_route_circuit_name:
            description: The name of the Express Route Circuit in which to create
                the Authorization.
            required: true
            policy: ''
            notes: ''
    attributes:
        id:
            description: The Resource ID of the ExpressRoute Circuit Authorization.
        authorization_key:
            description: The Authorization Key.
        authorization_use_status:
            description: The authorization use status.
    timeouts:
        create:
            description: Used when creating the ExpressRoute Circuit Authorization.
            required: false
            timeout: 30
        update:
            description: Used when updating the ExpressRoute Circuit Authorization.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the ExpressRoute Circuit Authorization.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the ExpressRoute Circuit Authorization.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbVY0Y0hKMFZHVnpkQ0lLSUNCc2IyTmhkR2x2YmlBOUlD
        SlhaWE4wSUZWVElncDlDZ3B5WlhOdmRYSmpaU0FpWVhwMWNtVnliVjlsZUhCeVpYTnpYM0p2ZFhS
        bFgyTnBjbU4xYVhRaUlDSmxlR0Z0Y0d4bElpQjdDaUFnYm1GdFpTQWdJQ0FnSUNBZ0lDQWdJQ0Fn
        SUNBZ0lEMGdJbVY0Y0hKbGMzTlNiM1YwWlRFaUNpQWdjbVZ6YjNWeVkyVmZaM0p2ZFhCZmJtRnRa
        U0FnSUQwZ1lYcDFjbVZ5YlY5eVpYTnZkWEpqWlY5bmNtOTFjQzVsZUdGdGNHeGxMbTVoYldVS0lD
        QnNiMk5oZEdsdmJpQWdJQ0FnSUNBZ0lDQWdJQ0FnUFNCaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJk
        eWIzVndMbVY0WVcxd2JHVXViRzlqWVhScGIyNEtJQ0J6WlhKMmFXTmxYM0J5YjNacFpHVnlYMjVo
        YldVZ1BTQWlSWEYxYVc1cGVDSUtJQ0J3WldWeWFXNW5YMnh2WTJGMGFXOXVJQ0FnSUNBZ1BTQWlV
        MmxzYVdOdmJpQldZV3hzWlhraUNpQWdZbUZ1WkhkcFpIUm9YMmx1WDIxaWNITWdJQ0FnSUQwZ05U
        QUtDaUFnYzJ0MUlIc0tJQ0FnSUhScFpYSWdJQ0E5SUNKVGRHRnVaR0Z5WkNJS0lDQWdJR1poYlds
        c2VTQTlJQ0pOWlhSbGNtVmtSR0YwWVNJS0lDQjlDZ29nSUdGc2JHOTNYMk5zWVhOemFXTmZiM0Js
        Y21GMGFXOXVjeUE5SUdaaGJITmxDZ29nSUhSaFozTWdQU0I3Q2lBZ0lDQmxiblpwY205dWJXVnVk
        Q0E5SUNKUWNtOWtkV04wYVc5dUlnb2dJSDBLZlFvS2NtVnpiM1Z5WTJVZ0ltRjZkWEpsY20xZlpY
        aHdjbVZ6YzE5eWIzVjBaVjlqYVhKamRXbDBYMkYxZEdodmNtbDZZWFJwYjI0aUlDSmxlR0Z0Y0d4
        bElpQjdDaUFnYm1GdFpTQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnUFNBaVpYaGhiWEJz
        WlVWU1EwRjFkR2dpQ2lBZ1pYaHdjbVZ6YzE5eWIzVjBaVjlqYVhKamRXbDBYMjVoYldVZ1BTQmhl
        blZ5WlhKdFgyVjRjSEpsYzNOZmNtOTFkR1ZmWTJseVkzVnBkQzVsZUdGdGNHeGxMbTVoYldVS0lD
        QnlaWE52ZFhKalpWOW5jbTkxY0Y5dVlXMWxJQ0FnSUNBZ0lDQTlJR0Y2ZFhKbGNtMWZjbVZ6YjNW
        eVkyVmZaM0p2ZFhBdVpYaGhiWEJzWlM1dVlXMWxDbjBL
    import: !!binary |
        Q2dwRmVIQnlaWE56VW05MWRHVWdRMmx5WTNWcGRDQkJkWFJvYjNKcGVtRjBhVzl1Y3lCallXNGdZ
        bVVnYVcxd2IzSjBaV1FnZFhOcGJtY2dkR2hsSUdCeVpYTnZkWEpqWlNCcFpHQXNJR1V1Wnk0S0Nn
        PT0=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdlpYaHdjbVZ6YzE5eWIzVjBaVjlqYVhKamRXbDBYMkYxZEdodmNtbDZZWFJwYjI0
        dWFIUnRiQzV0WVhKclpHOTNiZz09
