azurerm_log_analytics_datasource_windows_event:
    status: ASSESS
    subcategory: Log Analytics
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_log_analytics_datasource_windows_event'
    description: Manages a Log Analytics Windows Event DataSource.
    arguments: {}
    attributes: {}
    timeouts: {}
