azurerm_monitor_diagnostic_setting:
    status: HOLD
    subcategory: Monitor
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_monitor_diagnostic_setting'
    description: Manages a Diagnostic Setting for an existing Resource.
    arguments:
        name:
            description: Specifies the name of the Diagnostic Setting. Changing this
                forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        target_resource_id:
            description: The ID of an existing Resource on which to configure Diagnostic
                Settings. Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        eventhub_name:
            description: Specifies the name of the Event Hub where Diagnostics Data
                should be sent. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: If this isn't specified then the default Event Hub will be used.
        eventhub_authorization_rule_id:
            description: Specifies the ID of an Event Hub Namespace Authorization
                Rule used to send Diagnostics Data. Changing this forces a new resource
                to be created.
            required: false
            policy: ''
            notes: One of `eventhub_authorization_rule_id`, `log_analytics_workspace_id`
                and `storage_account_id` must be specified.
        log:
            description: One or more `log` blocks as defined below.
            required: false
            policy: ''
            notes: At least one `log` or `metric` block must be specified.
        log_analytics_workspace_id:
            description: Specifies the ID of a Log Analytics Workspace where Diagnostics
                Data should be sent. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: One of `eventhub_authorization_rule_id`, `log_analytics_workspace_id`
                and `storage_account_id` must be specified.
        metric:
            description: One or more `metric` blocks as defined below.
            required: false
            policy: ''
            notes: At least one `log` or `metric` block must be specified.
        storage_account_id:
            description: With this parameter you can specify a storage account which
                should be used to send the logs to. Parameter must be a valid Azure
                Resource ID. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: One of `eventhub_authorization_rule_id`, `log_analytics_workspace_id`
                and `storage_account_id` must be specified.
        log_analytics_destination_type:
            description: When set to 'Dedicated' logs sent to a Log Analytics workspace
                will go into resource specific tables, instead of the legacy AzureDiagnostics
                table.
            required: false
            policy: ''
            notes: This setting will only have an effect if a `log_analytics_workspace_id`
                is provided, and the resource is available for resource-specific logs.  As
                of July 2019, this only includes Azure Data Factory. Please [see the
                documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-logs-stream-log-store#azure-diagnostics-vs-resource-specific)
                for more information.
        category:
            description: The name of a Diagnostic Metric Category for this Resource.
            required: true
            policy: ''
            notes: The Metric Categories available vary depending on the Resource
                being used. You may wish to use [the `azurerm_monitor_diagnostic_categories`
                Data Source](../d/monitor_diagnostic_categories.html) to identify
                which categories are available for a given Resource.
        retention_policy:
            description: A `retention_policy` block as defined below.
            required: true
            policy: ''
            notes: ''
        enabled:
            description: Is this Retention Policy enabled?
            required: true
            policy: ''
            notes: ''
        days:
            description: The number of days for which this Retention Policy should
                apply.
            required: false
            policy: ''
            notes: Setting this to `0` will retain the events indefinitely.
    attributes:
        id:
            description: The ID of the Diagnostic Setting.
    timeouts:
        create:
            description: Used when creating the Diagnostics Setting.
            required: false
            timeout: 30
        update:
            description: Used when updating the Diagnostics Setting.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Diagnostics Setting.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Diagnostics Setting.
            required: false
            timeout: 60
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbVY0WVcxd2JHVXRjbVZ6YjNWeVkyVnpJZ29nSUd4dlky
        RjBhVzl1SUQwZ0lsZGxjM1FnUlhWeWIzQmxJZ3A5Q2dwa1lYUmhJQ0poZW5WeVpYSnRYM04wYjNK
        aFoyVmZZV05qYjNWdWRDSWdJbVY0WVcxd2JHVWlJSHNLSUNCdVlXMWxJQ0FnSUNBZ0lDQWdJQ0Fn
        SUNBZ0lEMGdJbVY0WVcxd2JHVnpkRzl5WVdOaklnb2dJSEpsYzI5MWNtTmxYMmR5YjNWd1gyNWhi
        V1VnUFNBaUpIdGhlblZ5WlhKdFgzSmxjMjkxY21ObFgyZHliM1Z3TG1WNFlXMXdiR1V1Ym1GdFpY
        MGlDbjBLQ21SaGRHRWdJbUY2ZFhKbGNtMWZhMlY1WDNaaGRXeDBJaUFpWlhoaGJYQnNaU0lnZXdv
        Z0lHNWhiV1VnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdQU0FpWlhoaGJYQnNaUzEyWVhWc2RDSUtJQ0J5
        WlhOdmRYSmpaVjluY205MWNGOXVZVzFsSUQwZ0lpUjdZWHAxY21WeWJWOXlaWE52ZFhKalpWOW5j
        bTkxY0M1bGVHRnRjR3hsTG01aGJXVjlJZ3A5Q2dweVpYTnZkWEpqWlNBaVlYcDFjbVZ5YlY5dGIy
        NXBkRzl5WDJScFlXZHViM04wYVdOZmMyVjBkR2x1WnlJZ0ltVjRZVzF3YkdVaUlIc0tJQ0J1WVcx
        bElDQWdJQ0FnSUNBZ0lDQWdJQ0FnUFNBaVpYaGhiWEJzWlNJS0lDQjBZWEpuWlhSZmNtVnpiM1Z5
        WTJWZmFXUWdQU0FpSkh0a1lYUmhMbUY2ZFhKbGNtMWZhMlY1WDNaaGRXeDBMbVY0WVcxd2JHVXVh
        V1I5SWdvZ0lITjBiM0poWjJWZllXTmpiM1Z1ZEY5cFpDQTlJQ0lrZTJSaGRHRXVZWHAxY21WeWJW
        OXpkRzl5WVdkbFgyRmpZMjkxYm5RdVpYaGhiWEJzWlM1cFpIMGlDZ29nSUd4dlp5QjdDaUFnSUNC
        allYUmxaMjl5ZVNBOUlDSkJkV1JwZEVWMlpXNTBJZ29nSUNBZ1pXNWhZbXhsWkNBZ1BTQm1ZV3h6
        WlFvS0lDQWdJSEpsZEdWdWRHbHZibDl3YjJ4cFkza2dld29nSUNBZ0lDQmxibUZpYkdWa0lEMGda
        bUZzYzJVS0lDQWdJSDBLSUNCOUNnb2dJRzFsZEhKcFl5QjdDaUFnSUNCallYUmxaMjl5ZVNBOUlD
        SkJiR3hOWlhSeWFXTnpJZ29LSUNBZ0lISmxkR1Z1ZEdsdmJsOXdiMnhwWTNrZ2V3b2dJQ0FnSUNC
        bGJtRmliR1ZrSUQwZ1ptRnNjMlVLSUNBZ0lIMEtJQ0I5Q24wSw==
    import: !!binary |
        Q2dwRWFXRm5ibTl6ZEdsaklGTmxkSFJwYm1keklHTmhiaUJpWlNCcGJYQnZjblJsWkNCMWMybHVa
        eUIwYUdVZ1lISmxjMjkxY21ObElHbGtZQ3dnWlM1bkxnb0s=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmJXOXVhWFJ2Y2w5a2FXRm5ibTl6ZEdsalgzTmxkSFJwYm1jdWFIUnRiQzV0WVhK
        clpHOTNiZz09
