azurerm_subnet:
    status: ASSESS
    subcategory: Network
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_subnet'
    description: Manages a subnet. Subnets represent network segments within the IP
        space defined by the virtual network.
    arguments:
        name:
            description: The name of service to delegate to. Possible values include
                `Microsoft.BareMetal/AzureVMware`, `Microsoft.BareMetal/CrayServers`,
                `Microsoft.Batch/batchAccounts`, `Microsoft.ContainerInstance/containerGroups`,
                `Microsoft.Databricks/workspaces`, `Microsoft.DBforPostgreSQL/serversv2`,
                `Microsoft.HardwareSecurityModules/dedicatedHSMs`, `Microsoft.Logic/integrationServiceEnvironments`,
                `Microsoft.Netapp/volumes`, `Microsoft.ServiceFabricMesh/networks`,
                `Microsoft.Sql/managedInstances`, `Microsoft.Sql/servers`, `Microsoft.StreamAnalytics/streamingJobs`,
                `Microsoft.Web/hostingEnvironments` and `Microsoft.Web/serverFarms`.
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group in which to create the subnet.
                Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        virtual_network_name:
            description: The name of the virtual network to which to attach the subnet.
                Changing this forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        address_prefix:
            description: The address prefix to use for the subnet.
            required: true
            policy: ''
            notes: ''
        delegation:
            description: One or more `delegation` blocks as defined below.
            required: false
            policy: ''
            notes: ''
        enforce_private_link_endpoint_network_policies:
            description: Enable or Disable network policies for the private link endpoint
                on the subnet. Default value is `false`. Conflicts with enforce_private_link_service_network_policies.
            required: false
            policy: ''
            notes: Network policies, like network security groups (NSG), are not supported
                for Private Link Endpoints or Private Link Services. In order to deploy
                a Private Link Endpoint on a given subnet, you must set the `enforce_private_link_endpoint_network_policies`
                attribute to `true`. This setting is only applicable for the Private
                Link Endpoint, for all other resources in the subnet access is controlled
                based via the Network Security Group which can be configured using
                the `azurerm_subnet_network_security_group_association` resource.
        enforce_private_link_service_network_policies:
            description: Enable or Disable network policies for the private link service
                on the subnet. Default valule is `false`. Conflicts with `enforce_private_link_endpoint_network_policies`.
            required: false
            policy: ''
            notes: In order to deploy a Private Link Service on a given subnet, you
                must set the `enforce_private_link_service_network_policies` attribute
                to `true`. This setting is only applicable for the Private Link Service,
                for all other resources in the subnet access is controlled based on
                the Network Security Group which can be configured using the `azurerm_subnet_network_security_group_association`
                resource.
        service_endpoints:
            description: 'The list of Service endpoints to associate with the subnet.
                Possible values include: `Microsoft.AzureActiveDirectory`, `Microsoft.AzureCosmosDB`,
                `Microsoft.ContainerRegistry`, `Microsoft.EventHub`, `Microsoft.KeyVault`,
                `Microsoft.ServiceBus`, `Microsoft.Sql`, `Microsoft.Storage` and `Microsoft.Web`.'
            required: false
            policy: ''
            notes: ''
        service_delegation:
            description: A `service_delegation` block as defined below.
            required: true
            policy: ''
            notes: Delegating to services may not be available in all regions. Check
                that the service you are delegating to is available in your region
                using the [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/network/vnet/subnet?view=azure-cli-latest#az-network-vnet-subnet-list-available-delegations).
                Also, `actions` is specific to each service type. The exact list of
                `actions` needs to be retrieved using the aforementioned [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/network/vnet/subnet?view=azure-cli-latest#az-network-vnet-subnet-list-available-delegations).
        actions:
            description: A list of Actions which should be delegated. This list is
                specific to the service to delegate to. Possible values include `Microsoft.Network/networkinterfaces/*`,
                `Microsoft.Network/virtualNetworks/subnets/action`, `Microsoft.Network/virtualNetworks/subnets/join/action`,
                `Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action`
                and `Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action`.
            required: false
            policy: ''
            notes: Azure may add default actions depending on the service delegation
                name and they can't be changed.
    attributes:
        id:
            description: The subnet ID.
        name:
            description: The name of the subnet.
        resource_group_name:
            description: The name of the resource group in which the subnet is created
                in.
        virtual_network_name:
            description: The name of the virtual network in which the subnet is created
                in
        address_prefix:
            description: The address prefix for the subnet
    timeouts:
        create:
            description: Used when creating the Subnet.
            required: false
            timeout: 30
        update:
            description: Used when updating the Subnet.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Subnet.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Subnet.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbUZqWTJWd2RHRnVZMlZVWlhOMFVtVnpiM1Z5WTJWSGNt
        OTFjREVpQ2lBZ2JHOWpZWFJwYjI0Z1BTQWlWMlZ6ZENCVlV5SUtmUW9LY21WemIzVnlZMlVnSW1G
        NmRYSmxjbTFmZG1seWRIVmhiRjl1WlhSM2IzSnJJaUFpWlhoaGJYQnNaU0lnZXdvZ0lHNWhiV1Vn
        SUNBZ0lDQWdJQ0FnSUNBZ0lDQWdQU0FpWVdOalpYQjBZVzVqWlZSbGMzUldhWEowZFdGc1RtVjBk
        Mjl5YXpFaUNpQWdZV1JrY21WemMxOXpjR0ZqWlNBZ0lDQWdJQ0E5SUZzaU1UQXVNQzR3TGpBdk1U
        WWlYUW9nSUd4dlkyRjBhVzl1SUNBZ0lDQWdJQ0FnSUNBZ1BTQmhlblZ5WlhKdFgzSmxjMjkxY21O
        bFgyZHliM1Z3TG1WNFlXMXdiR1V1Ykc5allYUnBiMjRLSUNCeVpYTnZkWEpqWlY5bmNtOTFjRjl1
        WVcxbElEMGdZWHAxY21WeWJWOXlaWE52ZFhKalpWOW5jbTkxY0M1bGVHRnRjR3hsTG01aGJXVUtm
        UW9LY21WemIzVnlZMlVnSW1GNmRYSmxjbTFmYzNWaWJtVjBJaUFpWlhoaGJYQnNaU0lnZXdvZ0lH
        NWhiV1VnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJRDBnSW5SbGMzUnpkV0p1WlhRaUNpQWdjbVZ6YjNW
        eVkyVmZaM0p2ZFhCZmJtRnRaU0FnUFNCaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndMbVY0
        WVcxd2JHVXVibUZ0WlFvZ0lIWnBjblIxWVd4ZmJtVjBkMjl5YTE5dVlXMWxJRDBnWVhwMWNtVnli
        VjkyYVhKMGRXRnNYMjVsZEhkdmNtc3VaWGhoYlhCc1pTNXVZVzFsQ2lBZ1lXUmtjbVZ6YzE5d2Nt
        Vm1hWGdnSUNBZ0lDQWdQU0FpTVRBdU1DNHhMakF2TWpRaUNnb2dJR1JsYkdWbllYUnBiMjRnZXdv
        Z0lDQWdibUZ0WlNBOUlDSmhZMk4wWlhOMFpHVnNaV2RoZEdsdmJpSUtDaUFnSUNCelpYSjJhV05s
        WDJSbGJHVm5ZWFJwYjI0Z2V3b2dJQ0FnSUNCdVlXMWxJQ0FnSUQwZ0lrMXBZM0p2YzI5bWRDNURi
        MjUwWVdsdVpYSkpibk4wWVc1alpTOWpiMjUwWVdsdVpYSkhjbTkxY0hNaUNpQWdJQ0FnSUdGamRH
        bHZibk1nUFNCYklrMXBZM0p2YzI5bWRDNU9aWFIzYjNKckwzWnBjblIxWVd4T1pYUjNiM0pyY3k5
        emRXSnVaWFJ6TDJwdmFXNHZZV04wYVc5dUlpd2dJazFwWTNKdmMyOW1kQzVPWlhSM2IzSnJMM1pw
        Y25SMVlXeE9aWFIzYjNKcmN5OXpkV0p1WlhSekwzQnlaWEJoY21WT1pYUjNiM0pyVUc5c2FXTnBa
        WE12WVdOMGFXOXVJbDBLSUNBZ0lIMEtJQ0I5Q24wSw==
    import: !!binary |
        Q2dwVGRXSnVaWFJ6SUdOaGJpQmlaU0JwYlhCdmNuUmxaQ0IxYzJsdVp5QjBhR1VnWUhKbGMyOTFj
        bU5sSUdsa1lDd2daUzVuTGdvSw==
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmMzVmlibVYwTG1oMGJXd3ViV0Z5YTJSdmQyND0=
