azurerm_data_factory_linked_service_mysql:
    status: ASSESS
    subcategory: Data Factory
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_data_factory_linked_service_mysql'
    description: Manages a Linked Service (connection) between MySQL and Azure Data
        Factory.
    arguments:
        name:
            description: Specifies the name of the Data Factory Linked Service MySQL.
                Changing this forces a new resource to be created. Must be globally
                unique. See the [Microsoft documentation](https://docs.microsoft.com/en-us/azure/data-factory/naming-rules
            required: true
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group in which to create the Data
                Factory Linked Service MySQL. Changing this forces a new resource
            required: true
            policy: ''
            notes: ''
        data_factory_name:
            description: The Data Factory name in which to associate the Linked Service
                with. Changing this forces a new resource.
            required: true
            policy: ''
            notes: ''
        connection_string:
            description: The connection string in which to authenticate with MySQL.
            required: true
            policy: ''
            notes: ''
        description:
            description: The description for the Data Factory Linked Service MySQL.
            required: false
            policy: ''
            notes: ''
        integration_runtime_name:
            description: The integration runtime reference to associate with the Data
                Factory Linked Service MySQL.
            required: false
            policy: ''
            notes: ''
        annotations:
            description: List of tags that can be used for describing the Data Factory
                Linked Service MySQL.
            required: false
            policy: ''
            notes: ''
        parameters:
            description: A map of parameters to associate with the Data Factory Linked
                Service MySQL.
            required: false
            policy: ''
            notes: ''
        additional_properties:
            description: A map of additional properties to associate with the Data
                Factory Linked Service MySQL.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the Data Factory MySql Linked Service.
    timeouts:
        create:
            description: Used when creating the Data Factory MySql Linked Service.
            required: false
            timeout: 30
        update:
            description: Used when updating the Data Factory MySql Linked Service.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the Data Factory MySql Linked Service.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the Data Factory MySql Linked Service.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbVY0WVcxd2JHVXRjbVZ6YjNWeVkyVnpJZ29nSUd4dlky
        RjBhVzl1SUQwZ0ltNXZjblJvWlhWeWIzQmxJZ3A5Q2dweVpYTnZkWEpqWlNBaVlYcDFjbVZ5YlY5
        a1lYUmhYMlpoWTNSdmNua2lJQ0psZUdGdGNHeGxJaUI3Q2lBZ2JtRnRaU0FnSUNBZ0lDQWdJQ0Fn
        SUNBZ0lDQTlJQ0psZUdGdGNHeGxJZ29nSUd4dlkyRjBhVzl1SUNBZ0lDQWdJQ0FnSUNBZ1BTQmhl
        blZ5WlhKdFgzSmxjMjkxY21ObFgyZHliM1Z3TG1WNFlXMXdiR1V1Ykc5allYUnBiMjRLSUNCeVpY
        TnZkWEpqWlY5bmNtOTFjRjl1WVcxbElEMGdZWHAxY21WeWJWOXlaWE52ZFhKalpWOW5jbTkxY0M1
        bGVHRnRjR3hsTG01aGJXVUtmUW9LY21WemIzVnlZMlVnSW1GNmRYSmxjbTFmWkdGMFlWOW1ZV04w
        YjNKNVgyeHBibXRsWkY5elpYSjJhV05sWDIxNWMzRnNJaUFpWlhoaGJYQnNaU0lnZXdvZ0lHNWhi
        V1VnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdQU0FpWlhoaGJYQnNaU0lLSUNCeVpYTnZkWEpqWlY5bmNt
        OTFjRjl1WVcxbElEMGdZWHAxY21WeWJWOXlaWE52ZFhKalpWOW5jbTkxY0M1bGVHRnRjR3hsTG01
        aGJXVUtJQ0JrWVhSaFgyWmhZM1J2Y25sZmJtRnRaU0FnSUQwZ1lYcDFjbVZ5YlY5a1lYUmhYMlpo
        WTNSdmNua3VaWGhoYlhCc1pTNXVZVzFsQ2lBZ1kyOXVibVZqZEdsdmJsOXpkSEpwYm1jZ0lDQTlJ
        Q0pUWlhKMlpYSTlkR1Z6ZER0UWIzSjBQVE16TURZN1JHRjBZV0poYzJVOWRHVnpkRHRWYzJWeVBY
        UmxjM1E3VTFOTVRXOWtaVDB4TzFWelpWTjVjM1JsYlZSeWRYTjBVM1J2Y21VOU1EdFFZWE56ZDI5
        eVpEMTBaWE4wSWdwOUNnPT0=
    import: !!binary |
        Q2dwRVlYUmhJRVpoWTNSdmNua2dUWGxUY1d3Z1RHbHVhMlZrSUZObGNuWnBZMlVuY3lCallXNGdZ
        bVVnYVcxd2IzSjBaV1FnZFhOcGJtY2dkR2hsSUdCeVpYTnZkWEpqWlNCcFpHQXNJR1V1Wnk0S0Nn
        PT0=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdlpHRjBZVjltWVdOMGIzSjVYMnhwYm10bFpGOXpaWEoyYVdObFgyMTVjM0ZzTG1o
        MGJXd3ViV0Z5YTJSdmQyND0=
