azurerm_sql_elasticpool:
    status: ASSESS
    subcategory: Database
    layout: azurerm
    page_title: 'Azure Resource Manager: azurerm_sql_elasticpool'
    description: Manages a SQL Elastic Pool.
    arguments:
        name:
            description: The name of the elastic pool. This needs to be globally unique.
                Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        resource_group_name:
            description: The name of the resource group in which to create the elastic
                pool. This must be the same as the resource group of the underlying
                SQL server.
            required: false
            policy: ''
            notes: ''
        location:
            description: Specifies the supported Azure location where the resource
                exists. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        server_name:
            description: The name of the SQL Server on which to create the elastic
                pool. Changing this forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        edition:
            description: The edition of the elastic pool to be created. Valid values
                are `Basic`, `Standard`, and `Premium`. Refer to [Azure SQL Database
                Service Tiers](https://docs.microsoft.com/en-gb/azure/sql-database/sql-database-service-tiers#elastic-pool-service-tiers-and-performance-in-edtus
            required: false
            policy: ''
            notes: ''
        dtu:
            description: The total shared DTU for the elastic pool. Valid values depend
                on the `edition` which has been defined. Refer to [Azure SQL Database
                Service Tiers](https://docs.microsoft.com/en-gb/azure/sql-database/sql-database-service-tiers#elastic-pool-service-tiers-and-performance-in-edtus
            required: false
            policy: ''
            notes: ''
        db_dtu_min:
            description: The minimum DTU which will be guaranteed to all databases
                in the elastic pool to be created.
            required: false
            policy: ''
            notes: ''
        db_dtu_max:
            description: The maximum DTU which will be guaranteed to all databases
                in the elastic pool to be created.
            required: false
            policy: ''
            notes: ''
        pool_size:
            description: The maximum size in MB that all databases in the elastic
                pool can grow to. The maximum size must be consistent with combination
                of `edition` and `dtu` and the limits documented in [Azure SQL Database
                Service Tiers](https://docs.microsoft.com/en-gb/azure/sql-database/sql-database-service-tiers#elastic-pool-service-tiers-and-performance-in-edtus).
                If not defined when creating an elastic pool, the value is set to
                the size implied by `edition` and `dtu`.
            required: false
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The SQL Elastic Pool ID.
        creation_date:
            description: The creation date of the SQL Elastic Pool.
    timeouts:
        create:
            description: Used when creating the SQL Elastic Pool.
            required: false
            timeout: 30
        update:
            description: Used when updating the SQL Elastic Pool.
            required: false
            timeout: 30
        read:
            description: Used when retrieving the SQL Elastic Pool.
            required: false
            timeout: 5
        delete:
            description: Used when deleting the SQL Elastic Pool.
            required: false
            timeout: 30
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGVuVnlaWEp0WDNKbGMyOTFjbU5sWDJkeWIzVndJaUFpWlhoaGJYQnNa
        U0lnZXdvZ0lHNWhiV1VnSUNBZ0lEMGdJbTE1TFhKbGMyOTFjbU5sTFdkeWIzVndJZ29nSUd4dlky
        RjBhVzl1SUQwZ0lsZGxjM1FnVlZNaUNuMEtDbkpsYzI5MWNtTmxJQ0poZW5WeVpYSnRYM054YkY5
        elpYSjJaWElpSUNKbGVHRnRjR3hsSWlCN0NpQWdibUZ0WlNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0Fn
        SUNBZ0lDQWdJQ0E5SUNKdGVTMXpjV3d0YzJWeWRtVnlJaUFqSUU1UFZFVTZJRzVsWldSeklIUnZJ
        R0psSUdkc2IySmhiR3g1SUhWdWFYRjFaUW9nSUhKbGMyOTFjbU5sWDJkeWIzVndYMjVoYldVZ0lD
        QWdJQ0FnSUNBZ1BTQmhlblZ5WlhKdFgzSmxjMjkxY21ObFgyZHliM1Z3TG1WNFlXMXdiR1V1Ym1G
        dFpRb2dJR3h2WTJGMGFXOXVJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnUFNCaGVuVnlaWEp0
        WDNKbGMyOTFjbU5sWDJkeWIzVndMbVY0WVcxd2JHVXViRzlqWVhScGIyNEtJQ0IyWlhKemFXOXVJ
        Q0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUQwZ0lqRXlMakFpQ2lBZ1lXUnRhVzVwYzNSeVlY
        UnZjbDlzYjJkcGJpQWdJQ0FnSUNBZ0lDQTlJQ0kwWkcweGJqRTFOM0kwTnpCeUlnb2dJR0ZrYlds
        dWFYTjBjbUYwYjNKZmJHOW5hVzVmY0dGemMzZHZjbVFnUFNBaU5DMTJNM0o1TFRVelkzSXpOeTF3
        TkRVMWR6QnlaQ0lLZlFvS2NtVnpiM1Z5WTJVZ0ltRjZkWEpsY20xZmMzRnNYMlZzWVhOMGFXTndi
        MjlzSWlBaVpYaGhiWEJzWlNJZ2V3b2dJRzVoYldVZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnUFNBaWRH
        VnpkQ0lLSUNCeVpYTnZkWEpqWlY5bmNtOTFjRjl1WVcxbElEMGdZWHAxY21WeWJWOXlaWE52ZFhK
        alpWOW5jbTkxY0M1bGVHRnRjR3hsTG01aGJXVUtJQ0JzYjJOaGRHbHZiaUFnSUNBZ0lDQWdJQ0Fn
        SUQwZ1lYcDFjbVZ5YlY5eVpYTnZkWEpqWlY5bmNtOTFjQzVsZUdGdGNHeGxMbXh2WTJGMGFXOXVD
        aUFnYzJWeWRtVnlYMjVoYldVZ0lDQWdJQ0FnSUNBOUlHRjZkWEpsY20xZmMzRnNYM05sY25abGNp
        NWxlR0Z0Y0d4bExtNWhiV1VLSUNCbFpHbDBhVzl1SUNBZ0lDQWdJQ0FnSUNBZ0lEMGdJa0poYzJs
        aklnb2dJR1IwZFNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnUFNBMU1Bb2dJR1JpWDJSMGRWOXRhVzRn
        SUNBZ0lDQWdJQ0FnUFNBd0NpQWdaR0pmWkhSMVgyMWhlQ0FnSUNBZ0lDQWdJQ0E5SURVS0lDQndi
        MjlzWDNOcGVtVWdJQ0FnSUNBZ0lDQWdJRDBnTlRBd01BcDlDZz09
    import: !!binary |
        Q2dwVFVVd2dSV3hoYzNScFl5QlFiMjlzSjNNZ1kyRnVJR0psSUdsdGNHOXlkR1ZrSUhWemFXNW5J
        SFJvWlNCZ2NtVnpiM1Z5WTJVZ2FXUmdMQ0JsTG1jdUNnbz0=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjZkWEpsY20wdllteHZZaTl0WVhOMFpYSXZkMlZpYzJsMFpT
        OWtiMk56TDNJdmMzRnNYMlZzWVhOMGFXTndiMjlzTG1oMGJXd3ViV0Z5YTJSdmQyND0=
