kubernetes_job:
    status: ASSESS
    layout: kubernetes
    page_title: 'Kubernetes: kubernetes_job'
    sidebar_current: docs-kubernetes-resource-job
    description: A Job creates one or more Pods and ensures that a specified number
        of them successfully terminate. You can also use a Job to run multiple Pods
        in parallel.
    arguments:
        metadata:
            description: 'Standard resource''s metadata. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
            required: true
            policy: ''
            notes: ''
        spec:
            description: 'Specification of the desired behavior of a job. More info:
                https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status'
            required: true
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
