vault_database_secret_backend_connection:
    status: ASSESS
    layout: vault
    page_title: 'Vault: vault_database_secret_backend_connection resource'
    sidebar_current: docs-vault-resource-database-secret-backend-connection
    description: Configures a database secret backend connection for Vault.
    arguments:
        name:
            description: A unique name to give the database connection.
            required: true
            policy: ''
            notes: ''
        backend:
            description: The unique name of the Vault mount to configure.
            required: true
            policy: ''
            notes: ''
        verify_connection:
            description: Whether the connection should be verified on
            required: false
            policy: ''
            notes: ''
        allowed_roles:
            description: A list of roles that are allowed to use this
            required: false
            policy: ''
            notes: ''
        root_rotation_statements:
            description: A list of database statements to be executed to rotate the
                root user's credentials.
            required: false
            policy: ''
            notes: ''
        data:
            description: A map of sensitive data to pass to the endpoint. Useful for
                templated connection strings.
            required: false
            policy: ''
            notes: ''
        cassandra:
            description: A nested block containing configuration options for Cassandra
                connections.
            required: false
            policy: ''
            notes: ''
        mongodb:
            description: A nested block containing configuration options for MongoDB
                connections.
            required: false
            policy: ''
            notes: ''
        hana:
            description: A nested block containing configuration options for SAP HanaDB
                connections.
            required: false
            policy: ''
            notes: ''
        mssql:
            description: A nested block containing configuration options for MSSQL
                connections.
            required: false
            policy: ''
            notes: ''
        mysql:
            description: A nested block containing configuration options for MySQL
                connections.
            required: false
            policy: ''
            notes: ''
        mysql_rds:
            description: A nested block containing configuration options for RDS MySQL
                connections.
            required: false
            policy: ''
            notes: ''
        mysql_aurora:
            description: A nested block containing configuration options for Aurora
                MySQL connections.
            required: false
            policy: ''
            notes: ''
        mysql_legacy:
            description: A nested block containing configuration options for legacy
                MySQL connections.
            required: false
            policy: ''
            notes: ''
        postgresql:
            description: A nested block containing configuration options for PostgreSQL
                connections.
            required: false
            policy: ''
            notes: ''
        oracle:
            description: A nested block containing configuration options for Oracle
                connections.
            required: false
            policy: ''
            notes: ''
        elasticsearch:
            description: A nested block containing configuration options for Elasticsearch
                connections.
            required: false
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
