vault_identity_group:
    status: ASSESS
    layout: vault
    page_title: 'Vault: vault_identity_group resource'
    sidebar_current: docs-vault-resource-identity-group
    description: Creates an Identity Group for Vault.
    arguments:
        name:
            description: Name of the identity group to create.
            required: false
            policy: ''
            notes: ''
        type:
            description: Type of the group, internal or external. Defaults to `internal`.
            required: false
            policy: ''
            notes: ''
        policies:
            description: A list of policies to apply to the group.
            required: false
            policy: ''
            notes: ''
        metadata:
            description: A Map of additional metadata to associate with the group.
            required: false
            policy: ''
            notes: ''
        member_group_ids:
            description: A list of Group IDs to be assigned as group members.
            required: false
            policy: ''
            notes: ''
        member_entity_ids:
            description: A list of Entity IDs to be assigned as group members. Not
                allowed on `external` groups.
            required: false
            policy: ''
            notes: ''
        external_policies:
            description: '`false` by default. If set to `true`, this resource will
                ignore any policies return from Vault or specified in the resource.
                You can use [`vault_identity_group_policies`](identity_group_policies.html'
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The `id` of the created group.
    timeouts: {}
