vault_generic_secret:
    status: ASSESS
    layout: vault
    page_title: 'Vault: vault_generic_secret resource'
    sidebar_current: docs-vault-resource-generic-secret
    description: Writes arbitrary data to a given path in Vault
    arguments:
        path:
            description: The full logical path at which to write the given data.
            required: true
            policy: ''
            notes: ''
        data_json:
            description: String containing a JSON-encoded object that will be
            required: true
            policy: ''
            notes: ''
        allow_read:
            description: True/false. Set this to true if your
            required: false
            policy: ''
            notes: ''
        disable_read:
            description: True/false. Set this to true if your vault
            required: false
            policy: ''
            notes: ''
    attributes:
        data:
            description: A mapping whose keys are the top-level data keys returned
                from
    timeouts: {}
