vault_database_secret_backend_static_role:
    status: ASSESS
    layout: vault
    page_title: 'Vault: vault_database_secret_backend_static_role resource'
    sidebar_current: docs-vault-resource-database-secret-backend-static-role
    description: Configures a database secret backend static role for Vault.
    arguments:
        name:
            description: A unique name to give the static role.
            required: true
            policy: ''
            notes: ''
        backend:
            description: The unique name of the Vault mount to configure.
            required: true
            policy: ''
            notes: ''
        db_name:
            description: The unique name of the database connection to use for the
                static role.
            required: true
            policy: ''
            notes: ''
        username:
            description: The database username that this static role corresponds to.
            required: true
            policy: ''
            notes: ''
        rotation_period:
            description: The amount of time Vault should wait before rotating the
                password, in seconds.
            required: true
            policy: ''
            notes: ''
        rotation_statements:
            description: Database statements to execute to rotate the password for
                the configured database user.
            required: false
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
