vault_ssh_secret_backend_ca:
    status: ASSESS
    layout: vault
    page_title: 'Vault: vault_ssh_secret_backend_ca resource'
    sidebar_current: docs-vault-resource-ssh-secret-backend-ca
    description: Managing CA information in an SSH secret backend in Vault
    arguments:
        backend:
            description: The path where the SSH secret backend is mounted. Defaults
                to 'ssh'
            required: false
            policy: ''
            notes: ''
        generate_signing_key:
            description: Whether Vault should generate the signing key pair internally.
                Defaults to true
            required: false
            policy: ''
            notes: ''
        public_key:
            description: The public key part the SSH CA key pair; required if generate_signing_key
                is false.
            required: false
            policy: ''
            notes: ''
        private_key:
            description: The private key part the SSH CA key pair; required if generate_signing_key
                is false.
            required: false
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
