aws_lb_listener_certificate:
    status: ASSESS
    subcategory: Elastic Load Balancing v2 (ALB/NLB)
    layout: aws
    page_title: 'AWS: aws_lb_listener_certificate'
    description: Provides a Load Balancer Listener Certificate resource.
    arguments:
        listener_arn:
            description: The ARN of the listener to which to attach the certificate.
            required: false
            policy: ''
            notes: ''
        certificate_arn:
            description: The ARN of the certificate to attach to the listener.
            required: false
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
