aws_cloudwatch_log_destination_policy:
    status: HOLD
    subcategory: CloudWatch
    layout: aws
    page_title: 'AWS: aws_cloudwatch_log_destination_policy'
    description: Provides a CloudWatch Logs destination policy.
    arguments:
        destination_name:
            description: A name for the subscription filter
            required: true
            policy: ''
            notes: ''
        access_policy:
            description: The policy document. This is a JSON formatted string.
            required: true
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
