aws_vpc_peering_connection:
    status: ASSESS
    subcategory: VPC
    layout: aws
    page_title: 'AWS: aws_vpc_peering_connection'
    description: Provides a resource to manage a VPC peering connection.
    arguments: {}
    attributes: {}
    timeouts: {}
    usage: {}
    import: {}
    hcl_url: {}
