aws_cognito_user_pool:
    status: HOLD
    subcategory: Cognito
    layout: aws
    page_title: 'AWS: aws_cognito_user_pool'
    description: Provides a Cognito User Pool resource.
    arguments:
        admin_create_user_config:
            description: '- The configuration for [AdminCreateUser](#admin-create-user-config'
            required: false
            policy: ''
            notes: ''
        alias_attributes:
            description: 'Attributes supported as an alias for this user pool. Possible
                values: phone_number, email, or preferred_username. Conflicts with
                `username_attributes`.'
            required: false
            policy: ''
            notes: ''
        auto_verified_attributes:
            description: 'The attributes to be auto-verified. Possible values: email,
                phone_number.'
            required: false
            policy: ''
            notes: ''
        device_configuration:
            description: '- The configuration for the [user pool''s device tracking](#device-configuration).'
            required: false
            policy: ''
            notes: ''
        email_configuration:
            description: '- The [Email Configuration](#email-configuration).'
            required: false
            policy: ''
            notes: ''
        name:
            description: The name of the user pool.
            required: true
            policy: ''
            notes: ''
        email_verification_subject:
            description: A string representing the email verification subject. Conflicts
                with `verification_message_template` configuration block `email_subject`
                argument.
            required: false
            policy: ''
            notes: ''
        email_verification_message:
            description: A string representing the email verification message. Conflicts
                with `verification_message_template` configuration block `email_message`
                argument.
            required: false
            policy: ''
            notes: ''
        lambda_config:
            description: '- A container for the AWS [Lambda triggers](#lambda-configuration'
            required: false
            policy: ''
            notes: ''
        mfa_configuration:
            description: Multi-Factor Authentication (MFA
            required: false
            policy: ''
            notes: ''
        password_policy:
            description: '- A container for information about the [user pool password
                policy](#password-policy).'
            required: false
            policy: ''
            notes: ''
        schema:
            description: '- A container with the [schema attributes](#schema-attributes'
            required: false
            policy: ''
            notes: ''
        sms_authentication_message:
            description: A string representing the SMS authentication message. The
                message must contain the `{
            required: false
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
