aws_load_balancer_listener_policy:
    status: HOLD
    subcategory: Elastic Load Balancing (ELB Classic)
    layout: aws
    page_title: 'AWS: aws_load_balancer_listener_policy'
    description: Attaches a load balancer policy to an ELB Listener.
    arguments:
        load_balancer_name:
            description: The load balancer to attach the policy to.
            required: true
            policy: ''
            notes: ''
        load_balancer_port:
            description: The load balancer listener port to apply the policy to.
            required: true
            policy: ''
            notes: ''
        policy_names:
            description: List of Policy Names to apply to the backend server.
            required: true
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the policy.
        load_balancer_name:
            description: The load balancer on which the policy is defined.
        load_balancer_port:
            description: The load balancer listener port the policies are applied
                to
    timeouts: {}
