aws_instance:
    status: ASSESS
    subcategory: EC2
    layout: aws
    page_title: 'AWS: aws_instance'
    description: Provides an EC2 instance resource. This allows instances to be created,
        updated, and deleted. Instances also support provisioning.
    arguments:
        ami:
            description: The AMI to use for the instance.
            required: true
            policy: ''
            notes: ''
        availability_zone:
            description: The AZ to start the instance in.
            required: false
            policy: ''
            notes: ''
        placement_group:
            description: The Placement Group to start the instance in.
            required: false
            policy: ''
            notes: ''
        tenancy:
            description: The tenancy of the instance (if the instance is running in
                a VPC). An instance with a tenancy of dedicated runs on single-tenant
                hardware. The host tenancy is not supported for the import-instance
                command.
            required: false
            policy: ''
            notes: ''
        host_id:
            description: The Id of a dedicated host that the instance will be assigned
                to. Use when an instance is to be launched on a specific dedicated
                host.
            required: false
            policy: ''
            notes: ''
        cpu_core_count:
            description: Sets the number of CPU cores for an instance. This option
                is
            required: false
            policy: ''
            notes: ''
        cpu_threads_per_core:
            description: ' If set to to 1, hyperthreading is disabled on the launched
                instance. Defaults to 2 if not set. See [Optimizing CPU Options](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-optimize-cpu.html'
            required: false
            policy: ''
            notes: Changing `cpu_core_count` and/or `cpu_threads_per_core` will cause
                the resource to be destroyed and re-created.
        ebs_optimized:
            description: If true, the launched EC2 instance will be EBS-optimized.
            required: false
            policy: ''
            notes: ''
        disable_api_termination:
            description: If true, enables [EC2 Instance
            required: false
            policy: ''
            notes: ''
        instance_initiated_shutdown_behavior:
            description: Shutdown behavior for the
            required: false
            policy: ''
            notes: ''
        instance_type:
            description: The type of instance to start. Updates to this field will
                trigger a stop/start of the EC2 instance.
            required: true
            policy: ''
            notes: ''
        key_name:
            description: The key name of the Key Pair to use for the instance; which
                can be managed using [the `aws_key_pair` resource](key_pair.html).
            required: false
            policy: ''
            notes: ''
        get_password_data:
            description: If true, wait for password data to become available and retrieve
                it. Useful for getting the administrator password for instances running
                Microsoft Windows. The password data is exported to the `password_data`
                attribute. See [GetPasswordData](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_GetPasswordData.html
            required: false
            policy: ''
            notes: ''
        monitoring:
            description: If true, the launched EC2 instance will have detailed monitoring
                enabled. (Available since v0.6.0)
            required: false
            policy: ''
            notes: ''
        security_groups:
            description: A list of security group names (EC2-Classic
            required: false
            policy: ''
            notes: If you are creating Instances in a VPC, use `vpc_security_group_ids`
                instead.
        vpc_security_group_ids:
            description: A list of security group IDs to associate with.
            required: false
            policy: ''
            notes: ''
        subnet_id:
            description: The VPC Subnet ID to launch in.
            required: false
            policy: ''
            notes: ''
        associate_public_ip_address:
            description: Associate a public ip address with an instance in a VPC.  Boolean
                value.
            required: false
            policy: ''
            notes: ''
        private_ip:
            description: Private IP address to associate with the
            required: false
            policy: ''
            notes: ''
        source_dest_check:
            description: Controls if traffic is routed to the instance when
            required: false
            policy: ''
            notes: ''
        user_data:
            description: The user data to provide when launching the instance. Do
                not pass gzip-compressed data via this argument; see `user_data_base64`
                instead.
            required: false
            policy: ''
            notes: ''
        user_data_base64:
            description: Can be used instead of `user_data` to pass base64-encoded
                binary data directly. Use this instead of `user_data` whenever the
                value is not a valid UTF-8 string. For example, gzip-encoded user
                data must be base64-encoded and passed via this argument to avoid
                corruption.
            required: false
            policy: ''
            notes: ''
        iam_instance_profile:
            description: The IAM Instance Profile to
            required: false
            policy: ''
            notes: ''
        ipv6_address_count:
            description: A number of IPv6 addresses to associate with the primary
                network interface. Amazon EC2 chooses the IPv6 addresses from the
                range of your subnet.
            required: false
            policy: ''
            notes: ''
        ipv6_addresses:
            description: Specify one or more IPv6 addresses from the range of the
                subnet to associate with the primary network interface
            required: false
            policy: ''
            notes: ''
        tags:
            description: A map of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
        volume_tags:
            description: A map of tags to assign to the devices created by the instance
                at launch time.
            required: false
            policy: ''
            notes: ''
        root_block_device:
            description: Customize details about the root block
            required: false
            policy: ''
            notes: ''
        ebs_block_device:
            description: Additional EBS block devices to attach to the
            required: false
            policy: ''
            notes: ''
        ephemeral_block_device:
            description: Customize Ephemeral (also known as
            required: false
            policy: ''
            notes: ''
        network_interface:
            description: Customize network interfaces to be attached at instance boot
                time. See [Network Interfaces](#network-interfaces
            required: false
            policy: ''
            notes: ''
        credit_specification:
            description: Customize the credit specification of the instance. See [Credit
                Specification](#credit-specification
            required: false
            policy: ''
            notes: ''
        hibernation:
            description: If true, the launched EC2 instance will support hibernation.
            required: false
            policy: ''
            notes: ''
        metadata_options:
            description: Customize the metadata options of the instance. See [Metadata
                Options](#metadata-options
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The instance ID.
        arn:
            description: The ARN of the instance.
        availability_zone:
            description: The availability zone of the instance.
        placement_group:
            description: The placement group of the instance.
        key_name:
            description: The key name of the instance
        password_data:
            description: Base-64 encoded encrypted password data for the instance.
        public_dns:
            description: The public DNS name assigned to the instance. For EC2-VPC,
                this
        public_ip:
            description: 'The public IP address assigned to the instance, if applicable.
                **NOTE**: If you are using an [`aws_eip`](/docs/providers/aws/r/eip.html)
                with your instance, you should refer to the EIP''s address directly
                and not use `public_ip`, as this field will change after the EIP is
                attached.'
        ipv6_addresses:
            description: A list of assigned IPv6 addresses, if any
        primary_network_interface_id:
            description: The ID of the instance's primary network interface.
        private_dns:
            description: The private DNS name assigned to the instance. Can only be
        private_ip:
            description: The private IP address assigned to the instance
        security_groups:
            description: The associated security groups.
        vpc_security_group_ids:
            description: The associated security groups in non-default VPC
        subnet_id:
            description: The VPC subnet ID.
        credit_specification:
            description: Credit specification of instance.
        instance_state:
            description: 'The state of the instance. One of: `pending`, `running`,
                `shutting-down`, `terminated`, `stopping`, `stopped`. See [Instance
                Lifecycle](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html)
                for more information.'
    timeouts:
        create:
            description: Used when launching the instance (until it reaches the initial
                `running` state)
            required: false
            timeout: 10
        update:
            description: Used when stopping and starting the instance when necessary
                during update - e.g. when changing instance type
            required: false
            timeout: 10
        delete:
            description: Used when terminating the instance
            required: false
            timeout: 20
    usage: !!binary |
        Q2lNZ1EzSmxZWFJsSUdFZ2JtVjNJR2x1YzNSaGJtTmxJRzltSUhSb1pTQnNZWFJsYzNRZ1ZXSjFi
        blIxSURFMExqQTBJRzl1SUdGdUNpTWdkREl1YldsamNtOGdibTlrWlNCM2FYUm9JR0Z1SUVGWFV5
        QlVZV2NnYm1GdGFXNW5JR2wwSUNKSVpXeHNiMWR2Y214a0lncHdjbTkyYVdSbGNpQWlZWGR6SWlC
        N0NpQWdjbVZuYVc5dUlEMGdJblZ6TFhkbGMzUXRNaUlLZlFvS1pHRjBZU0FpWVhkelgyRnRhU0ln
        SW5WaWRXNTBkU0lnZXdvZ0lHMXZjM1JmY21WalpXNTBJRDBnZEhKMVpRb0tJQ0JtYVd4MFpYSWdl
        d29nSUNBZ2JtRnRaU0FnSUQwZ0ltNWhiV1VpQ2lBZ0lDQjJZV3gxWlhNZ1BTQmJJblZpZFc1MGRT
        OXBiV0ZuWlhNdmFIWnRMWE56WkM5MVluVnVkSFV0ZEhKMWMzUjVMVEUwTGpBMExXRnRaRFkwTFhO
        bGNuWmxjaTBxSWwwS0lDQjlDZ29nSUdacGJIUmxjaUI3Q2lBZ0lDQnVZVzFsSUNBZ1BTQWlkbWx5
        ZEhWaGJHbDZZWFJwYjI0dGRIbHdaU0lLSUNBZ0lIWmhiSFZsY3lBOUlGc2lhSFp0SWwwS0lDQjlD
        Z29nSUc5M2JtVnljeUE5SUZzaU1EazVOekl3TVRBNU5EYzNJbDBnSXlCRFlXNXZibWxqWVd3S2ZR
        b0tjbVZ6YjNWeVkyVWdJbUYzYzE5cGJuTjBZVzVqWlNJZ0luZGxZaUlnZXdvZ0lHRnRhU0FnSUNB
        Z0lDQWdJQ0FnUFNBaUpIdGtZWFJoTG1GM2MxOWhiV2t1ZFdKMWJuUjFMbWxrZlNJS0lDQnBibk4w
        WVc1alpWOTBlWEJsSUQwZ0luUXlMbTFwWTNKdklnb0tJQ0IwWVdkeklEMGdld29nSUNBZ1RtRnRa
        U0E5SUNKSVpXeHNiMWR2Y214a0lnb2dJSDBLZlFvPQ==
    import: !!binary |
        Q2dwSmJuTjBZVzVqWlhNZ1kyRnVJR0psSUdsdGNHOXlkR1ZrSUhWemFXNW5JSFJvWlNCZ2FXUmdM
        Q0JsTG1jdUNnbz0=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjNjeTlpYkc5aUwyMWhjM1JsY2k5M1pXSnphWFJsTDJSdlkz
        TXZjaTlwYm5OMFlXNWpaUzVvZEcxc0xtMWhjbXRrYjNkdQ==
