aws_lb:
    status: ASSESS
    subcategory: Elastic Load Balancing v2 (ALB/NLB)
    layout: aws
    page_title: 'AWS: aws_lb'
    description: Provides a Load Balancer resource.
    arguments:
        name:
            description: The name of the LB. This name must be unique within your
                AWS account, can have a maximum of 32 characters,
            required: false
            policy: ''
            notes: ''
        name_prefix:
            description: Creates a unique name beginning with the specified prefix.
                Conflicts with `name`.
            required: false
            policy: ''
            notes: ''
        internal:
            description: If true, the LB will be internal.
            required: false
            policy: ''
            notes: ''
        load_balancer_type:
            description: The type of load balancer to create. Possible values are
                `application` or `network`. The default value is `application`.
            required: false
            policy: ''
            notes: ''
        security_groups:
            description: A list of security group IDs to assign to the LB. Only valid
                for Load Balancers of type `application`.
            required: false
            policy: ''
            notes: ''
        drop_invalid_header_fields:
            description: Indicates whether HTTP headers with header fields that are
                not valid are removed by the load balancer (true
            required: false
            policy: ''
            notes: ''
        access_logs:
            description: An Access Logs block. Access Logs documented below.
            required: false
            policy: ''
            notes: ''
        subnets:
            description: A list of subnet IDs to attach to the LB. Subnets
            required: false
            policy: ''
            notes: ''
        subnet_mapping:
            description: A subnet mapping block as documented below.
            required: false
            policy: ''
            notes: ''
        idle_timeout:
            description: 'The time in seconds that the connection is allowed to be
                idle. Only valid for Load Balancers of type `application`. Default:
                60.'
            required: false
            policy: ''
            notes: ''
        enable_deletion_protection:
            description: If true, deletion of the load balancer will be disabled via
            required: false
            policy: ''
            notes: ''
        enable_cross_zone_load_balancing:
            description: If true, cross-zone load balancing of the load balancer will
                be enabled.
            required: false
            policy: ''
            notes: ''
        enable_http2:
            description: Indicates whether HTTP/2 is enabled in `application` load
                balancers. Defaults to `true`.
            required: false
            policy: ''
            notes: ''
        ip_address_type:
            description: The type of IP addresses used by the subnets for your load
                balancer. The possible values are `ipv4` and `dualstack`
            required: false
            policy: ''
            notes: ''
        tags:
            description: A map of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
        bucket:
            description: The S3 bucket name to store the logs in.
            required: true
            policy: ''
            notes: ''
        prefix:
            description: The S3 bucket prefix. Logs are stored in the root if not
                configured.
            required: false
            policy: ''
            notes: ''
        enabled:
            description: Boolean to enable / disable `access_logs`. Defaults to `false`,
                even when `bucket` is specified.
            required: false
            policy: ''
            notes: ''
        subnet_id:
            description: The id of the subnet of which to attach to the load balancer.
                You can specify only one subnet per Availability Zone.
            required: true
            policy: ''
            notes: ''
        allocation_id:
            description: The allocation ID of the Elastic IP address.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ARN of the load balancer (matches `arn`).
        arn:
            description: The ARN of the load balancer (matches `id`).
        arn_suffix:
            description: The ARN suffix for use with CloudWatch Metrics.
        dns_name:
            description: The DNS name of the load balancer.
        zone_id:
            description: The canonical hosted zone ID of the load balancer (to be
                used in a Route 53 Alias record).
    timeouts: {}
