aws_route53_resolver_rule:
    status: ASSESS
    subcategory: Route53 Resolver
    layout: aws
    page_title: 'AWS: aws_route53_resolver_rule'
    description: Provides a Route53 Resolver rule.
    arguments:
        domain_name:
            description: DNS queries for this domain name are forwarded to the IP
                addresses that are specified using `target_ip`.
            required: false
            policy: ''
            notes: ''
        rule_type:
            description: The rule type. Valid values are `FORWARD`, `SYSTEM` and `RECURSIVE`.
            required: false
            policy: ''
            notes: ''
        name:
            description: A friendly name that lets you easily find a rule in the Resolver
                dashboard in the Route 53 console.
            required: false
            policy: ''
            notes: ''
        resolver_endpoint_id:
            description: The ID of the outbound resolver endpoint that you want to
                use to route DNS queries to the IP addresses that you specify using
                `target_ip`.
            required: false
            policy: ''
            notes: ''
        target_ip:
            description: Configuration block(s
            required: false
            policy: ''
            notes: ''
        tags:
            description: A map of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
        ip:
            description: One IP address that you want to forward DNS queries to. You
                can specify only IPv4 addresses.
            required: false
            policy: ''
            notes: ''
        port:
            description: The port at `ip` that you want to forward DNS queries to.
                Default value is `53`
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the resolver rule.
        arn:
            description: The ARN (Amazon Resource Name) for the resolver rule.
        owner_id:
            description: When a rule is shared with another AWS account, the account
                ID of the account that the rule is shared with.
        share_status:
            description: Whether the rules is shared and, if so, whether the current
                account is sharing the rule with another account, or another account
                is sharing the rule with the current account.
    timeouts: {}
    usage: {}
    import: !!binary |
        Q2dwU2IzVjBaVFV6SUZKbGMyOXNkbVZ5SUhKMWJHVnpJR05oYmlCaVpTQnBiWEJ2Y25SbFpDQjFj
        Mmx1WnlCMGFHVWdZR2xrWUN3Z1pTNW5MZ29L
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjNjeTlpYkc5aUwyMWhjM1JsY2k5M1pXSnphWFJsTDJSdlkz
        TXZjaTl5YjNWMFpUVXpYM0psYzI5c2RtVnlYM0oxYkdVdWFIUnRiQzV0WVhKclpHOTNiZz09
