aws_dx_hosted_private_virtual_interface_accepter:
    status: ASSESS
    subcategory: Direct Connect
    layout: aws
    page_title: 'AWS: aws_dx_hosted_private_virtual_interface_accepter'
    description: Provides a resource to manage the accepter's side of a Direct Connect
        hosted private virtual interface.
    arguments:
        virtual_interface_id:
            description: The ID of the Direct Connect virtual interface to accept.
            required: true
            policy: ''
            notes: ''
        dx_gateway_id:
            description: The ID of the Direct Connect gateway to which to connect
                the virtual interface.
            required: false
            policy: ''
            notes: ''
        tags:
            description: A map of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
        vpn_gateway_id:
            description: The ID of the [virtual private gateway](vpn_gateway.html
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the virtual interface.
        arn:
            description: The ARN of the virtual interface.
    timeouts: {}
    usage: !!binary |
        Q25CeWIzWnBaR1Z5SUNKaGQzTWlJSHNLSUNBaklFTnlaV0YwYjNJbmN5QmpjbVZrWlc1MGFXRnNj
        eTRLZlFvS2NISnZkbWxrWlhJZ0ltRjNjeUlnZXdvZ0lHRnNhV0Z6SUQwZ0ltRmpZMlZ3ZEdWeUln
        b0tJQ0FqSUVGalkyVndkR1Z5SjNNZ1kzSmxaR1Z1ZEdsaGJITXVDbjBLQ21SaGRHRWdJbUYzYzE5
        allXeHNaWEpmYVdSbGJuUnBkSGtpSUNKaFkyTmxjSFJsY2lJZ2V3b2dJSEJ5YjNacFpHVnlJRDBn
        SW1GM2N5NWhZMk5sY0hSbGNpSUtmUW9LSXlCRGNtVmhkRzl5SjNNZ2MybGtaU0J2WmlCMGFHVWdW
        a2xHQ25KbGMyOTFjbU5sSUNKaGQzTmZaSGhmYUc5emRHVmtYM0J5YVhaaGRHVmZkbWx5ZEhWaGJG
        OXBiblJsY21aaFkyVWlJQ0pqY21WaGRHOXlJaUI3Q2lBZ1kyOXVibVZqZEdsdmJsOXBaQ0FnSUNB
        OUlDSmtlR052YmkxNmVucDZlbnA2ZWlJS0lDQnZkMjVsY2w5aFkyTnZkVzUwWDJsa0lEMGdJaVI3
        WkdGMFlTNWhkM05mWTJGc2JHVnlYMmxrWlc1MGFYUjVMbUZqWTJWd2RHVnlMbUZqWTI5MWJuUmZh
        V1I5SWdvS0lDQnVZVzFsSUNBZ0lDQWdJQ0FnSUNBOUlDSjJhV1l0Wm05dklnb2dJSFpzWVc0Z0lD
        QWdJQ0FnSUNBZ0lEMGdOREE1TkFvZ0lHRmtaSEpsYzNOZlptRnRhV3g1SUQwZ0ltbHdkalFpQ2lB
        Z1ltZHdYMkZ6YmlBZ0lDQWdJQ0FnUFNBMk5UTTFNZ29LSUNBaklGUm9aU0JoZDNOZlpIaGZhRzl6
        ZEdWa1gzQnlhWFpoZEdWZmRtbHlkSFZoYkY5cGJuUmxjbVpoWTJVS0lDQWpJRzExYzNRZ1ltVWda
        R1Z6ZEhKdmVXVmtJR0psWm05eVpTQjBhR1VnWVhkelgzWndibDluWVhSbGQyRjVMZ29nSUdSbGNH
        VnVaSE5mYjI0Z1BTQmJJbUYzYzE5MmNHNWZaMkYwWlhkaGVTNTJjRzVmWjNjaVhRcDlDZ29qSUVG
        alkyVndkR1Z5SjNNZ2MybGtaU0J2WmlCMGFHVWdWa2xHTGdweVpYTnZkWEpqWlNBaVlYZHpYM1p3
        Ymw5bllYUmxkMkY1SWlBaWRuQnVYMmQzSWlCN0NpQWdjSEp2ZG1sa1pYSWdQU0FpWVhkekxtRmpZ
        MlZ3ZEdWeUlncDlDZ3B5WlhOdmRYSmpaU0FpWVhkelgyUjRYMmh2YzNSbFpGOXdjbWwyWVhSbFgz
        WnBjblIxWVd4ZmFXNTBaWEptWVdObFgyRmpZMlZ3ZEdWeUlpQWlZV05qWlhCMFpYSWlJSHNLSUNC
        d2NtOTJhV1JsY2lBZ0lDQWdJQ0FnSUNBZ0lDQTlJQ0poZDNNdVlXTmpaWEIwWlhJaUNpQWdkbWx5
        ZEhWaGJGOXBiblJsY21aaFkyVmZhV1FnUFNBaUpIdGhkM05mWkhoZmFHOXpkR1ZrWDNCeWFYWmhk
        R1ZmZG1seWRIVmhiRjlwYm5SbGNtWmhZMlV1WTNKbFlYUnZjaTVwWkgwaUNpQWdkbkJ1WDJkaGRH
        VjNZWGxmYVdRZ0lDQWdJQ0FnUFNBaUpIdGhkM05mZG5CdVgyZGhkR1YzWVhrdWRuQnVYMmQzTG1s
        a2ZTSUtDaUFnZEdGbmN5QTlJSHNLSUNBZ0lGTnBaR1VnUFNBaVFXTmpaWEIwWlhJaUNpQWdmUXA5
        Q2c9PQ==
    import: !!binary |
        Q2dwRWFYSmxZM1FnUTI5dWJtVmpkQ0JvYjNOMFpXUWdjSEpwZG1GMFpTQjJhWEowZFdGc0lHbHVk
        R1Z5Wm1GalpYTWdZMkZ1SUdKbElHbHRjRzl5ZEdWa0lIVnphVzVuSUhSb1pTQmdkbWxtSUdsa1lD
        d2daUzVuTGdvSw==
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjNjeTlpYkc5aUwyMWhjM1JsY2k5M1pXSnphWFJsTDJSdlkz
        TXZjaTlrZUY5b2IzTjBaV1JmY0hKcGRtRjBaVjkyYVhKMGRXRnNYMmx1ZEdWeVptRmpaVjloWTJO
        bGNIUmxjaTVvZEcxc0xtMWhjbXRrYjNkdQ==
