aws_wafregional_sql_injection_match_set:
    status: ASSESS
    subcategory: WAF Regional
    layout: aws
    page_title: 'AWS: aws_wafregional_sql_injection_match_set'
    description: Provides a AWS WAF Regional SqlInjectionMatchSet resource for use
        with ALB.
    arguments:
        name:
            description: The name or description of the SizeConstraintSet.
            required: true
            policy: ''
            notes: ''
        sql_injection_match_tuple:
            description: The parts of web requests that you want AWS WAF to inspect
                for malicious SQL code and, if you want AWS WAF to inspect a header,
                the name of the header.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the WAF SqlInjectionMatchSet.
    timeouts: {}
