aws_waf_size_constraint_set:
    status: HOLD
    subcategory: WAF
    layout: aws
    page_title: 'AWS: aws_waf_size_constraint_set'
    description: Provides a AWS WAF Size Constraint Set resource.
    arguments:
        name:
            description: The name or description of the Size Constraint Set.
            required: true
            policy: ''
            notes: ''
        size_constraints:
            description: Specifies the parts of web requests that you want to inspect
                the size of.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the WAF Size Constraint Set.
        arn:
            description: Amazon Resource Name (ARN)
    timeouts: {}
