aws_iam_group:
    status: ASSESS
    subcategory: IAM
    layout: aws
    page_title: 'AWS: aws_iam_group'
    description: Provides an IAM group.
    arguments:
        name:
            description: 'The group''s name. The name must consist of upper and lowercase
                alphanumeric characters with no spaces. You can also include any of
                the following characters: `=,.@-_.`. Group names are not distinguished
                by case. For example, you cannot create groups named both "ADMINS"
                and "admins".'
            required: true
            policy: ''
            notes: ''
        path:
            description: Path in which to create the group.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The group's ID.
        arn:
            description: The ARN assigned by AWS for this group.
        name:
            description: The group's name.
        path:
            description: The path of the group in IAM.
        unique_id:
            description: The [unique ID][1] assigned by AWS.
    timeouts: {}
