aws_cloudwatch_log_metric_filter:
    status: HOLD
    subcategory: CloudWatch
    layout: aws
    page_title: 'AWS: aws_cloudwatch_log_metric_filter'
    description: Provides a CloudWatch Log Metric Filter resource.
    arguments:
        name:
            description: The name of the CloudWatch metric to which the monitored
                log information should be published (e.g. `ErrorCount`)
            required: true
            policy: ''
            notes: ''
        pattern:
            description: A valid [CloudWatch Logs filter pattern](https://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/FilterAndPatternSyntax.html)
            required: true
            policy: ''
            notes: ''
        log_group_name:
            description: The name of the log group to associate the metric filter
                with.
            required: true
            policy: ''
            notes: ''
        metric_transformation:
            description: A block defining collection of information
            required: true
            policy: ''
            notes: ''
        namespace:
            description: The destination namespace of the CloudWatch metric.
            required: true
            policy: ''
            notes: ''
        value:
            description: What to publish to the metric. For example, if you're counting
                the occurrences of a particular term like "Error", the value will
                be "1" for each occurrence. If you're counting the bytes transferred
                the published value will be the value in the log event.
            required: true
            policy: ''
            notes: ''
        default_value:
            description: The value to emit when a filter pattern does not match a
                log event.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The name of the metric filter.
    timeouts: {}
