aws_globalaccelerator_listener:
    status: ASSESS
    subcategory: Global Accelerator
    layout: aws
    page_title: 'AWS: aws_globalaccelerator_listener'
    description: Provides a Global Accelerator listener.
    arguments:
        accelerator_arn:
            description: The Amazon Resource Name (ARN
            required: true
            policy: ''
            notes: ''
        client_affinity:
            description: 'Direct all requests from a user to the same endpoint. Valid
                values are `NONE`, `SOURCE_IP`. Default: `NONE`. If `NONE`, Global
                Accelerator uses the "five-tuple" properties of source IP address,
                source port, destination IP address, destination port, and protocol
                to select the hash value. If `SOURCE_IP`, Global Accelerator uses
                the "two-tuple" properties of source (client'
            required: false
            policy: ''
            notes: ''
        protocol:
            description: The protocol for the connections from clients to the accelerator.
                Valid values are `TCP`, `UDP`.
            required: false
            policy: ''
            notes: ''
        port_range:
            description: The list of port ranges for the connections from clients
                to the accelerator. Fields documented below.
            required: false
            policy: ''
            notes: ''
        from_port:
            description: The first port in the range of ports, inclusive.
            required: false
            policy: ''
            notes: ''
        to_port:
            description: The last port in the range of ports, inclusive.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The Amazon Resource Name (ARN) of the listener.
    timeouts: {}
