aws_appautoscaling_scheduled_action:
    status: ASSESS
    subcategory: Application Autoscaling
    layout: aws
    page_title: 'AWS: aws_appautoscaling_scheduled_action'
    description: Provides an Application AutoScaling ScheduledAction resource.
    arguments:
        name:
            description: The name of the scheduled action.
            required: true
            policy: ''
            notes: ''
        service_namespace:
            description: 'The namespace of the AWS service. Documentation can be found
                in the parameter at: [AWS Application Auto Scaling API Reference](https://docs.aws.amazon.com/ApplicationAutoScaling/latest/APIReference/API_PutScheduledAction.html#ApplicationAutoScaling-PutScheduledAction-request-ServiceNamespace'
            required: true
            policy: ''
            notes: ''
        resource_id:
            description: 'The identifier of the resource associated with the scheduled
                action. Documentation can be found in the parameter at: [AWS Application
                Auto Scaling API Reference](https://docs.aws.amazon.com/ApplicationAutoScaling/latest/APIReference/API_PutScheduledAction.html#ApplicationAutoScaling-PutScheduledAction-request-ResourceId)'
            required: true
            policy: ''
            notes: ''
        scalable_dimension:
            description: 'The scalable dimension. Documentation can be found in the
                parameter at: [AWS Application Auto Scaling API Reference](https://docs.aws.amazon.com/ApplicationAutoScaling/latest/APIReference/API_PutScheduledAction.html#ApplicationAutoScaling-PutScheduledAction-request-ScalableDimension'
            required: false
            policy: ''
            notes: ''
        scalable_target_action:
            description: The new minimum and maximum capacity. You can set both values
                or just one. See [below](#scalable-target-action-arguments)
            required: false
            policy: ''
            notes: ''
        schedule:
            description: 'The schedule for this action. The following formats are
                supported: At expressions - at(yyyy-mm-ddThh:mm:ss), Rate expressions
                - rate(valueunit), Cron expressions - cron(fields). In UTC. Documentation
                can be found in the parameter at: [AWS Application Auto Scaling API
                Reference](https://docs.aws.amazon.com/ApplicationAutoScaling/latest/APIReference/API_PutScheduledAction.html#ApplicationAutoScaling-PutScheduledAction-request-Schedule)'
            required: false
            policy: ''
            notes: ''
        start_time:
            description: 'The date and time for the scheduled action to start. Specify
                the following format: 2006-01-02T15:04:05Z'
            required: false
            policy: ''
            notes: ''
        end_time:
            description: 'The date and time for the scheduled action to end. Specify
                the following format: 2006-01-02T15:04:05Z'
            required: false
            policy: ''
            notes: ''
    attributes:
        arn:
            description: The Amazon Resource Name (ARN) of the scheduled action.
    timeouts: {}
