aws_default_vpc:
    status: ASSESS
    subcategory: VPC
    layout: aws
    page_title: 'AWS: aws_default_vpc'
    description: Manage the default VPC resource.
    arguments:
        enable_dns_support:
            description: A boolean flag to enable/disable DNS support in the VPC.
                Defaults true.
            required: false
            policy: ''
            notes: ''
        enable_dns_hostnames:
            description: A boolean flag to enable/disable DNS hostnames in the VPC.
                Defaults false.
            required: false
            policy: ''
            notes: ''
        enable_classiclink:
            description: A boolean flag to enable/disable ClassicLink
            required: false
            policy: ''
            notes: ''
        tags:
            description: A map of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
    attributes:
        arn:
            description: Amazon Resource Name (ARN) of VPC
        id:
            description: The ID of the VPC
        cidr_block:
            description: The CIDR block of the VPC
        instance_tenancy:
            description: Tenancy of instances spin up within VPC.
        enable_dns_support:
            description: Whether or not the VPC has DNS support
        enable_dns_hostnames:
            description: Whether or not the VPC has DNS hostname support
        enable_classiclink:
            description: Whether or not the VPC has Classiclink enabled
        assign_generated_ipv6_cidr_block:
            description: Whether or not an Amazon-provided IPv6 CIDR
        main_route_table_id:
            description: The ID of the main route table associated with
        default_network_acl_id:
            description: The ID of the network ACL created by default on VPC creation
        default_security_group_id:
            description: The ID of the security group created by default on VPC creation
        default_route_table_id:
            description: The ID of the route table created by default on VPC creation
        ipv6_association_id:
            description: The association ID for the IPv6 CIDR block of the VPC
        ipv6_cidr_block:
            description: The IPv6 CIDR block of the VPC
        owner_id:
            description: The ID of the AWS account that owns the VPC.
    timeouts: {}
