aws_waf_ipset:
    status: ASSESS
    subcategory: WAF
    layout: aws
    page_title: 'AWS: aws_waf_ipset'
    description: Provides a AWS WAF IPSet resource.
    arguments:
        name:
            description: The name or description of the IPSet.
            required: true
            policy: ''
            notes: ''
        ip_set_descriptors:
            description: One or more pairs specifying the IP address type (IPV4 or
                IPV6
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the WAF IPSet.
        arn:
            description: The ARN of the WAF IPSet.
    timeouts: {}
