aws_wafregional_geo_match_set:
    status: ASSESS
    subcategory: WAF Regional
    layout: aws
    page_title: 'AWS: aws_wafregional_geo_match_set'
    description: Provides a AWS WAF Regional Geo Match Set resource.
    arguments:
        name:
            description: The name or description of the Geo Match Set.
            required: true
            policy: ''
            notes: ''
        geo_match_constraint:
            description: The Geo Match Constraint objects which contain the country
                that you want AWS WAF to search for.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the WAF Regional Geo Match Set.
    timeouts: {}
