aws_ec2_transit_gateway_route_table:
    status: HOLD
    subcategory: EC2
    layout: aws
    page_title: 'AWS: aws_ec2_transit_gateway_route_table'
    description: Manages an EC2 Transit Gateway Route Table
    arguments:
        transit_gateway_id:
            description: Identifier of EC2 Transit Gateway.
            required: true
            policy: ''
            notes: ''
        tags:
            description: Key-value tags for the EC2 Transit Gateway Route Table.
            required: false
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
