aws_macie_member_account_association:
    status: HOLD
    subcategory: Macie
    layout: aws
    page_title: 'AWS: aws_macie_member_account_association'
    description: Associates an AWS account with Amazon Macie as a member account.
    arguments:
        member_account_id:
            description: The ID of the AWS account that you want to associate with
                Amazon Macie as a member account.
            required: true
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the association.
    timeouts: {}
