aws_vpn_gateway_route_propagation:
    status: HOLD
    subcategory: VPC
    layout: aws
    page_title: 'AWS: aws_vpn_gateway_route_propagation'
    description: Requests automatic route propagation between a VPN gateway and a
        route table.
    arguments: {}
    attributes: {}
    timeouts: {}
