aws_ssm_patch_group:
    status: ASSESS
    subcategory: SSM
    layout: aws
    page_title: 'AWS: aws_ssm_patch_group'
    description: Provides an SSM Patch Group resource
    arguments:
        baseline_id:
            description: The ID of the patch baseline to register the patch group
                with.
            required: true
            policy: ''
            notes: ''
        patch_group:
            description: The name of the patch group that should be registered with
                the patch baseline.
            required: true
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the patch baseline.
    timeouts: {}
