aws_nat_gateway:
    status: HOLD
    subcategory: VPC
    layout: aws
    page_title: 'AWS: aws_nat_gateway'
    description: Provides a resource to create a VPC NAT Gateway.
    arguments:
        allocation_id:
            description: The Allocation ID of the Elastic IP address for the gateway.
            required: true
            policy: ''
            notes: ''
        subnet_id:
            description: The Subnet ID of the subnet in which to place the gateway.
            required: true
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
