aws_appsync_api_key:
    status: ASSESS
    subcategory: AppSync
    layout: aws
    page_title: 'AWS: aws_appsync_api_key'
    description: Provides an AppSync API Key.
    arguments:
        api_id:
            description: The ID of the associated AppSync API
            required: true
            policy: ''
            notes: ''
        description:
            description: The API key description. Defaults to "Managed by Terraform".
            required: false
            policy: ''
            notes: ''
        expires:
            description: RFC3339 string representation of the expiry date. Rounded
                down to nearest hour. By default, it is 7 days from the date of creation.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: API Key ID (Formatted as ApiId:Key)
        key:
            description: The API key
    timeouts: {}
