aws_dx_transit_virtual_interface:
    status: ASSESS
    subcategory: Direct Connect
    layout: aws
    page_title: 'AWS: aws_dx_transit_virtual_interface'
    description: Provides a Direct Connect transit virtual interface resource.
    arguments:
        address_family:
            description: The address family for the BGP peer. `ipv4 ` or `ipv6`.
            required: false
            policy: ''
            notes: ''
        bgp_asn:
            description: The autonomous system (AS
            required: false
            policy: ''
            notes: ''
        connection_id:
            description: The ID of the Direct Connect connection (or LAG
            required: false
            policy: ''
            notes: ''
        dx_gateway_id:
            description: The ID of the Direct Connect gateway to which to connect
                the virtual interface.
            required: false
            policy: ''
            notes: ''
        name:
            description: The name for the virtual interface.
            required: false
            policy: ''
            notes: ''
        vlan:
            description: The VLAN ID.
            required: false
            policy: ''
            notes: ''
        amazon_address:
            description: The IPv4 CIDR address to use to send traffic to Amazon. Required
                for IPv4 BGP peers.
            required: false
            policy: ''
            notes: ''
        bgp_auth_key:
            description: The authentication key for BGP configuration.
            required: false
            policy: ''
            notes: ''
        customer_address:
            description: The IPv4 CIDR destination address to which Amazon should
                send traffic. Required for IPv4 BGP peers.
            required: false
            policy: ''
            notes: ''
        mtu:
            description: The maximum transmission unit (MTU
            required: false
            policy: ''
            notes: ''
        tags:
            description: A map of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the virtual interface.
        arn:
            description: The ARN of the virtual interface.
        aws_device:
            description: The Direct Connect endpoint on which the virtual interface
                terminates.
        jumbo_frame_capable:
            description: Indicates whether jumbo frames (8500 MTU) are supported.
    timeouts: {}
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGQzTmZaSGhmWjJGMFpYZGhlU0lnSW1WNFlXMXdiR1VpSUhzS0lDQnVZ
        VzFsSUNBZ0lDQWdJQ0FnSUNBZ1BTQWlkR1l0WkhobkxXVjRZVzF3YkdVaUNpQWdZVzFoZW05dVgz
        TnBaR1ZmWVhOdUlEMGdOalExTVRJS2ZRb0tjbVZ6YjNWeVkyVWdJbUYzYzE5a2VGOTBjbUZ1YzJs
        MFgzWnBjblIxWVd4ZmFXNTBaWEptWVdObElpQWlaWGhoYlhCc1pTSWdld29nSUdOdmJtNWxZM1Jw
        YjI1ZmFXUWdQU0FpSkh0aGQzTmZaSGhmWTI5dWJtVmpkR2x2Ymk1bGVHRnRjR3hsTG1sa2ZTSUtD
        aUFnWkhoZloyRjBaWGRoZVY5cFpDQWdQU0FpSkh0aGQzTmZaSGhmWjJGMFpYZGhlUzVsZUdGdGNH
        eGxMbWxrZlNJS0lDQnVZVzFsSUNBZ0lDQWdJQ0FnSUNBOUlDSjBaaTEwY21GdWMybDBMWFpwWmkx
        bGVHRnRjR3hsSWdvZ0lIWnNZVzRnSUNBZ0lDQWdJQ0FnSUQwZ05EQTVOQW9nSUdGa1pISmxjM05m
        Wm1GdGFXeDVJRDBnSW1sd2RqUWlDaUFnWW1kd1gyRnpiaUFnSUNBZ0lDQWdQU0EyTlRNMU1ncDlD
        Zz09
    import: !!binary |
        Q2dwRWFYSmxZM1FnUTI5dWJtVmpkQ0IwY21GdWMybDBJSFpwY25SMVlXd2dhVzUwWlhKbVlXTmxj
        eUJqWVc0Z1ltVWdhVzF3YjNKMFpXUWdkWE5wYm1jZ2RHaGxJR0IyYVdZZ2FXUmdMQ0JsTG1jdUNn
        bz0=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjNjeTlpYkc5aUwyMWhjM1JsY2k5M1pXSnphWFJsTDJSdlkz
        TXZjaTlrZUY5MGNtRnVjMmwwWDNacGNuUjFZV3hmYVc1MFpYSm1ZV05sTG1oMGJXd3ViV0Z5YTJS
        dmQyND0=
