aws_iam_openid_connect_provider:
    status: HOLD
    subcategory: IAM
    layout: aws
    page_title: 'AWS: aws_iam_openid_connect_provider'
    description: Provides an IAM OpenID Connect provider.
    arguments:
        url:
            description: The URL of the identity provider. Corresponds to the _iss_
                claim.
            required: true
            policy: ''
            notes: ''
        client_id_list:
            description: A list of client IDs (also known as audiences). When a mobile
                or web app registers with an OpenID Connect provider, they establish
                a value that identifies the application. (This is the value that's
                sent as the client_id parameter on OAuth requests.)
            required: true
            policy: ''
            notes: ''
        thumbprint_list:
            description: A list of server certificate thumbprints for the OpenID Connect
                (OIDC
            required: true
            policy: ''
            notes: ''
    attributes:
        arn:
            description: The ARN assigned by AWS for this provider.
    timeouts: {}
