aws_docdb_cluster_snapshot:
    status: ASSESS
    subcategory: DocumentDB
    layout: aws
    page_title: 'AWS: aws_docdb_cluster_snapshot'
    description: Manages a DocDB database cluster snapshot.
    arguments:
        db_cluster_identifier:
            description: The DocDB Cluster Identifier from which to take the snapshot.
            required: false
            policy: ''
            notes: ''
        db_cluster_snapshot_identifier:
            description: The Identifier for the snapshot.
            required: false
            policy: ''
            notes: ''
    attributes:
        availability_zones:
            description: List of EC2 Availability Zones that instances in the DocDB
                cluster snapshot can be restored in.
        db_cluster_snapshot_arn:
            description: The Amazon Resource Name (ARN) for the DocDB Cluster Snapshot.
        engine:
            description: Specifies the name of the database engine.
        engine_version:
            description: Version of the database engine for this DocDB cluster snapshot.
        kms_key_id:
            description: If storage_encrypted is true, the AWS KMS key identifier
                for the encrypted DocDB cluster snapshot.
        port:
            description: Port that the DocDB cluster was listening on at the time
                of the snapshot.
        source_db_cluster_snapshot_identifier:
            description: The DocDB Cluster Snapshot Arn that the DocDB Cluster Snapshot
                was copied from. It only has value in case of cross customer or cross
                region copy.
        storage_encrypted:
            description: Specifies whether the DocDB cluster snapshot is encrypted.
        status:
            description: The status of this DocDB Cluster Snapshot.
        vpc_id:
            description: The VPC ID associated with the DocDB cluster snapshot.
    timeouts: {}
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGQzTmZaRzlqWkdKZlkyeDFjM1JsY2w5emJtRndjMmh2ZENJZ0ltVjRZ
        VzF3YkdVaUlIc0tJQ0JrWWw5amJIVnpkR1Z5WDJsa1pXNTBhV1pwWlhJZ0lDQWdJQ0FnSUNBZ1BT
        QWlKSHRoZDNOZlpHOWpaR0pmWTJ4MWMzUmxjaTVsZUdGdGNHeGxMbWxrZlNJS0lDQmtZbDlqYkhW
        emRHVnlYM051WVhCemFHOTBYMmxrWlc1MGFXWnBaWElnUFNBaWNtVnpiM1Z5WTJWMFpYTjBjMjVo
        Y0hOb2IzUXhNak0wSWdwOUNnPT0=
    import: !!binary |
        Q2dwZ1lYZHpYMlJ2WTJSaVgyTnNkWE4wWlhKZmMyNWhjSE5vYjNSZ0lHTmhiaUJpWlNCcGJYQnZj
        blJsWkNCaWVTQjFjMmx1WnlCMGFHVWdZMngxYzNSbGNpQnpibUZ3YzJodmRDQnBaR1Z1ZEdsbWFX
        VnlMQ0JsTG1jdUNnbz0=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjNjeTlpYkc5aUwyMWhjM1JsY2k5M1pXSnphWFJsTDJSdlkz
        TXZjaTlrYjJOa1lsOWpiSFZ6ZEdWeVgzTnVZWEJ6YUc5MExtaDBiV3d1YldGeWEyUnZkMjQ9
