aws_lb_cookie_stickiness_policy:
    status: ASSESS
    subcategory: Elastic Load Balancing (ELB Classic)
    layout: aws
    page_title: 'AWS: aws_lb_cookie_stickiness_policy'
    description: Provides a load balancer cookie stickiness policy, which allows an
        ELB to control the sticky session lifetime of the browser.
    arguments:
        name:
            description: The name of the stickiness policy.
            required: true
            policy: ''
            notes: ''
        load_balancer:
            description: The load balancer to which the policy
            required: true
            policy: ''
            notes: ''
        lb_port:
            description: The load balancer port to which the policy
            required: true
            policy: ''
            notes: ''
        cookie_expiration_period:
            description: The time period after which
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the policy.
        name:
            description: The name of the stickiness policy.
        load_balancer:
            description: The load balancer to which the policy is attached.
        lb_port:
            description: The load balancer port to which the policy is applied.
        cookie_expiration_period:
            description: The time period after which the session cookie is considered
                stale, expressed in seconds.
    timeouts: {}
