aws_backup_plan:
    status: HOLD
    subcategory: Backup
    layout: aws
    page_title: 'AWS: aws_backup_plan'
    description: Provides an AWS Backup plan resource.
    arguments:
        name:
            description: The display name of a backup plan.
            required: true
            policy: ''
            notes: ''
        rule:
            description: A rule object that specifies a scheduled task that is used
                to back up a selection of resources.
            required: true
            policy: ''
            notes: ''
        tags:
            description: Metadata that you can assign to help organize the plans you
                create.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The id of the backup plan.
        arn:
            description: The ARN of the backup plan.
        version:
            description: Unique, randomly generated, Unicode, UTF-8 encoded string
                that serves as the version ID of the backup plan.
    timeouts: {}
