aws_guardduty_member:
    status: ASSESS
    subcategory: GuardDuty
    layout: aws
    page_title: 'AWS: aws_guardduty_member'
    description: Provides a resource to manage a GuardDuty member
    arguments:
        account_id:
            description: AWS account ID for member account.
            required: false
            policy: ''
            notes: ''
        detector_id:
            description: The detector ID of the GuardDuty account where you want to
                create member accounts.
            required: false
            policy: ''
            notes: ''
        email:
            description: Email address for member account.
            required: false
            policy: ''
            notes: ''
        invite:
            description: Boolean whether to invite the account to GuardDuty as a member.
                Defaults to `false`. To detect if an invitation needs to be (re-)sent,
                the Terraform state value is `true` based on a `relationship_status`
                of `Disabled`, `Enabled`, `Invited`, or `EmailVerificationInProgress`.
            required: false
            policy: ''
            notes: ''
        invitation_message:
            description: Message for invitation.
            required: false
            policy: ''
            notes: ''
        disable_email_notification:
            description: Boolean whether an email notification is sent to the accounts.
                Defaults to `false`.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the GuardDuty member
        relationship_status:
            description: The status of the relationship between the member account
                and its master account. More information can be found in [Amazon GuardDuty
                API Reference](https://docs.aws.amazon.com/guardduty/latest/ug/get-members.html).
    timeouts: {}
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGQzTmZaM1ZoY21Sa2RYUjVYMlJsZEdWamRHOXlJaUFpYldGemRHVnlJ
        aUI3Q2lBZ1pXNWhZbXhsSUQwZ2RISjFaUXA5Q2dweVpYTnZkWEpqWlNBaVlYZHpYMmQxWVhKa1pI
        VjBlVjlrWlhSbFkzUnZjaUlnSW0xbGJXSmxjaUlnZXdvZ0lIQnliM1pwWkdWeUlEMGdJbUYzY3k1
        a1pYWWlDZ29nSUdWdVlXSnNaU0E5SUhSeWRXVUtmUW9LY21WemIzVnlZMlVnSW1GM2MxOW5kV0Z5
        WkdSMWRIbGZiV1Z0WW1WeUlpQWliV1Z0WW1WeUlpQjdDaUFnWVdOamIzVnVkRjlwWkNBZ0lDQWdJ
        Q0FnSUQwZ0lpUjdZWGR6WDJkMVlYSmtaSFYwZVY5a1pYUmxZM1J2Y2k1dFpXMWlaWEl1WVdOamIz
        VnVkRjlwWkgwaUNpQWdaR1YwWldOMGIzSmZhV1FnSUNBZ0lDQWdJRDBnSWlSN1lYZHpYMmQxWVhK
        a1pIVjBlVjlrWlhSbFkzUnZjaTV0WVhOMFpYSXVhV1I5SWdvZ0lHVnRZV2xzSUNBZ0lDQWdJQ0Fn
        SUNBZ0lDQTlJQ0p5WlhGMWFYSmxaRUJsZUdGdGNHeGxMbU52YlNJS0lDQnBiblpwZEdVZ0lDQWdJ
        Q0FnSUNBZ0lDQWdQU0IwY25WbENpQWdhVzUyYVhSaGRHbHZibDl0WlhOellXZGxJRDBnSW5Cc1pX
        RnpaU0JoWTJObGNIUWdaM1ZoY21Sa2RYUjVJR2x1ZG1sMFlYUnBiMjRpQ24wSw==
    import: !!binary |
        Q2dwSGRXRnlaRVIxZEhrZ2JXVnRZbVZ5Y3lCallXNGdZbVVnYVcxd2IzSjBaV1FnZFhOcGJtY2dk
        R2hsSUhSb1pTQnRZWE4wWlhJZ1IzVmhjbVJFZFhSNUlHUmxkR1ZqZEc5eUlFbEVJR0Z1WkNCdFpX
        MWlaWElnUVZkVElHRmpZMjkxYm5RZ1NVUXNJR1V1Wnk0S0NnPT0=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjNjeTlpYkc5aUwyMWhjM1JsY2k5M1pXSnphWFJsTDJSdlkz
        TXZjaTluZFdGeVpHUjFkSGxmYldWdFltVnlMbWgwYld3dWJXRnlhMlJ2ZDI0PQ==
