aws_ses_identity_notification_topic:
    status: HOLD
    subcategory: SES
    layout: aws
    page_title: 'AWS: aws_ses_identity_notification_topic'
    description: Setting AWS SES Identity Notification Topic
    arguments:
        topic_arn:
            description: The Amazon Resource Name (ARN
            required: false
            policy: ''
            notes: ''
        notification_type:
            description: 'The type of notifications that will be published to the
                specified Amazon SNS topic. Valid Values: *Bounce*, *Complaint* or
                *Delivery*.'
            required: true
            policy: ''
            notes: ''
        identity:
            description: The identity for which the Amazon SNS topic will be set.
                You can specify an identity by using its name or by using its Amazon
                Resource Name (ARN).
            required: true
            policy: ''
            notes: ''
        include_original_headers:
            description: Whether SES should include original email headers in SNS
                notifications of this type. *false* by default.
            required: false
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
