aws_msk_configuration:
    status: HOLD
    subcategory: Managed Streaming for Kafka (MSK)
    layout: aws
    page_title: 'AWS: aws_msk_configuration'
    description: Terraform resource for managing an Amazon Managed Streaming for Kafka
        configuration
    arguments:
        server_properties:
            description: Contents of the server.properties file. Supported properties
                are documented in the [MSK Developer Guide](https://docs.aws.amazon.com/msk/latest/developerguide/msk-configuration-properties.html).
            required: true
            policy: ''
            notes: ''
        kafka_versions:
            description: List of Apache Kafka versions which can use this configuration.
            required: true
            policy: ''
            notes: ''
        name:
            description: Name of the configuration.
            required: true
            policy: ''
            notes: ''
        description:
            description: Description of the configuration.
            required: false
            policy: ''
            notes: ''
    attributes:
        arn:
            description: Amazon Resource Name (ARN) of the configuration.
        latest_revision:
            description: Latest revision of the configuration.
    timeouts: {}
