aws_vpc_dhcp_options:
    status: HOLD
    subcategory: VPC
    layout: aws
    page_title: 'AWS: aws_vpc_dhcp_options'
    description: Provides a VPC DHCP Options resource.
    arguments:
        domain_name:
            description: the suffix domain name to use by default when resolving non
                Fully Qualified Domain Names. In other words, this is what ends up
                being the `search` value in the `/etc/resolv.conf` file.
            required: false
            policy: ''
            notes: ''
        domain_name_servers:
            description: List of name servers to configure in `/etc/resolv.conf`.
                If you want to use the default AWS nameservers you should set this
                to `AmazonProvidedDNS`.
            required: false
            policy: ''
            notes: ''
        ntp_servers:
            description: List of NTP servers to configure.
            required: false
            policy: ''
            notes: ''
        netbios_name_servers:
            description: List of NETBIOS name servers.
            required: false
            policy: ''
            notes: ''
        netbios_node_type:
            description: The NetBIOS node type (1, 2, 4, or 8). AWS recommends to
                specify 2 since broadcast and multicast are not supported in their
                network. For more information about these node types, see [RFC 2132](http://www.ietf.org/rfc/rfc2132.txt).
            required: false
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the DHCP Options Set.
        owner_id:
            description: The ID of the AWS account that owns the DHCP options set.
    timeouts: {}
