aws_sns_platform_application:
    status: ASSESS
    subcategory: SNS
    layout: aws
    page_title: 'AWS: aws_sns_platform_application'
    description: Provides an SNS platform application resource.
    arguments:
        name:
            description: The friendly name for the SNS platform application
            required: true
            policy: ''
            notes: ''
        platform:
            description: The platform that the app is registered with. See [Platform][1]
                for supported platforms.
            required: true
            policy: ''
            notes: ''
        platform_credential:
            description: Application Platform credential. See [Credential][1] for
                type of credential required for platform. The value of this attribute
                when stored into the Terraform state is only a hash of the real value,
                so therefore it is not practical to use this as an attribute for other
                resources.
            required: true
            policy: ''
            notes: ''
        event_delivery_failure_topic_arn:
            description: SNS Topic triggered when a delivery to any of the platform
                endpoints associated with your platform application encounters a permanent
                failure.
            required: false
            policy: ''
            notes: ''
        event_endpoint_created_topic_arn:
            description: SNS Topic triggered when a new platform endpoint is added
                to your platform application.
            required: false
            policy: ''
            notes: ''
        event_endpoint_deleted_topic_arn:
            description: SNS Topic triggered when an existing platform endpoint is
                deleted from your platform application.
            required: false
            policy: ''
            notes: ''
        event_endpoint_updated_topic_arn:
            description: SNS Topic triggered when an existing platform endpoint is
                changed from your platform application.
            required: false
            policy: ''
            notes: ''
        failure_feedback_role_arn:
            description: The IAM role permitted to receive failure feedback for this
                application.
            required: false
            policy: ''
            notes: ''
        platform_principal:
            description: Application Platform principal. See [Principal][2] for type
                of principal required for platform. The value of this attribute when
                stored into the Terraform state is only a hash of the real value,
                so therefore it is not practical to use this as an attribute for other
                resources.
            required: false
            policy: ''
            notes: ''
        success_feedback_role_arn:
            description: The IAM role permitted to receive success feedback for this
                application.
            required: false
            policy: ''
            notes: ''
        success_feedback_sample_rate:
            description: The percentage of success to sample (0-100)
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ARN of the SNS platform application
        arn:
            description: The ARN of the SNS platform application
    timeouts: {}
