aws_appautoscaling_policy:
    status: ASSESS
    subcategory: Application Autoscaling
    layout: aws
    page_title: 'AWS: aws_appautoscaling_policy'
    description: Provides an Application AutoScaling Policy resource.
    arguments:
        name:
            description: The name of the policy.
            required: true
            policy: ''
            notes: ''
        policy_type:
            description: For DynamoDB, only `TargetTrackingScaling` is supported.
                For Amazon ECS, Spot Fleet, and Amazon RDS, both `StepScaling` and
                `TargetTrackingScaling` are supported. For any other service, only
                `StepScaling` is supported. Defaults to `StepScaling`.
            required: false
            policy: ''
            notes: ''
        resource_id:
            description: 'The resource type and unique identifier string for the resource
                associated with the scaling policy. Documentation can be found in
                the `ResourceId` parameter at: [AWS Application Auto Scaling API Reference](http://docs.aws.amazon.com/ApplicationAutoScaling/latest/APIReference/API_RegisterScalableTarget.html#API_RegisterScalableTarget_RequestParameters)'
            required: true
            policy: ''
            notes: ''
        scalable_dimension:
            description: 'The scalable dimension of the scalable target. Documentation
                can be found in the `ScalableDimension` parameter at: [AWS Application
                Auto Scaling API Reference](http://docs.aws.amazon.com/ApplicationAutoScaling/latest/APIReference/API_RegisterScalableTarget.html#API_RegisterScalableTarget_RequestParameters)'
            required: true
            policy: ''
            notes: ''
        service_namespace:
            description: 'The AWS service namespace of the scalable target. Documentation
                can be found in the `ServiceNamespace` parameter at: [AWS Application
                Auto Scaling API Reference](http://docs.aws.amazon.com/ApplicationAutoScaling/latest/APIReference/API_RegisterScalableTarget.html#API_RegisterScalableTarget_RequestParameters)'
            required: true
            policy: ''
            notes: ''
        step_scaling_policy_configuration:
            description: Step scaling policy configuration, requires `policy_type
                = "StepScaling"` (default). See supported fields below.
            required: false
            policy: ''
            notes: ''
        target_tracking_scaling_policy_configuration:
            description: A target tracking policy, requires `policy_type = "TargetTrackingScaling"`.
                See supported fields below.
            required: false
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
