aws_guardduty_invite_accepter:
    status: HOLD
    subcategory: GuardDuty
    layout: aws
    page_title: 'AWS: aws_guardduty_invite_accepter'
    description: Provides a resource to accept a pending GuardDuty invite on creation,
        ensure the detector has the correct master account on read, and disassociate
        with the master account upon removal.
    arguments:
        detector_id:
            description: The detector ID of the member GuardDuty account.
            required: true
            policy: ''
            notes: ''
        master_account_id:
            description: AWS account ID for master account.
            required: true
            policy: ''
            notes: ''
    attributes:
        id:
            description: GuardDuty member detector ID
    timeouts: {}
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKaGQzTmZaM1ZoY21Sa2RYUjVYMlJsZEdWamRHOXlJaUFpYldGemRHVnlJ
        aUI3ZlFvS2NtVnpiM1Z5WTJVZ0ltRjNjMTluZFdGeVpHUjFkSGxmWkdWMFpXTjBiM0lpSUNKdFpX
        MWlaWElpSUhzS0lDQndjbTkyYVdSbGNpQTlJQ0poZDNNdVpHVjJJZ3A5Q2dweVpYTnZkWEpqWlNB
        aVlYZHpYMmQxWVhKa1pIVjBlVjl0WlcxaVpYSWlJQ0prWlhZaUlIc0tJQ0JoWTJOdmRXNTBYMmxr
        SUNBOUlDSWtlMkYzYzE5bmRXRnlaR1IxZEhsZlpHVjBaV04wYjNJdWJXVnRZbVZ5TG1GalkyOTFi
        blJmYVdSOUlnb2dJR1JsZEdWamRHOXlYMmxrSUQwZ0lpUjdZWGR6WDJkMVlYSmtaSFYwZVY5a1pY
        UmxZM1J2Y2k1dFlYTjBaWEl1YVdSOUlnb2dJR1Z0WVdsc0lDQWdJQ0FnSUQwZ0luSmxjWFZwY21W
        a1FHVjRZVzF3YkdVdVkyOXRJZ29nSUdsdWRtbDBaU0FnSUNBZ0lEMGdkSEoxWlFwOUNncHlaWE52
        ZFhKalpTQWlZWGR6WDJkMVlYSmtaSFYwZVY5cGJuWnBkR1ZmWVdOalpYQjBaWElpSUNKdFpXMWla
        WElpSUhzS0lDQmtaWEJsYm1SelgyOXVJRDBnV3lKaGQzTmZaM1ZoY21Sa2RYUjVYMjFsYldKbGNp
        NWtaWFlpWFFvZ0lIQnliM1pwWkdWeUlDQWdQU0FpWVhkekxtUmxkaUlLQ2lBZ1pHVjBaV04wYjNK
        ZmFXUWdJQ0FnSUNBZ1BTQWlKSHRoZDNOZlozVmhjbVJrZFhSNVgyUmxkR1ZqZEc5eUxtMWxiV0ps
        Y2k1cFpIMGlDaUFnYldGemRHVnlYMkZqWTI5MWJuUmZhV1FnUFNBaUpIdGhkM05mWjNWaGNtUmtk
        WFI1WDJSbGRHVmpkRzl5TG0xaGMzUmxjaTVoWTJOdmRXNTBYMmxrZlNJS2ZRbz0=
    import: !!binary |
        Q2dwZ1lYZHpYMmQxWVhKa1pIVjBlVjlwYm5acGRHVmZZV05qWlhCMFpYSmdJR05oYmlCaVpTQnBi
        WEJ2Y25SbFpDQjFjMmx1WnlCMGFHVWdkR2hsSUcxbGJXSmxjaUJIZFdGeVpFUjFkSGtnWkdWMFpX
        TjBiM0lnU1VRc0lHVXVaeTRLQ2c9PQ==
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjNjeTlpYkc5aUwyMWhjM1JsY2k5M1pXSnphWFJsTDJSdlkz
        TXZjaTluZFdGeVpHUjFkSGxmYVc1MmFYUmxYMkZqWTJWd2RHVnlMbWgwYld3dWJXRnlhMlJ2ZDI0
        PQ==
