aws_kms_alias:
    status: HOLD
    subcategory: KMS
    layout: aws
    page_title: 'AWS: aws_kms_alias'
    description: Provides a display name for a customer master key.
    arguments:
        name:
            description: The display name of the alias. The name must start with the
                word "alias" followed by a forward slash (alias/)
            required: false
            policy: ''
            notes: ''
        name_prefix:
            description: Creates an unique alias beginning with the specified prefix.
            required: false
            policy: ''
            notes: ''
        target_key_id:
            description: Identifier for the key for which the alias is for, can be
                either an ARN or key_id.
            required: true
            policy: ''
            notes: ''
    attributes:
        arn:
            description: The Amazon Resource Name (ARN) of the key alias.
        target_key_arn:
            description: The Amazon Resource Name (ARN) of the target key identifier.
    timeouts: {}
