aws_waf_xss_match_set:
    status: ASSESS
    subcategory: WAF
    layout: aws
    page_title: 'AWS: aws_waf_xss_match_set'
    description: Provides a AWS WAF XssMatchSet resource.
    arguments:
        name:
            description: The name or description of the SizeConstraintSet.
            required: true
            policy: ''
            notes: ''
        xss_match_tuples:
            description: The parts of web requests that you want to inspect for cross-site
                scripting attacks.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the WAF XssMatchSet.
        arn:
            description: Amazon Resource Name (ARN)
    timeouts: {}
