aws_sns_topic_subscription:
    status: ASSESS
    subcategory: SNS
    layout: aws
    page_title: 'AWS: aws_sns_topic_subscription'
    description: Provides a resource for subscribing to SNS topics.
    arguments:
        topic_arn:
            description: The ARN of the SNS topic to subscribe to
            required: true
            policy: ''
            notes: ''
        protocol:
            description: 'The protocol to use. The possible values for this are: `sqs`,
                `sms`, `lambda`, `application`. (`http` or `https` are partially supported,
                see below'
            required: true
            policy: ''
            notes: ''
        endpoint:
            description: The endpoint to send data to, the contents will vary with
                the protocol. (see below for more information)
            required: true
            policy: ''
            notes: ''
        endpoint_auto_confirms:
            description: Boolean indicating whether the end point is capable of [auto
                confirming subscription](http://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.html#SendMessageToHttp.prepare
            required: false
            policy: ''
            notes: ''
        confirmation_timeout_in_minutes:
            description: Integer indicating number of minutes to wait in retying mode
                for fetching subscription arn before marking it as failure. Only applicable
                for http and https protocols (default is 1 minute).
            required: false
            policy: ''
            notes: ''
        raw_message_delivery:
            description: Boolean indicating whether or not to enable raw message delivery
                (the original message is directly passed, not wrapped in JSON with
                the original message in the message property
            required: false
            policy: ''
            notes: ''
        filter_policy:
            description: JSON String with the filter policy that will be used in the
                subscription to filter messages seen by the target resource. Refer
                to the [SNS docs](https://docs.aws.amazon.com/sns/latest/dg/message-filtering.html
            required: false
            policy: ''
            notes: ''
        delivery_policy:
            description: JSON String with the delivery policy (retries, backoff, etc.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ARN of the subscription
        topic_arn:
            description: The ARN of the topic the subscription belongs to
        protocol:
            description: The protocol being used
        endpoint:
            description: The full endpoint to send data to (SQS ARN, HTTP(S) URL,
                Application ARN, SMS number, etc.)
        arn:
            description: The ARN of the subscription stored as a more user-friendly
                property
    timeouts: {}
