aws_dx_gateway_association:
    status: HOLD
    subcategory: Direct Connect
    layout: aws
    page_title: 'AWS: aws_dx_gateway_association'
    description: Associates a Direct Connect Gateway with a VGW or transit gateway.
    arguments:
        dx_gateway_id:
            description: The ID of the Direct Connect gateway.
            required: true
            policy: ''
            notes: ''
        associated_gateway_id:
            description: The ID of the VGW or transit gateway with which to associate
                the Direct Connect gateway.
            required: false
            policy: ''
            notes: ''
        vpn_gateway_id:
            description: '*Deprecated:* Use `associated_gateway_id` instead. The ID
                of the VGW with which to associate the gateway.'
            required: false
            policy: ''
            notes: ''
        associated_gateway_owner_account_id:
            description: The ID of the AWS account that owns the VGW or transit gateway
                with which to associate the Direct Connect gateway.
            required: false
            policy: ''
            notes: ''
        proposal_id:
            description: The ID of the Direct Connect gateway association proposal.
            required: false
            policy: ''
            notes: ''
        allowed_prefixes:
            description: VPC prefixes (CIDRs
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the Direct Connect gateway association resource.
        associated_gateway_type:
            description: The type of the associated gateway, `transitGateway` or `virtualPrivateGateway`.
        dx_gateway_association_id:
            description: The ID of the Direct Connect gateway association.
        dx_gateway_owner_account_id:
            description: The ID of the AWS account that owns the Direct Connect gateway.
    timeouts: {}
