aws_elasticache_replication_group:
    status: ASSESS
    subcategory: ElastiCache
    layout: aws
    page_title: 'AWS: aws_elasticache_replication_group'
    description: Provides an ElastiCache Replication Group resource.
    arguments:
        replication_group_id:
            description: The replication group identifier. This parameter is stored
                as a lowercase string.
            required: true
            policy: ''
            notes: ''
        replication_group_description:
            description: A user-created description for the replication group.
            required: true
            policy: ''
            notes: ''
        number_cache_clusters:
            description: The number of cache clusters (primary and replicas
            required: false
            policy: ''
            notes: ''
        node_type:
            description: The compute and memory capacity of the nodes in the node
                group.
            required: true
            policy: ''
            notes: ''
        automatic_failover_enabled:
            description: Specifies whether a read-only replica will be automatically
                promoted to read/write primary if the existing primary fails. If true,
                Multi-AZ is enabled for this replication group. If false, Multi-AZ
                is disabled for this replication group. Must be enabled for Redis
                (cluster mode enabled
            required: false
            policy: ''
            notes: ''
        auto_minor_version_upgrade:
            description: Specifies whether a minor engine upgrades will be applied
                automatically to the underlying Cache Cluster instances during the
                maintenance window. Defaults to `true`.
            required: false
            policy: ''
            notes: ''
        availability_zones:
            description: A list of EC2 availability zones in which the replication
                group's cache clusters will be created. The order of the availability
                zones in the list is not important.
            required: false
            policy: ''
            notes: ''
        engine:
            description: The name of the cache engine to be used for the clusters
                in this replication group. e.g. `redis`
            required: false
            policy: ''
            notes: ''
        at_rest_encryption_enabled:
            description: Whether to enable encryption at rest.
            required: false
            policy: ''
            notes: ''
        transit_encryption_enabled:
            description: Whether to enable encryption in transit.
            required: false
            policy: ''
            notes: ''
        auth_token:
            description: The password used to access a password protected server.
                Can be specified only if `transit_encryption_enabled = true`.
            required: false
            policy: ''
            notes: ''
        kms_key_id:
            description: The ARN of the key that you wish to use if encrypting at
                rest. If not supplied, uses service managed encryption. Can be specified
                only if `at_rest_encryption_enabled = true`.
            required: false
            policy: ''
            notes: ''
        engine_version:
            description: The version number of the cache engine to be used for the
                cache clusters in this replication group.
            required: false
            policy: ''
            notes: ''
        parameter_group_name:
            description: The name of the parameter group to associate with this replication
                group. If this argument is omitted, the default cache parameter group
                for the specified engine is used.
            required: false
            policy: ''
            notes: ''
        port:
            description: The port number on which each of the cache nodes will accept
                connections. For Memcache the default is 11211, and for Redis the
                default port is 6379.
            required: false
            policy: ''
            notes: ''
        subnet_group_name:
            description: The name of the cache subnet group to be used for the replication
                group.
            required: false
            policy: ''
            notes: ''
        security_group_names:
            description: A list of cache security group names to associate with this
                replication group.
            required: false
            policy: ''
            notes: ''
        security_group_ids:
            description: One or more Amazon VPC security groups associated with this
                replication group. Use this parameter only when you are creating a
                replication group in an Amazon Virtual Private Cloud
            required: false
            policy: ''
            notes: ''
        snapshot_arns:
            description: A single-element string list containing an
            required: false
            policy: ''
            notes: ''
        snapshot_name:
            description: The name of a snapshot from which to restore data into the
                new node group. Changing the `snapshot_name` forces a new resource.
            required: false
            policy: ''
            notes: ''
        maintenance_window:
            description: Specifies the weekly time range for when maintenance
            required: false
            policy: ''
            notes: ''
        notification_topic_arn:
            description: An Amazon Resource Name (ARN
            required: false
            policy: ''
            notes: ''
        snapshot_window:
            description: The daily time range (in UTC
            required: false
            policy: ''
            notes: ''
        snapshot_retention_limit:
            description: The number of days for which ElastiCache will
            required: false
            policy: ''
            notes: ''
        apply_immediately:
            description: Specifies whether any modifications are applied immediately,
                or during the next maintenance window. Default is `false`.
            required: false
            policy: ''
            notes: ''
        tags:
            description: A map of tags to assign to the resource
            required: false
            policy: ''
            notes: ''
        cluster_mode:
            description: Create a native redis cluster. `automatic_failover_enabled`
                must be set to true. Cluster Mode documented below. Only 1 `cluster_mode`
                block is allowed.
            required: false
            policy: ''
            notes: ''
        replicas_per_node_group:
            description: Specify the number of replica nodes in each node group. Valid
                values are 0 to 5. Changing this number will force a new resource.
            required: true
            policy: ''
            notes: ''
        num_node_groups:
            description: Specify the number of node groups (shards
            required: true
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the ElastiCache Replication Group.
        configuration_endpoint_address:
            description: The address of the replication group configuration endpoint
                when cluster mode is enabled.
        primary_endpoint_address:
            description: (Redis only) The address of the endpoint for the primary
                node in the replication group, if the cluster mode is disabled.
        member_clusters:
            description: The identifiers of all the nodes that are part of this replication
                group.
    timeouts: {}
