aws_redshift_parameter_group:
    status: HOLD
    subcategory: Redshift
    layout: aws
    page_title: 'AWS: aws_redshift_parameter_group'
    description: Provides a Redshift Cluster parameter group resource.
    arguments:
        name:
            description: The name of the Redshift parameter.
            required: true
            policy: ''
            notes: ''
        family:
            description: The family of the Redshift parameter group.
            required: true
            policy: ''
            notes: ''
        description:
            description: The description of the Redshift parameter group. Defaults
                to "Managed by Terraform".
            required: false
            policy: ''
            notes: ''
        parameter:
            description: A list of Redshift parameters to apply.
            required: false
            policy: ''
            notes: ''
        value:
            description: The value of the Redshift parameter.
            required: true
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
    attributes:
        arn:
            description: Amazon Resource Name (ARN) of parameter group
        id:
            description: The Redshift parameter group name.
    timeouts: {}
