aws_iam_group_membership:
    status: HOLD
    subcategory: IAM
    layout: aws
    page_title: 'AWS: aws_iam_group_membership'
    description: Provides a top level resource to manage IAM Group membership for
        IAM Users.
    arguments:
        name:
            description: The name to identify the Group Membership
            required: true
            policy: ''
            notes: ''
        users:
            description: A list of IAM User names to associate with the Group
            required: true
            policy: ''
            notes: ''
        group:
            description: The IAM Group name to attach the list of `users` to
            required: true
            policy: ''
            notes: ''
    attributes:
        name:
            description: The name to identify the Group Membership
        users:
            description: list of IAM User names
    timeouts: {}
