aws_ssm_parameter:
    status: HOLD
    subcategory: SSM
    layout: aws
    page_title: 'AWS: aws_ssm_parameter'
    description: Provides a SSM Parameter resource
    arguments:
        name:
            description: The name of the parameter. If the name contains a path (e.g.
                any forward slashes (`/`)), it must be fully qualified with a leading
                forward slash (`/`). For additional requirements and constraints,
                see the [AWS SSM User Guide](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-parameter-name-constraints.html).
            required: true
            policy: ''
            notes: ''
        type:
            description: The type of the parameter. Valid types are `String`, `StringList`
                and `SecureString`.
            required: true
            policy: ''
            notes: ''
        value:
            description: The value of the parameter.
            required: true
            policy: ''
            notes: ''
        description:
            description: The description of the parameter.
            required: false
            policy: ''
            notes: ''
        tier:
            description: The tier of the parameter. If not specified, will default
                to `Standard`. Valid tiers are `Standard` and `Advanced`. For more
                information on parameter tiers, see the [AWS SSM Parameter tier comparison
                and guide](https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-advanced-parameters.html).
            required: false
            policy: ''
            notes: ''
        key_id:
            description: The KMS key id or arn for encrypting a SecureString.
            required: false
            policy: ''
            notes: ''
        overwrite:
            description: Overwrite an existing parameter. If not specified, will default
                to `false` if the resource has not been created by terraform to avoid
                overwrite of existing resource and will default to `true` otherwise
                (terraform lifecycle rules should then be used to manage the update
                behavior).
            required: false
            policy: ''
            notes: ''
        allowed_pattern:
            description: A regular expression used to validate the parameter value.
            required: false
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the object.
            required: false
            policy: ''
            notes: ''
    attributes:
        arn:
            description: The ARN of the parameter.
        name:
            description: (Required) The name of the parameter.
        description:
            description: (Required) The description of the parameter.
        type:
            description: (Required) The type of the parameter. Valid types are `String`,
                `StringList` and `SecureString`.
        value:
            description: (Required) The value of the parameter.
        version:
            description: The version of the parameter.
    timeouts: {}
