aws_ec2_transit_gateway:
    status: HOLD
    subcategory: EC2
    layout: aws
    page_title: 'AWS: aws_ec2_transit_gateway'
    description: Manages an EC2 Transit Gateway
    arguments:
        amazon_side_asn:
            description: Private Autonomous System Number (ASN
            required: false
            policy: ''
            notes: ''
        auto_accept_shared_attachments:
            description: 'Whether resource attachment requests are automatically accepted.
                Valid values: `disable`, `enable`. Default value: `disable`.'
            required: false
            policy: ''
            notes: ''
        default_route_table_association:
            description: 'Whether resource attachments are automatically associated
                with the default association route table. Valid values: `disable`,
                `enable`. Default value: `enable`.'
            required: false
            policy: ''
            notes: ''
        default_route_table_propagation:
            description: 'Whether resource attachments automatically propagate routes
                to the default propagation route table. Valid values: `disable`, `enable`.
                Default value: `enable`.'
            required: false
            policy: ''
            notes: ''
        description:
            description: Description of the EC2 Transit Gateway.
            required: false
            policy: ''
            notes: ''
        dns_support:
            description: 'Whether DNS support is enabled. Valid values: `disable`,
                `enable`. Default value: `enable`.'
            required: false
            policy: ''
            notes: ''
        tags:
            description: Key-value tags for the EC2 Transit Gateway.
            required: false
            policy: ''
            notes: ''
        vpn_ecmp_support:
            description: 'Whether VPN Equal Cost Multipath Protocol support is enabled.
                Valid values: `disable`, `enable`. Default value: `enable`.'
            required: false
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
