aws_athena_workgroup:
    status: HOLD
    subcategory: Athena
    layout: aws
    page_title: 'AWS: aws_athena_workgroup'
    description: Manages an Athena Workgroup.
    arguments:
        name:
            description: Name of the workgroup.
            required: true
            policy: ''
            notes: ''
        configuration:
            description: Configuration block with various settings for the workgroup.
                Documented below.
            required: false
            policy: ''
            notes: ''
        description:
            description: Description of the workgroup.
            required: false
            policy: ''
            notes: ''
        state:
            description: State of the workgroup. Valid values are `DISABLED` or `ENABLED`.
                Defaults to `ENABLED`.
            required: false
            policy: ''
            notes: ''
        tags:
            description: Key-value mapping of resource tags for the workgroup.
            required: false
            policy: ''
            notes: ''
        force_destroy:
            description: The option to delete the workgroup and its contents even
                if the workgroup contains any named queries.
            required: false
            policy: ''
            notes: ''
    attributes:
        arn:
            description: Amazon Resource Name (ARN) of the workgroup
        id:
            description: The workgroup name
    timeouts: {}
