aws_lambda_permission:
    status: HOLD
    subcategory: Lambda
    layout: aws
    page_title: 'AWS: aws_lambda_permission'
    description: Creates a Lambda function permission.
    arguments: {}
    attributes: {}
    timeouts: {}
