aws_sagemaker_notebook_instance:
    status: ASSESS
    subcategory: Sagemaker
    layout: aws
    page_title: 'AWS: aws_sagemaker_notebook_instance'
    description: Provides a Sagemaker Notebook Instance resource.
    arguments:
        name:
            description: The name of the notebook instance (must be unique).
            required: true
            policy: ''
            notes: ''
        role_arn:
            description: The ARN of the IAM role to be used by the notebook instance
                which allows SageMaker to call other services on your behalf.
            required: true
            policy: ''
            notes: ''
        instance_type:
            description: The name of ML compute instance type.
            required: true
            policy: ''
            notes: ''
        subnet_id:
            description: The VPC subnet ID.
            required: false
            policy: ''
            notes: ''
        security_groups:
            description: The associated security groups.
            required: false
            policy: ''
            notes: ''
        kms_key_id:
            description: The AWS Key Management Service (AWS KMS
            required: false
            policy: ''
            notes: ''
        lifecycle_config_name:
            description: The name of a lifecycle configuration to associate with the
                notebook instance.
            required: false
            policy: ''
            notes: ''
        direct_internet_access:
            description: 'Set to `Disabled` to disable internet access to notebook.
                Requires `security_groups` and `subnet_id` to be set. Supported values:
                `Enabled` (Default'
            required: false
            policy: ''
            notes: ''
        tags:
            description: A map of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The name of the notebook instance.
        arn:
            description: The Amazon Resource Name (ARN) assigned by AWS to this notebook
                instance.
    timeouts: {}
