aws_ecs_cluster:
    status: ASSESS
    subcategory: ECS
    layout: aws
    page_title: 'AWS: aws_ecs_cluster'
    description: Provides an ECS cluster.
    arguments:
        name:
            description: The name of the cluster (up to 255 letters, numbers, hyphens,
                and underscores)
            required: true
            policy: ''
            notes: ''
        capacity_providers:
            description: List of short names of one or more capacity providers to
                associate with the cluster. Valid values also include `FARGATE` and
                `FARGATE_SPOT`.
            required: false
            policy: ''
            notes: ''
        default_capacity_provider_strategy:
            description: The capacity provider strategy to use by default for the
                cluster. Can be one or more.  Defined below.
            required: false
            policy: ''
            notes: ''
        tags:
            description: Key-value map of resource tags
            required: false
            policy: ''
            notes: ''
        setting:
            description: Configuration block(s
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The Amazon Resource Name (ARN) that identifies the cluster
        arn:
            description: The Amazon Resource Name (ARN) that identifies the cluster
    timeouts: {}
