aws_backup_selection:
    status: ASSESS
    subcategory: Backup
    layout: aws
    page_title: 'AWS: aws_backup_selection'
    description: Manages selection conditions for AWS Backup plan resources.
    arguments:
        name:
            description: The display name of a resource selection document.
            required: true
            policy: ''
            notes: ''
        plan_id:
            description: The backup plan ID to be associated with the selection of
                resources.
            required: true
            policy: ''
            notes: ''
        iam_role_arn:
            description: The ARN of the IAM role that AWS Backup uses to authenticate
                when restoring and backing up the target resource. See the [AWS Backup
                Developer Guide](https://docs.aws.amazon.com/aws-backup/latest/devguide/access-control.html#managed-policies
            required: true
            policy: ''
            notes: ''
        selection_tag:
            description: Tag-based conditions used to specify a set of resources to
                assign to a backup plan.
            required: false
            policy: ''
            notes: ''
        resources:
            description: An array of strings that either contain Amazon Resource Names
                (ARNs
            required: false
            policy: ''
            notes: ''
        type:
            description: An operation, such as `StringEquals`, that is applied to
                a key-value pair used to filter resources in a selection.
            required: true
            policy: ''
            notes: ''
        key:
            description: The key in a key-value pair.
            required: true
            policy: ''
            notes: ''
        value:
            description: The value in a key-value pair.
            required: true
            policy: ''
            notes: ''
    attributes:
        id:
            description: Backup Selection identifier
    timeouts: {}
