aws_cloudwatch_log_stream:
    status: ASSESS
    subcategory: CloudWatch
    layout: aws
    page_title: 'AWS: aws_cloudwatch_log_stream'
    description: Provides a CloudWatch Log Stream resource.
    arguments:
        name:
            description: The name of the log stream. Must not be longer than 512 characters
                and must not contain `:`
            required: true
            policy: ''
            notes: ''
        log_group_name:
            description: The name of the log group under which the log stream is to
                be created.
            required: true
            policy: ''
            notes: ''
    attributes:
        arn:
            description: The Amazon Resource Name (ARN) specifying the log stream.
    timeouts: {}
