aws_iam_account_password_policy:
    status: ASSESS
    subcategory: IAM
    layout: aws
    page_title: 'AWS: aws_iam_account_password_policy'
    description: Manages Password Policy for the AWS Account.
    arguments:
        allow_users_to_change_password:
            description: Whether to allow users to change their own password
            required: false
            policy: ''
            notes: ''
        hard_expiry:
            description: Whether users are prevented from setting a new password after
                their password has expired
            required: false
            policy: ''
            notes: ''
        max_password_age:
            description: The number of days that an user password is valid.
            required: false
            policy: ''
            notes: ''
        minimum_password_length:
            description: Minimum length to require for user passwords.
            required: false
            policy: ''
            notes: ''
        password_reuse_prevention:
            description: The number of previous passwords that users are prevented
                from reusing.
            required: false
            policy: ''
            notes: ''
        require_lowercase_characters:
            description: Whether to require lowercase characters for user passwords.
            required: false
            policy: ''
            notes: ''
        require_numbers:
            description: Whether to require numbers for user passwords.
            required: false
            policy: ''
            notes: ''
        require_symbols:
            description: Whether to require symbols for user passwords.
            required: false
            policy: ''
            notes: ''
        require_uppercase_characters:
            description: Whether to require uppercase characters for user passwords.
            required: false
            policy: ''
            notes: ''
    attributes:
        expire_passwords:
            description: Indicates whether passwords in the account expire.
    timeouts: {}
