aws_codedeploy_deployment_config:
    status: ASSESS
    subcategory: CodeDeploy
    layout: aws
    page_title: 'AWS: aws_codedeploy_deployment_config'
    description: Provides a CodeDeploy deployment config.
    arguments:
        deployment_config_name:
            description: The name of the deployment config.
            required: false
            policy: ''
            notes: ''
        compute_platform:
            description: The compute platform can be `Server`, `Lambda`, or `ECS`.
                Default is `Server`.
            required: false
            policy: ''
            notes: ''
        minimum_healthy_hosts:
            description: A minimum_healthy_hosts block. Required for `Server` compute
                platform. Minimum Healthy Hosts are documented below.
            required: false
            policy: ''
            notes: ''
        traffic_routing_config:
            description: A traffic_routing_config block. Traffic Routing Config is
                documented below.
            required: false
            policy: ''
            notes: ''
        type:
            description: Type of traffic routing config. One of `TimeBasedCanary`,
                `TimeBasedLinear`, `AllAtOnce`.
            required: false
            policy: ''
            notes: ''
        value:
            description: The value when the type is `FLEET_PERCENT` represents the
                minimum number of healthy instances as
            required: false
            policy: ''
            notes: ''
        time_based_canary:
            description: The time based canary configuration information. If `type`
                is `TimeBasedLinear`, use `time_based_linear` instead.
            required: false
            policy: ''
            notes: ''
        time_based_linear:
            description: The time based linear configuration information. If `type`
                is `TimeBasedCanary`, use `time_based_canary` instead.
            required: false
            policy: ''
            notes: ''
        interval:
            description: The number of minutes between each incremental traffic shift
                of a `TimeBasedLinear` deployment.
            required: false
            policy: ''
            notes: ''
        percentage:
            description: The percentage of traffic that is shifted at the start of
                each increment of a `TimeBasedLinear` deployment.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The deployment group's config name.
        deployment_config_id:
            description: The AWS Assigned deployment config id
    timeouts: {}
    usage: {}
    import: !!binary |
        Q2dwRGIyUmxSR1Z3Ykc5NUlFUmxjR3h2ZVcxbGJuUWdRMjl1Wm1sbmRYSmhkR2x2Ym5NZ1kyRnVJ
        R0psSUdsdGNHOXlkR1ZrSUhWemFXNW5JSFJvWlNCZ1pHVndiRzk1YldWdWRGOWpiMjVtYVdkZmJt
        RnRaV0FzSUdVdVp5NEtDZz09
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjNjeTlpYkc5aUwyMWhjM1JsY2k5M1pXSnphWFJsTDJSdlkz
        TXZjaTlqYjJSbFpHVndiRzk1WDJSbGNHeHZlVzFsYm5SZlkyOXVabWxuTG1oMGJXd3ViV0Z5YTJS
        dmQyND0=
