aws_network_interface_sg_attachment:
    status: ASSESS
    subcategory: VPC
    layout: aws
    page_title: 'AWS: aws_network_interface_sg_attachment'
    description: Associates a security group with a network interface.
    arguments: {}
    attributes: {}
    timeouts: {}
