aws_lb_listener_rule:
    status: HOLD
    subcategory: Elastic Load Balancing v2 (ALB/NLB)
    layout: aws
    page_title: 'AWS: aws_lb_listener_rule'
    description: Provides a Load Balancer Listener Rule resource.
    arguments:
        listener_arn:
            description: The ARN of the listener to which to attach the rule.
            required: false
            policy: ''
            notes: ''
        priority:
            description: The priority for the rule between `1` and `50000`. Leaving
                it unset will automatically set the rule with next available priority
                after currently existing highest rule. A listener can't have multiple
                rules with the same priority.
            required: false
            policy: ''
            notes: ''
        action:
            description: An Action block. Action blocks are documented below.
            required: true
            policy: ''
            notes: ''
        condition:
            description: A Condition block. Multiple condition blocks of different
                types can be set and all must be satisfied for the rule to match.
                Condition blocks are documented below.
            required: true
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ARN of the rule (matches `arn`)
        arn:
            description: The ARN of the rule (matches `id`)
    timeouts: {}
