aws_s3_bucket_metric:
    status: ASSESS
    subcategory: S3
    layout: aws
    page_title: 'AWS: aws_s3_bucket_metric'
    description: Provides a S3 bucket metrics configuration resource.
    arguments:
        bucket:
            description: The name of the bucket to put metric configuration.
            required: false
            policy: ''
            notes: ''
        name:
            description: Unique identifier of the metrics configuration for the bucket.
            required: false
            policy: ''
            notes: ''
        filter:
            description: '[Object filtering](http://docs.aws.amazon.com/AmazonS3/latest/dev/metrics-configurations.html#metrics-configurations-filter'
            required: false
            policy: ''
            notes: ''
        prefix:
            description: Object prefix for filtering (singular).
            required: false
            policy: ''
            notes: ''
        tags:
            description: Object tags for filtering (up to 10).
            required: false
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
    usage: {}
    import: !!binary |
        Q2dwVE15QmlkV05yWlhRZ2JXVjBjbWxqSUdOdmJtWnBaM1Z5WVhScGIyNXpJR05oYmlCaVpTQnBi
        WEJ2Y25SbFpDQjFjMmx1WnlCZ1luVmphMlYwT20xbGRISnBZMkFzSUdVdVp5NEtDZz09
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXRjNjeTlpYkc5aUwyMWhjM1JsY2k5M1pXSnphWFJsTDJSdlkz
        TXZjaTl6TTE5aWRXTnJaWFJmYldWMGNtbGpMbWgwYld3dWJXRnlhMlJ2ZDI0PQ==
