aws_dx_connection:
    status: HOLD
    subcategory: Direct Connect
    layout: aws
    page_title: 'AWS: aws_dx_connection'
    description: Provides a Connection of Direct Connect.
    arguments:
        name:
            description: The name of the connection.
            required: true
            policy: ''
            notes: ''
        bandwidth:
            description: 'The bandwidth of the connection. Valid values for dedicated
                connections: 1Gbps, 10Gbps. Valid values for hosted connections: 50Mbps,
                100Mbps, 200Mbps, 300Mbps, 400Mbps, 500Mbps, 1Gbps, 2Gbps, 5Gbps and
                10Gbps. Case sensitive.'
            required: true
            policy: ''
            notes: ''
        location:
            description: The AWS Direct Connect location where the connection is located.
                See [DescribeLocations](https://docs.aws.amazon.com/directconnect/latest/APIReference/API_DescribeLocations.html
            required: true
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the connection.
        arn:
            description: The ARN of the connection.
        jumbo_frame_capable:
            description: Boolean value representing if jumbo frames have been enabled
                for this connection.
        has_logical_redundancy:
            description: Indicates whether the connection supports a secondary BGP
                peer in the same address family (IPv4/IPv6).
        aws_device:
            description: The Direct Connect endpoint on which the physical connection
                terminates.
    timeouts: {}
