aws_iam_group_policy_attachment:
    status: ASSESS
    subcategory: IAM
    layout: aws
    page_title: 'AWS: aws_iam_group_policy_attachment'
    description: Attaches a Managed IAM Policy to an IAM group
    arguments:
        group:
            description: '- The group the policy should be applied to'
            required: true
            policy: ''
            notes: ''
        policy_arn:
            description: '- The ARN of the policy you want to apply'
            required: true
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
