aws_waf_rule:
    status: ASSESS
    subcategory: WAF
    layout: aws
    page_title: 'AWS: aws_waf_rule'
    description: Provides a AWS WAF rule resource.
    arguments:
        metric_name:
            description: The name or description for the Amazon CloudWatch metric
                of this rule. The name can contain only alphanumeric characters (A-Z,
                a-z, 0-9); the name can't contain whitespace.
            required: true
            policy: ''
            notes: ''
        name:
            description: The name or description of the rule.
            required: true
            policy: ''
            notes: ''
        predicates:
            description: The objects to include in a rule (documented below).
            required: false
            policy: ''
            notes: ''
        tags:
            description: Key-value map of resource tags
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the WAF rule.
        arn:
            description: The ARN of the WAF rule.
    timeouts: {}
