aws_securityhub_product_subscription:
    status: HOLD
    subcategory: Security Hub
    layout: aws
    page_title: 'AWS: aws_securityhub_product_subscription'
    description: Subscribes to a Security Hub product.
    arguments:
        product_arn:
            description: The ARN of the product that generates findings that you want
                to import into Security Hub - see below.
            required: true
            policy: ''
            notes: ''
    attributes:
        arn:
            description: The ARN of a resource that represents your subscription to
                the product that generates the findings that you want to import into
                Security Hub.
    timeouts: {}
