aws_vpn_connection_route:
    status: ASSESS
    subcategory: VPC
    layout: aws
    page_title: 'AWS: aws_vpn_connection_route'
    description: Provides a static route between a VPN connection and a customer gateway.
    arguments:
        destination_cidr_block:
            description: The CIDR block associated with the local subnet of the customer
                network.
            required: true
            policy: ''
            notes: ''
        vpn_connection_id:
            description: The ID of the VPN connection.
            required: true
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
