aws_default_route_table:
    status: HOLD
    subcategory: VPC
    layout: aws
    page_title: 'AWS: aws_default_route_table'
    description: Provides a resource to manage a Default VPC Routing Table.
    arguments:
        default_route_table_id:
            description: The ID of the Default Routing Table.
            required: true
            policy: ''
            notes: ''
        route:
            description: A list of route objects. Their keys are documented below.
            required: false
            policy: ''
            notes: ''
        tags:
            description: A mapping of tags to assign to the resource.
            required: false
            policy: ''
            notes: ''
        propagating_vgws:
            description: A list of virtual gateways for propagation.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the routing table
        owner_id:
            description: The ID of the AWS account that owns the route table
    timeouts: {}
