aws_api_gateway_method_settings:
    status: HOLD
    subcategory: API Gateway (REST APIs)
    layout: aws
    page_title: 'AWS: aws_api_gateway_method_settings'
    description: Provides an API Gateway Method Settings, e.g. logging or monitoring.
    arguments:
        rest_api_id:
            description: The ID of the REST API
            required: true
            policy: ''
            notes: ''
        stage_name:
            description: The name of the stage
            required: true
            policy: ''
            notes: ''
        method_path:
            description: Method path defined as `{resource_path}/{http_method}` for
                an individual method override, or `*/*` for overriding all methods
                in the stage.
            required: true
            policy: ''
            notes: ''
        settings:
            description: The settings block, see below.
            required: true
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
