aws_cloudfront_distribution:
    status: HOLD
    subcategory: CloudFront
    layout: aws
    page_title: 'AWS: aws_cloudfront_distribution'
    description: Provides a CloudFront web distribution resource.
    arguments: {}
    attributes: {}
    timeouts: {}
