aws_guardduty_detector:
    status: ASSESS
    subcategory: GuardDuty
    layout: aws
    page_title: 'AWS: aws_guardduty_detector'
    description: Provides a resource to manage a GuardDuty detector
    arguments:
        enable:
            description: Enable monitoring and feedback reporting. Setting to `false`
                is equivalent to "suspending" GuardDuty. Defaults to `true`.
            required: false
            policy: ''
            notes: ''
        finding_publishing_frequency:
            description: 'Specifies the frequency of notifications sent for subsequent
                finding occurrences. If the detector is a GuardDuty member account,
                the value is determined by the GuardDuty master account and cannot
                be modified, otherwise defaults to `SIX_HOURS`. For standalone and
                GuardDuty master accounts, it must be configured in Terraform to enable
                drift detection. Valid values for standalone and master accounts:
                `FIFTEEN_MINUTES`, `ONE_HOUR`, `SIX_HOURS`. See [AWS Documentation](https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_findings_cloudwatch.html#guardduty_findings_cloudwatch_notification_frequency'
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The ID of the GuardDuty detector
        account_id:
            description: The AWS account ID of the GuardDuty detector
    timeouts: {}
