aws_secretsmanager_secret:
    status: HOLD
    subcategory: Secrets Manager
    layout: aws
    page_title: 'AWS: aws_secretsmanager_secret'
    description: Provides a resource to manage AWS Secrets Manager secret metadata
    arguments:
        name:
            description: 'Specifies the friendly name of the new secret. The secret
                name can consist of uppercase letters, lowercase letters, digits,
                and any of the following characters: `/_+=.@-` Conflicts with `name_prefix`.'
            required: false
            policy: ''
            notes: ''
        name_prefix:
            description: Creates a unique name beginning with the specified prefix.
                Conflicts with `name`.
            required: false
            policy: ''
            notes: ''
        description:
            description: A description of the secret.
            required: false
            policy: ''
            notes: ''
        kms_key_id:
            description: Specifies the ARN or alias of the AWS KMS customer master
                key (CMK
            required: false
            policy: ''
            notes: ''
        policy:
            description: A valid JSON document representing a [resource policy](https://docs.aws.amazon.com/secretsmanager/latest/userguide/auth-and-access_resource-based-policies.html).
                For more information about building AWS IAM policy documents with
                Terraform, see the [AWS IAM Policy Document Guide](https://learn.hashicorp.com/terraform/aws/iam-policy).
            required: false
            policy: ''
            notes: ''
        recovery_window_in_days:
            description: Specifies the number of days that AWS Secrets Manager waits
                before it can delete the secret. This value can be `0` to force deletion
                without recovery or range from `7` to `30` days. The default value
                is `30`.
            required: false
            policy: ''
            notes: ''
        rotation_lambda_arn:
            description: Specifies the ARN of the Lambda function that can rotate
                the secret.
            required: false
            policy: ''
            notes: ''
        rotation_rules:
            description: A structure that defines the rotation configuration for this
                secret. Defined below.
            required: false
            policy: ''
            notes: ''
        tags:
            description: Specifies a key-value map of user-defined tags that are attached
                to the secret.
            required: false
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
