postgresql_postgresql_extension:
    status: ASSESS
    layout: postgresql
    page_title: 'PostgreSQL: postgresql_extension'
    sidebar_current: docs-postgresql-resource-postgresql_extension
    description: Creates and manages an extension on a PostgreSQL server.
    arguments:
        name:
            description: The name of the extension.
            required: true
            policy: ''
            notes: ''
        schema:
            description: Sets the schema of an extension.
            required: false
            policy: ''
            notes: ''
        version:
            description: Sets the version number of the extension.
            required: false
            policy: ''
            notes: ''
        database:
            description: Which database to create the extension on. Defaults to provider
                database.
            required: false
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
