openstack_compute_flavor_access_v2:
    status: ASSESS
    layout: openstack
    page_title: 'OpenStack: openstack_compute_flavor_access_v2'
    sidebar_current: docs-openstack-resource-compute-flavor-access-v2
    description: Manages a project access for flavor V2 resource within OpenStack.
    arguments:
        region:
            description: The region in which to obtain the V2 Compute client.
            required: false
            policy: ''
            notes: ''
        flavor_id:
            description: The UUID of flavor to use. Changing this creates a new flavor
                access.
            required: true
            policy: ''
            notes: ''
        tenant_id:
            description: The UUID of tenant which is allowed to use the flavor.
            required: true
            policy: ''
            notes: ''
    attributes:
        region:
            description: See Argument Reference above.
        flavor_id:
            description: See Argument Reference above.
        tenant_id:
            description: See Argument Reference above.
    timeouts: {}
