openstack_vpnaas_endpoint_group_v2:
    status: ASSESS
    layout: openstack
    page_title: 'OpenStack: openstack_vpnaas_endpoint_group_v2'
    sidebar_current: docs-openstack-resource-vpnaas-endpoint-group-v2
    description: Manages a V2 Neutron Endpoint Group resource within OpenStack.
    arguments:
        region:
            description: The region in which to obtain the V2 Networking client.
            required: false
            policy: ''
            notes: ''
        name:
            description: The name of the group. Changing this updates the name of
            required: false
            policy: ''
            notes: ''
        tenant_id:
            description: The owner of the group. Required if admin wants to
            required: false
            policy: ''
            notes: ''
        description:
            description: The human-readable description for the group.
            required: false
            policy: ''
            notes: ''
        value_specs:
            description: Map of additional options.
            required: false
            policy: ''
            notes: ''
    attributes:
        region:
            description: See Argument Reference above.
        name:
            description: See Argument Reference above.
        tenant_id:
            description: See Argument Reference above.
        description:
            description: See Argument Reference above.
        type:
            description: See Argument Reference above.
        endpoints:
            description: See Argument Reference above.
        value_specs:
            description: See Argument Reference above.
    timeouts: {}
