openstack_objectstorage_container_v1:
    status: ASSESS
    layout: openstack
    page_title: 'OpenStack: openstack_objectstorage_container_v1'
    sidebar_current: docs-openstack-resource-objectstorage-container-v1
    description: Manages a V1 container resource within OpenStack.
    arguments:
        region:
            description: The region in which to create the container. If
            required: false
            policy: ''
            notes: ''
        name:
            description: A unique name for the container. Changing this creates a
            required: true
            policy: ''
            notes: ''
        container_read:
            description: Sets an access control list (ACL
            required: false
            policy: ''
            notes: ''
        container_sync_to:
            description: The destination for container synchronization.
            required: false
            policy: ''
            notes: ''
        container_sync_key:
            description: The secret key for container synchronization.
            required: false
            policy: ''
            notes: ''
        container_write:
            description: Sets an ACL that grants write access.
            required: false
            policy: ''
            notes: ''
        versioning:
            description: Enable object versioning. The structure is described below.
            required: false
            policy: ''
            notes: ''
        metadata:
            description: Custom key/value pairs to associate with the container.
            required: false
            policy: ''
            notes: ''
        content_type:
            description: The MIME type for the container. Changing this
            required: false
            policy: ''
            notes: ''
        force_destroy:
            description: A boolean that indicates all objects should be deleted from
                the container so that the container can be destroyed without error.
                These objects are not recoverable.
            required: false
            policy: ''
            notes: ''
    attributes:
        region:
            description: See Argument Reference above.
        name:
            description: See Argument Reference above.
        container_read:
            description: See Argument Reference above.
        container_sync_to:
            description: See Argument Reference above.
        container_sync_key:
            description: See Argument Reference above.
        container_write:
            description: See Argument Reference above.
        versioning:
            description: See Argument Reference above.
        metadata:
            description: See Argument Reference above.
        content_type:
            description: See Argument Reference above.
    timeouts: {}
