openstack_dns_zone_v2:
    status: ASSESS
    layout: openstack
    page_title: 'OpenStack: openstack_dns_zone_v2'
    sidebar_current: docs-openstack-resource-dns-zone-v2
    description: Manages a DNS zone in the OpenStack DNS Service
    arguments:
        region:
            description: The region in which to obtain the V2 Compute client.
            required: false
            policy: ''
            notes: ''
        name:
            description: The name of the zone. Note the `.` at the end of the name.
            required: false
            policy: ''
            notes: ''
        email:
            description: The email contact for the zone record.
            required: false
            policy: ''
            notes: ''
        type:
            description: The type of zone. Can either be `PRIMARY` or `SECONDARY`.
            required: false
            policy: ''
            notes: ''
        attributes:
            description: Attributes for the DNS Service scheduler.
            required: false
            policy: ''
            notes: ''
        ttl:
            description: The time to live (TTL
            required: false
            policy: ''
            notes: ''
        description:
            description: A description of the zone.
            required: false
            policy: ''
            notes: ''
        masters:
            description: An array of master DNS servers. For when `type` is
            required: false
            policy: ''
            notes: ''
        value_specs:
            description: Map of additional options. Changing this creates a
            required: false
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
    usage: {}
    import: !!binary |
        Q2dwVWFHbHpJSEpsYzI5MWNtTmxJR05oYmlCaVpTQnBiWEJ2Y25SbFpDQmllU0J6Y0dWamFXWjVh
        VzVuSUhSb1pTQjZiMjVsSUVsRU9nb0s=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXOXdaVzV6ZEdGamF5OWliRzlpTDIxaGMzUmxjaTkzWldKemFY
        UmxMMlJ2WTNNdmNpOWtibk5mZW05dVpWOTJNaTVvZEcxc0xtMWhjbXRrYjNkdQ==
