openstack_identity_role_v3:
    status: ASSESS
    layout: openstack
    page_title: 'OpenStack: openstack_identity_role_v3'
    sidebar_current: docs-openstack-resource-identity-role-v3
    description: Manages a V3 Role resource within OpenStack Keystone.
    arguments:
        domain_id:
            description: The domain the role belongs to.
            required: false
            policy: ''
            notes: ''
        region:
            description: The region in which to obtain the V3 Keystone client.
            required: false
            policy: ''
            notes: ''
    attributes:
        name:
            description: See Argument Reference above.
        domain_id:
            description: See Argument Reference above.
        region:
            description: See Argument Reference above.
    timeouts: {}
