openstack_containerinfra_clustertemplate_v1:
    status: ASSESS
    layout: openstack
    page_title: 'OpenStack: openstack_containerinfra_clustertemplate_v1'
    sidebar_current: docs-openstack-resource-containerinfra-clustertemplate-v1
    description: Manages a V1 Magnum cluster template resource within OpenStack.
    arguments: {}
    attributes: {}
    timeouts: {}
