openstack_lb_pool_v2:
    status: ASSESS
    layout: openstack
    page_title: 'OpenStack: openstack_lb_pool_v2'
    sidebar_current: docs-openstack-resource-lb-pool-v2
    description: Manages a V2 pool resource within OpenStack.
    arguments:
        region:
            description: The region in which to obtain the V2 Networking client.
            required: false
            policy: ''
            notes: ''
        tenant_id:
            description: Required for admins. The UUID of the tenant who owns
            required: false
            policy: ''
            notes: ''
        name:
            description: Human-readable name for the pool.
            required: false
            policy: ''
            notes: ''
        description:
            description: Human-readable description for the pool.
            required: false
            policy: ''
            notes: ''
        protocol:
            description: The protocol - can either be TCP, HTTP, HTTPS, PROXY
            required: true
            policy: ''
            notes: ''
        loadbalancer_id:
            description: The load balancer on which to provision this
            required: false
            policy: ''
            notes: ''
        listener_id:
            description: The Listener on which the members of the pool
            required: false
            policy: ''
            notes: ''
        lb_method:
            description: The load balancing algorithm to
            required: true
            policy: ''
            notes: ''
        admin_state_up:
            description: The administrative state of the pool.
            required: false
            policy: ''
            notes: ''
        type:
            description: The type of persistence mode. The current specification
            required: true
            policy: ''
            notes: ''
        cookie_name:
            description: The name of the cookie if persistence mode is set
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The unique ID for the pool.
        tenant_id:
            description: See Argument Reference above.
        name:
            description: See Argument Reference above.
        description:
            description: See Argument Reference above.
        protocol:
            description: See Argument Reference above.
        lb_method:
            description: See Argument Reference above.
        persistence:
            description: See Argument Reference above.
        admin_state_up:
            description: See Argument Reference above.
    timeouts: {}
