openstack_networking_qos_policy_v2:
    status: ASSESS
    layout: openstack
    page_title: 'OpenStack: openstack_networking_qos_policy_v2'
    sidebar_current: docs-openstack-resource-networking-qos-policy-v2
    description: Manages a V2 Neutron QoS policy resource within OpenStack.
    arguments:
        region:
            description: The region in which to obtain the V2 Networking client.
            required: false
            policy: ''
            notes: ''
        name:
            description: The name of the QoS policy. Changing this updates the name
                of
            required: true
            policy: ''
            notes: ''
        project_id:
            description: The owner of the QoS policy. Required if admin wants to
            required: false
            policy: ''
            notes: ''
        shared:
            description: Indicates whether this QoS policy is shared across
            required: false
            policy: ''
            notes: ''
        description:
            description: The human-readable description for the QoS policy.
            required: false
            policy: ''
            notes: ''
        is_default:
            description: Indicates whether the QoS policy is default
            required: false
            policy: ''
            notes: ''
        value_specs:
            description: Map of additional options.
            required: false
            policy: ''
            notes: ''
        tags:
            description: A set of string tags for the QoS policy.
            required: false
            policy: ''
            notes: ''
    attributes:
        region:
            description: See Argument Reference above.
        name:
            description: See Argument Reference above.
        project_id:
            description: See Argument Reference above.
        created_at:
            description: The time at which QoS policy was created.
        updated_at:
            description: The time at which QoS policy was created.
        shared:
            description: See Argument Reference above.
        description:
            description: See Argument Reference above.
        is_default:
            description: See Argument Reference above.
        revision_number:
            description: The revision number of the QoS policy.
        value_specs:
            description: See Argument Reference above.
        tags:
            description: See Argument Reference above.
        all_tags:
            description: The collection of tags assigned on the QoS policy, which
                have been
    timeouts: {}
