openstack_networking_qos_dscp_marking_rule_v2:
    status: ASSESS
    layout: openstack
    page_title: 'OpenStack: openstack_networking_qos_dscp_marking_rule_v2'
    sidebar_current: docs-openstack-resource-networking-qos-dscp-marking-rule-v2
    description: Manages a V2 Neutron QoS DSCP marking rule resource within OpenStack.
    arguments:
        region:
            description: The region in which to obtain the V2 Networking client.
            required: false
            policy: ''
            notes: ''
        qos_policy_id:
            description: The QoS policy reference. Changing this creates a new QoS
                DSCP marking rule.
            required: true
            policy: ''
            notes: ''
        dscp_mark:
            description: The value of DSCP mark. Changing this updates the DSCP mark
                value existing
            required: true
            policy: ''
            notes: ''
    attributes:
        region:
            description: See Argument Reference above.
        qos_policy_id:
            description: See Argument Reference above.
        dscp_mark:
            description: See Argument Reference above.
    timeouts: {}
