datadog_logs_index:
    status: ASSESS
    layout: datadog
    page_title: 'Datadog: datadog_logs_index'
    sidebar_current: docs-datadog-resource-logs-index
    description: Provides a Datadog logs index resource. This can be used to create
        and manage logs indexes.
    arguments:
        name:
            description: The name of the index.
            required: true
            policy: ''
            notes: ''
        filter:
            description: Logs filter.
            required: true
            policy: ''
            notes: ''
        exclusion_filter:
            description: List of exclusion filters.
            required: false
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
