datadog_timeboard:
    status: ASSESS
    layout: datadog
    page_title: 'Datadog: datadog_timeboard'
    sidebar_current: docs-datadog-resource-timeboard
    description: Provides a Datadog timeboard resource. This can be used to create
        and manage timeboards.
    arguments: {}
    attributes: {}
    timeouts: {}
