azuread_service_principal_password:
    status: ASSESS
    subcategory: Service Principals
    layout: azuread
    page_title: 'Azure Active Directory: azuread_service_principal_password'
    description: Manages a Password associated with a Service Principal within Azure
        Active Directory.
    arguments:
        service_principal_id:
            description: The ID of the Service Principal for which this password should
                be created. Changing this field forces a new resource to be created.
            required: true
            policy: ''
            notes: ''
        value:
            description: The Password for this Service Principal.
            required: true
            policy: ''
            notes: ''
        end_date:
            description: The End Date which the Password is valid until, formatted
                as a RFC3339 date string (e.g. `2018-01-01T01:02:03Z`). Changing this
                field forces a new resource to be created.
            required: false
            policy: ''
            notes: ''
        end_date_relative:
            description: A relative duration for which the Password is valid until,
                for example `240h` (10 days
            required: false
            policy: ''
            notes: One of `end_date` or `end_date_relative` must be set.
        key_id:
            description: A GUID used to uniquely identify this Key. If not specified
                a GUID will be created. Changing this field forces a new resource
                to be created.
            required: false
            policy: ''
            notes: ''
        start_date:
            description: The Start Date which the Password is valid from, formatted
                as a RFC3339 date string (e.g. `2018-01-01T01:02:03Z`). If this isn't
                specified, the current date is used.  Changing this field forces a
                new resource to be created.
            required: false
            policy: ''
            notes: ''
    attributes:
        id:
            description: The Key ID for the Service Principal Password.
    timeouts: {}
