google_compute_target_pool:
    status: ASSESS
    subcategory: Compute Engine
    layout: google
    page_title: 'Google: google_compute_target_pool'
    sidebar_current: docs-google-compute-target-pool
    description: Manages a Target Pool within GCE.
    arguments:
        name:
            description: A unique name for the resource, required by GCE. Changing
            required: true
            policy: ''
            notes: ''
        backup_pool:
            description: URL to the backup target pool. Must also set
            required: false
            policy: ''
            notes: ''
        description:
            description: Textual description field.
            required: false
            policy: ''
            notes: ''
        failover_ratio:
            description: Ratio (0 to 1
            required: false
            policy: ''
            notes: ''
        health_checks:
            description: List of zero or one health check name or self_link. Only
            required: false
            policy: ''
            notes: ''
        instances:
            description: List of instances in the pool. They can be given as
            required: false
            policy: ''
            notes: ''
        project:
            description: The ID of the project in which the resource belongs. If it
            required: false
            policy: ''
            notes: ''
        region:
            description: Where the target pool resides. Defaults to project
            required: false
            policy: ''
            notes: ''
        session_affinity:
            description: How to distribute load. Options are "NONE" (no
            required: false
            policy: ''
            notes: ''
    attributes:
        self_link:
            description: The URI of the created resource.
    timeouts: {}
