google_compute_network_peering:
    status: ASSESS
    subcategory: Compute Engine
    layout: google
    page_title: 'Google: google_compute_network_peering'
    sidebar_current: docs-google-compute-network-peering
    description: Manages a network peering within GCE.
    arguments:
        name:
            description: Name of the peering.
            required: true
            policy: ''
            notes: ''
        network:
            description: The primary network of the peering.
            required: true
            policy: ''
            notes: ''
        peer_network:
            description: The peer network in the peering. The peer network
            required: true
            policy: ''
            notes: ''
    attributes:
        state:
            description: State for the peering, either `ACTIVE` or `INACTIVE`. The
                peering is
        state_details:
            description: Details about the current state of the peering.
    timeouts: {}
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKbmIyOW5iR1ZmWTI5dGNIVjBaVjl1WlhSM2IzSnJYM0JsWlhKcGJtY2lJ
        Q0p3WldWeWFXNW5NU0lnZXdvZ0lHNWhiV1VnSUNBZ0lDQWdJQ0E5SUNKd1pXVnlhVzVuTVNJS0lD
        QnVaWFIzYjNKcklDQWdJQ0FnUFNCbmIyOW5iR1ZmWTI5dGNIVjBaVjl1WlhSM2IzSnJMbVJsWm1G
        MWJIUXVjMlZzWmw5c2FXNXJDaUFnY0dWbGNsOXVaWFIzYjNKcklEMGdaMjl2WjJ4bFgyTnZiWEIx
        ZEdWZmJtVjBkMjl5YXk1dmRHaGxjaTV6Wld4bVgyeHBibXNLZlFvS2NtVnpiM1Z5WTJVZ0ltZHZi
        MmRzWlY5amIyMXdkWFJsWDI1bGRIZHZjbXRmY0dWbGNtbHVaeUlnSW5CbFpYSnBibWN5SWlCN0Np
        QWdibUZ0WlNBZ0lDQWdJQ0FnSUQwZ0luQmxaWEpwYm1jeUlnb2dJRzVsZEhkdmNtc2dJQ0FnSUNB
        OUlHZHZiMmRzWlY5amIyMXdkWFJsWDI1bGRIZHZjbXN1YjNSb1pYSXVjMlZzWmw5c2FXNXJDaUFn
        Y0dWbGNsOXVaWFIzYjNKcklEMGdaMjl2WjJ4bFgyTnZiWEIxZEdWZmJtVjBkMjl5YXk1a1pXWmhk
        V3gwTG5ObGJHWmZiR2x1YXdwOUNncHlaWE52ZFhKalpTQWlaMjl2WjJ4bFgyTnZiWEIxZEdWZmJt
        VjBkMjl5YXlJZ0ltUmxabUYxYkhRaUlIc0tJQ0J1WVcxbElDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNB
        Z0lDQTlJQ0ptYjI5aVlYSWlDaUFnWVhWMGIxOWpjbVZoZEdWZmMzVmlibVYwZDI5eWEzTWdQU0Fp
        Wm1Gc2MyVWlDbjBLQ25KbGMyOTFjbU5sSUNKbmIyOW5iR1ZmWTI5dGNIVjBaVjl1WlhSM2IzSnJJ
        aUFpYjNSb1pYSWlJSHNLSUNCdVlXMWxJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0E5SUNKdmRH
        aGxjaUlLSUNCaGRYUnZYMk55WldGMFpWOXpkV0p1WlhSM2IzSnJjeUE5SUNKbVlXeHpaU0lLZlFv
        PQ==
    import: !!binary |
        Q2dwV1VFTWdibVYwZDI5eWF5QndaV1Z5YVc1bmN5QmpZVzRnWW1VZ2FXMXdiM0owWldRZ2RYTnBi
        bWNnZEdobElHNWhiV1VnWVc1a0lIQnliMnBsWTNRZ2IyWWdkR2hsSUhCeWFXMWhjbmtnYm1WMGQy
        OXlheUIwYUdVZ2NHVmxjbWx1WnlCbGVHbHpkSE1nYVc0Z1lXNWtJSFJvWlNCdVlXMWxJRzltSUhS
        b1pTQnVaWFIzYjNKcklIQmxaWEpwYm1jS0NnPT0=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXZHZiMmRzWlM5aWJHOWlMMjFoYzNSbGNpOTNaV0p6YVhSbEwy
        UnZZM012Y2k5amIyMXdkWFJsWDI1bGRIZHZjbXRmY0dWbGNtbHVaeTVvZEcxc0xtMWhjbXRrYjNk
        dQ==
