google_bigtable_instance:
    status: ASSESS
    subcategory: Cloud Bigtable
    layout: google
    page_title: 'Google: google_bigtable_instance'
    sidebar_current: docs-google-bigtable-instance
    description: Creates a Google Bigtable instance.
    arguments:
        name:
            description: The name (also called Instance Id in the Cloud Console
            required: true
            policy: ''
            notes: ''
        cluster:
            description: A block of cluster configuration options. This can be specified
                1 or 2 times. See structure below.
            required: true
            policy: ''
            notes: ''
        project:
            description: The ID of the project in which the resource belongs. If it
            required: false
            policy: ''
            notes: ''
        instance_type:
            description: The instance type to create. One of `"DEVELOPMENT"` or `"PRODUCTION"`.
                Defaults to `"PRODUCTION"`.
            required: false
            policy: ''
            notes: ''
        display_name:
            description: The human-readable display name of the Bigtable instance.
                Defaults to the instance `name`.
            required: false
            policy: ''
            notes: ''
        cluster_id:
            description: The ID of the Cloud Bigtable cluster.
            required: true
            policy: ''
            notes: ''
        zone:
            description: The zone to create the Cloud Bigtable cluster in. Each
            required: true
            policy: ''
            notes: ''
        num_nodes:
            description: The number of nodes in your Cloud Bigtable cluster.
            required: false
            policy: ''
            notes: ''
        storage_type:
            description: The storage type to use. One of `"SSD"` or
            required: false
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
