google_compute_target_pool:
    status: ASSESS
    subcategory: Compute Engine
    layout: google
    page_title: 'Google: google_compute_target_pool'
    sidebar_current: docs-google-compute-target-pool
    description: Manages a Target Pool within GCE.
    arguments:
        name:
            description: A unique name for the resource, required by GCE. Changing
            required: true
            policy: ''
            notes: ''
        backup_pool:
            description: URL to the backup target pool. Must also set
            required: false
            policy: ''
            notes: ''
        description:
            description: Textual description field.
            required: false
            policy: ''
            notes: ''
        failover_ratio:
            description: Ratio (0 to 1
            required: false
            policy: ''
            notes: ''
        health_checks:
            description: List of zero or one health check name or self_link. Only
            required: false
            policy: ''
            notes: ''
        instances:
            description: List of instances in the pool. They can be given as
            required: false
            policy: ''
            notes: ''
        project:
            description: The ID of the project in which the resource belongs. If it
            required: false
            policy: ''
            notes: ''
        region:
            description: Where the target pool resides. Defaults to project
            required: false
            policy: ''
            notes: ''
        session_affinity:
            description: How to distribute load. Options are "NONE" (no
            required: false
            policy: ''
            notes: ''
    attributes:
        self_link:
            description: The URI of the created resource.
    timeouts: {}
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKbmIyOW5iR1ZmWTI5dGNIVjBaVjkwWVhKblpYUmZjRzl2YkNJZ0ltUmxa
        bUYxYkhRaUlIc0tJQ0J1WVcxbElEMGdJbWx1YzNSaGJtTmxMWEJ2YjJ3aUNnb2dJR2x1YzNSaGJt
        TmxjeUE5SUZzS0lDQWdJQ0oxY3kxalpXNTBjbUZzTVMxaEwyMTVhVzV6ZEdGdVkyVXhJaXdLSUNB
        Z0lDSjFjeTFqWlc1MGNtRnNNUzFpTDIxNWFXNXpkR0Z1WTJVeUlpd0tJQ0JkQ2dvZ0lHaGxZV3gw
        YUY5amFHVmphM01nUFNCYkNpQWdJQ0JuYjI5bmJHVmZZMjl0Y0hWMFpWOW9kSFJ3WDJobFlXeDBh
        RjlqYUdWamF5NWtaV1poZFd4MExtNWhiV1VzQ2lBZ1hRcDlDZ3B5WlhOdmRYSmpaU0FpWjI5dloy
        eGxYMk52YlhCMWRHVmZhSFIwY0Y5b1pXRnNkR2hmWTJobFkyc2lJQ0prWldaaGRXeDBJaUI3Q2lB
        Z2JtRnRaU0FnSUNBZ0lDQWdJQ0FnSUNBZ0lEMGdJbVJsWm1GMWJIUWlDaUFnY21WeGRXVnpkRjl3
        WVhSb0lDQWdJQ0FnSUQwZ0lpOGlDaUFnWTJobFkydGZhVzUwWlhKMllXeGZjMlZqSUQwZ01Rb2dJ
        SFJwYldWdmRYUmZjMlZqSUNBZ0lDQWdJQ0E5SURFS2ZRbz0=
    import: !!binary |
        Q2dwVVlYSm5aWFFnY0c5dmJITWdZMkZ1SUdKbElHbHRjRzl5ZEdWa0lIVnphVzVuSUdGdWVTQnZa
        aUIwYUdVZ1ptOXNiRzkzYVc1bklHWnZjbTFoZEhNNkNnbz0=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXZHZiMmRzWlM5aWJHOWlMMjFoYzNSbGNpOTNaV0p6YVhSbEwy
        UnZZM012Y2k5amIyMXdkWFJsWDNSaGNtZGxkRjl3YjI5c0xtaDBiV3d1YldGeWEyUnZkMjQ9
