google_dns_record_set:
    status: ASSESS
    subcategory: Cloud DNS
    layout: google
    page_title: 'Google: google_dns_record_set'
    sidebar_current: docs-google-dns-record-set
    description: Manages a set of DNS records within Google Cloud DNS.
    arguments:
        managed_zone:
            description: The name of the zone in which this record set will
            required: true
            policy: ''
            notes: ''
        name:
            description: The DNS name this record set will apply to.
            required: true
            policy: ''
            notes: ''
        rrdatas:
            description: The string data for the records in this record set
            required: true
            policy: ''
            notes: ''
        ttl:
            description: The time-to-live of this record set (seconds).
            required: true
            policy: ''
            notes: ''
        type:
            description: The DNS record set type.
            required: true
            policy: ''
            notes: ''
        project:
            description: The ID of the project in which the resource belongs. If it
            required: false
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
