google_compute_project_metadata:
    status: ASSESS
    subcategory: Compute Engine
    layout: google
    page_title: 'Google: google_compute_project_metadata'
    sidebar_current: docs-google-compute-project-metadata
    description: Manages common instance metadata
    arguments:
        metadata:
            description: A series of key value pairs.
            required: true
            policy: ''
            notes: ''
        project:
            description: The ID of the project in which the resource belongs. If it
            required: false
            policy: ''
            notes: ''
    attributes: {}
    timeouts: {}
    usage: !!binary |
        Q25KbGMyOTFjbU5sSUNKbmIyOW5iR1ZmWTI5dGNIVjBaVjl3Y205cVpXTjBYMjFsZEdGa1lYUmhJ
        aUFpWkdWbVlYVnNkQ0lnZXdvZ0lHMWxkR0ZrWVhSaElEMGdld29nSUNBZ1ptOXZJQ0E5SUNKaVlY
        SWlDaUFnSUNCbWFYcDZJRDBnSW1KMWVub2lDaUFnSUNBaU1UTWlJRDBnSWpReUlnb2dJSDBLZlFv
        PQ==
    import: !!binary |
        Q2dwVWFHbHpJSEpsYzI5MWNtTmxJR05oYmlCaVpTQnBiWEJ2Y25SbFpDQjFjMmx1WnlCMGFHVWdj
        SEp2YW1WamRDQkpSRG9LQ21CMFpYSnlZV1p2Y20wZ2FXMXdiM0owSUdkdmIyZHNaVjlqYjIxd2RY
        UmxYM0J5YjJwbFkzUmZiV1YwWVdSaGRHRXVabTl2SUcxNUxYQnliMnBsWTNRdGFXUmc=
    hcl_url: !!binary |
        YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDNSbGNuSmhabTl5YlMxd2NtOTJhV1JsY25NdmRHVnlj
        bUZtYjNKdExYQnliM1pwWkdWeUxXZHZiMmRzWlM5aWJHOWlMMjFoYzNSbGNpOTNaV0p6YVhSbEwy
        UnZZM012Y2k5amIyMXdkWFJsWDNCeWIycGxZM1JmYldWMFlXUmhkR0V1YUhSdGJDNXRZWEpyWkc5
        M2JnPT0=
